### ISSUE TITLE
Long time when switching profiles

### ISSUE THREAD

**Issue by bentiss** [libratbag/piper#1]
Playing with the G700 and switching between profiles introduces an ever growing timeout between the actual action on the profile switch button (going from profile0 to profile1) and the update on the screen.

I set the G700 profile 0 to a refresh rate of 125, which outputs an error on piper terminal when we retrieve this profile:
- at launch (profile 0 selected): 1 "Ooops, rate is 125 and I don't know how to deal with that." is displayed
- going to profile1 is immediate
- going back to profile 0, 2 "Ooops..." are displayed
- going to profile 2 takes few seconds
- going back to profile 0, 6 "Ooops..." are displayed
- etc...

Looks like we forget to clean up after a profile has been loaded or we need to use a caching mechanism in piper

**Comment by Hjdskes** [comment]
I think this one can be closed, feel free to reopen if it's still too slow @bentiss :)
