### ISSUE TITLE
ButtonsPage displays macros as their integer keycodes

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#100]
I couldn't test this before, but I just noticed it with the test device from running `ratbagd.devel`: the buttonspage displays macros using their integer keycodes. This is easily solved by copying the code from `KeyStroke::_update_macro`, but that results in (unnecessary?) duplication.

I was thinking of adding a (possibly static) method to `RatbagdButton` to get the human-readable string representation of the macro, if it is mapped to a macro. What are your thoughts on this? Tagging @whot and @bentiss

**Comment by whot** [comment]
having a static dictionary to map keycodes to strings? sure, we can/should add that to ratbagd

**Comment by Hjdskes** [comment]
We can use python-evdev like `KeyStroke::_update_macro` does, and put it in the bindings (in `RatbagdButton`).

**Comment by whot** [comment]
Sounds like a plan, yep
