### ISSUE TITLE
Device has no image or its path is invalid

### ISSUE THREAD

**Issue by PlasmaPower** [libratbag/piper#109]
I have a Logitech G502, which is detected by ratbagd. However, when I try to start piper, I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gi/_propertyhelper.py", line 427, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 87, in device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/usr/lib/python3.6/site-packages/piper/mousemap.py", line 111, in __init__
    raise ValueError("Device has no image or its path is invalid")
ValueError: Device has no image or its path is invalid
```

If there's anything else I can do to help debug let me know.

**Comment by Hjdskes** [comment]
Did you install libratbag from latest master? If so, can we gets its `build/meson-logs/install-log.txt`?

**Comment by PlasmaPower** [comment]
@Hjdskes I'm using the Arch Linux package `libratbag-git`. The `install-log.txt` is [here](https://gist.github.com/PlasmaPower/de4e131ce6ccd8e775583ac2d752d736), but I suspect you'll be more interested in `pacman -Ql libratbag-git` [here](https://gist.github.com/PlasmaPower/e8ed4680689726b89f20e53d64dece75).

**Comment by Hjdskes** [comment]
Thanks; both look correct to me. Can you run the following script and paste the output?

```python
#!/usr/bin/env python3

import piper.ratbagd as ratbagd

r = ratbagd.Ratbagd()
d = r.devices[0]
print(d.get_svg('gnome'))
```

**Comment by PlasmaPower** [comment]
@Hjdskes It just outputs a newline. I'm assuming it's returning an empty string. If it can't find the SVG does it usually output an empty string or `None`?

**Comment by PlasmaPower** [comment]
Looking at the code, should I move this issue to the libratbag repo? It looks like `get_svg` is just a dbus call.

**Comment by PlasmaPower** [comment]
`ratbagctl info event4` shows the same problem:

```
event4 - Logitech Gaming Mouse G502
               SVG: 
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, disable-profile, button, button-keys, led
 Number of Buttons: 11
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (disabled)
Profile 1: (disabled) (active)
Profile 2: (disabled)
```

**Comment by Hjdskes** [comment]
Yes please; this is probably a issue in your device's driver. Can you cross link to this one for reference?

**Comment by PlasmaPower** [comment]
Moved to https://github.com/libratbag/libratbag/issues/279
