### ISSUE TITLE
'Meson project name and language' error when trying to install piper

### ISSUE THREAD

**Issue by r2rX** [libratbag/piper#110]
Hey all,
I'm running Ubuntu 17.04 x64 and i'm trying to get piper working for my Logitech G502 mouse. I've successfully installed libratbag but the issue is that I get the following error when trying to install piper:

```
xxxxx@xxxxx:~/Desktop/piper$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.39.1
Source dir: /home/xxxxx/Desktop/piper
Build dir: /home/xxxxx/Desktop/piper/builddir
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

**Comment by Hjdskes** [comment]
This likely has to do with your meson version being too old, but I cannot find anything in its release notes about `project()`. The `meson.build` file declares needing meson >= 0.40.0; is there any chance you can try it with that or any later version?

**Comment by r2rX** [comment]
Thanks for the tip, @Hjdskes . After installing meson 0.41, it compiled successfully.

```
xxxxx@xxxxx:~/Desktop/piper$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.41.0
Source dir: /home/xxxxx/Desktop/piper
Build dir: /home/xxxxx/Desktop/piper/builddir
Build type: native build
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency python3 found: YES 3.5
Native dependency pygobject-3.0 found: YES 3.22.0
Configuring AboutDialog.ui using configuration
Native dependency glib-2.0 found: YES 2.52.0
Message: Getting Python3 install dir
Configuring piper using configuration
Configuring piper.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/xxxxx/Desktop/piper/meson_install.sh)
Build targets in project: 1
```

**Comment by Hjdskes** [comment]
Cheers, I'm closing this issue then. If there are other problems feel free to open a new one.

**Comment by oliv3r** [comment]
Debian stretch (just released) still ships with meson Version: 0.37.1. Would it not be wise to support at least that older version as well?

**Comment by bentiss** [comment]
> Debian stretch (just released) still ships with meson Version: 0.37.1. Would it not be wise to support at least that older version as well?

Long story short: `meson` is just a git clone away (it's a python script after all).

So users can just clone libratbag, clone meson, and run `./meson/meson.py build`.

Supporting such an old version of meson is going to be a pain given that we need fixes in later versions to have the build working properly.

**Comment by oliv3r** [comment]
Well i guess the point being is, that some people may not want to "polute" their system with lots of 'clones of everything' :) I prefer to get my packages from the package manager, but was curious about piper.
I'll try to run just the source without installing it and if that also fails, just wait until it is properly packaged upstream :)

thanks though

p.s. how can a 'simple' (no offense intended) python application require an entire build system with that many potential problems anyway?

**Comment by bentiss** [comment]
Yep, you can just clone and not install meson. As long as you have ninja, you are fine.

> p.s. how can a 'simple' (no offense intended) python application require an entire build system with that many potential problems anyway?

Given that to run piper, you need the upstream libratbag project which is less than trivial, having piper depending on the same version of meson than libratbag is not such an issue.

Keep in mind that piper is just the UI (a fancy one even). Most of the low level work is done in libratbag.

**Comment by oliv3r** [comment]
thanks @bentiss 👍
