### ISSUE TITLE
GTK fault when trying to run piper

### ISSUE THREAD

**Issue by MeFisto94** [libratbag/piper#111]
Hey Guys,
Running piper like this leads to a crash. I am uncertain whether this is related to the GLIB Issue mentioned during complication, though?

```
PYTHONPATH=$PYTHONPATH:/usr/lib/python3.5/site-packages piper

(piper:20504): Gtk-CRITICAL **: Error building template class 'MousePerspective' for an instance of type 'MousePerspective': .:3:4828 Invalid property: GtkScrolledWindow.ropagate_natural_width
Traceback (most recent call last):
  File "/home/x/Dokumente/02_GIT/piper/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/home/x/Dokumente/02_GIT/piper/piper/window.py", line 48, in __init__
    perspectives = [ErrorPerspective(), MousePerspective(), WelcomePerspective()]
  File "/home/x/Dokumente/02_GIT/piper/piper/mouseperspective.py", line 48, in __init__
    self.init_template()
  File "/home/x/Dokumente/02_GIT/piper/piper/gi_composites.py", line 101, in <lambda>
    cls.init_template = lambda s: _init_template(s, cls, base_init_template)
  File "/home/x/Dokumente/02_GIT/piper/piper/gi_composites.py", line 131, in _init_template
    ', '.join(self.__gtemplate_widgets__))
AttributeError: A missing child widget was set using GtkTemplate.Child and the entire template is now broken (widgets: stack, button_commit, _titlebar, notification_commi, listbox_profiles, add_profile_button, label_profile
```
Any ideas on how to progress further?

**Comment by Hjdskes** [comment]
`Invalid property: GtkScrolledWindow.ropagate_natural_width` ... interesting. That almost implies a typo (`ropagate` versus `propagate`), but this file isn't manually edited at all, plus it works for me on the current master.

> Any ideas on how to progress further?

Are you sure that your working directory is clean? Run `git diff` which shouldn't output anything. If it is, does running `./build/piper.devel` from your working directory result in the same error?

What distribution are you on and which Python, Gtk and PyGobject versions do you have?

**Comment by MeFisto94** [comment]
It also says propagate actually... Not sure how that could be lost during copy and paste actually, I am sorry.
git diff shows no changes, git status only shows changes for builddir/ (obviously).

Running piper.devel yields:
```
$ PYTHONPATH=$PYTHONPATH:/usr/lib/python3.5/site-packages ./builddir/piper.devel 
Running from source tree, using local files

(piper.devel:15958): Gtk-CRITICAL **: Error building template class 'MousePerspective' for an instance of type 'MousePerspective': .:3:4828 Invalid property: GtkScrolledWindow.propagate_natural_width
Traceback (most recent call last):
  File "/home/x/Dokumente/02_GIT/piper/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/home/x/Dokumente/02_GIT/piper/piper/window.py", line 48, in __init__
    perspectives = [ErrorPerspective(), MousePerspective(), WelcomePerspective()]
  File "/home/x/Dokumente/02_GIT/piper/piper/mouseperspective.py", line 48, in __init__
    self.init_template()
  File "/home/x/Dokumente/02_GIT/piper/piper/gi_composites.py", line 101, in <lambda>
    cls.init_template = lambda s: _init_template(s, cls, base_init_template)
  File "/home/x/Dokumente/02_GIT/piper/piper/gi_composites.py", line 131, in _init_template
    ', '.join(self.__gtemplate_widgets__))
AttributeError: A missing child widget was set using GtkTemplate.Child and the entire template is now broken (widgets: listbox_profiles, label_profile, _titlebar, add_profile_button, stack, button_commit, notification_commit)
```
$ python -V
Python 2.7.12+
$ python3 -V
Python 3.5.2+
$ gtk-launch --version
3.20.9
$ pip3 list
evdev (0.4.7)
lxml (3.6.4)
meson (0.41.2)
pexpect (4.2.0)
Pillow (3.3.1)
pip (9.0.1)
ptyprocess (0.5.1)
pycups (1.9.73)
pygobject (3.22.0)
PyYAML (3.11)
reportlab (3.3.0)
requests (2.10.0)
screen-resolution-extra (0.0.0)
setuptools (26.1.1)
six (1.10.0)
systemd-python (232)
ufw (0.35)
xkit (0.0.0)
```

I am uncertain whether that GTK Version is right and I removed a few definately unrelated wheels (like urllib) from that list.

I am running Kubuntu 16.10 on 4.8.0-59-generic

**Comment by Hjdskes** [comment]
>```
>$ gtk-launch --version
>3.20.9
>```

Your version of Gtk+ is too old; [`propagate-natural-width`](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GtkScrolledWindow--propagate-natural-width) was added in 3.22.

One of these days I need to go through the code to see what is the oldest version we can (easily) support, but for now I'm going to say you need to upgrade to 3.22. Sorry.

@whot any input from your end on this?

**Comment by MeFisto94** [comment]
Mhh, seems like its time to upgrade my distro soon, even though its less than a year old^^
Unfortunately I also had problems with meson, I had to take the newer version from Pip.

Anyway I managed to semi-upgrade my GTK version and now piper at least launches.
I now have
```
piper/mousemap.py", line 111, in __init__
    raise ValueError("Device has no image or its path is invalid")
```
Since I manually added a new mouse to libratbag. Is there a guide on how to make piper work with that?

**Comment by Hjdskes** [comment]
> Since I manually added a new mouse to libratbag.

I'm not sure what you mean with this.

> Is there a guide on how to make piper work with that?

Piper is only a GUI to libratbag. For device support, please open an issue there. Since you solved the one here, I'm closing this one.
