### ISSUE TITLE
Timeout when applying profiles to G502

### ISSUE THREAD

**Issue by cvuchener** [libratbag/piper#119]
piper crashes when clicking "apply":

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/piper/ratbagd.py", line 195, in _dbus_call
    500, None)
GLib.Error: g-io-error-quark: Timeout was reached (24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/piper/mouseperspective.py", line 128, in _on_save_button_clicked
    status = self._device.commit()
  File "/usr/local/lib/python3.6/site-packages/piper/ratbagd.py", line 339, in commit
    ret = self._dbus_call("Commit", "")
  File "/usr/local/lib/python3.6/site-packages/piper/ratbagd.py", line 202, in _dbus_call
    raise RatbagdDBusTimeout(e.message)
piper.ratbagd.RatbagdDBusTimeout: Timeout was reached
```

It looks like ratbagd is being too slow for piper but the new profiles are actually committed.

**Comment by Hjdskes** [comment]
This has been occurring for me as well every now and then; it seems that it usually performs fast enough and just sometimes something happens. I can however reproduce this reliably when I change something quickly after changing profiles, so definitely something I should fix. Just haven't gotten around to it yet :)

**Comment by Hjdskes** [comment]
Just to follow up: did this happen after you changed something immediately following a profile change, or does this happen consistently for you?

**Comment by cvuchener** [comment]
I can reproduce consistently with the following steps:
 - start piper
 - open the G502
 - go to button tab
 - change a button
 - click apply

If the "500" I see in the stacktrace is the timeout is millisecond, I think it is too short. It takes more than one second to write the profiles. Wireless devices may be even slower.

```
$ time ./ratbag-command profile 0 button 4 action set button 7 /dev/input/event2
ratbag error: unknown tag: 0x02

real	0m1,281s
user	0m0,006s
sys	0m0,015s
```

```
$ time ./src/tools/hidpp-persistent-profiles /dev/hidraw1 write g502_20170815.xml 

real	0m1,378s
user	0m0,020s
sys	0m0,005s
```

**Comment by Hjdskes** [comment]
> If the "500" I see in the stacktrace is the timeout is millisecond, I think it is too short.

500 is indeed the timeout in milliseconds; it's been like this since forever but I do recall discussing this with @whot. We'll definitely need to increase the timeout, but 

1. I do not know what happens when a user changes settings while the property is being changed (so we should strive to make it as small as possible?), and
2. I don't know what value will be long enough not to cause timeouts. This depends both on the device (incl. whether it's wireless or not, for example my G403 can be both) and the box running Piper.

**Comment by whot** [comment]
We can increase the timeout, but it's just moving the problem. As immediate fix it'll be fine, but realistically, we need to add async commit to libratbag: https://github.com/libratbag/libratbag/issues/269

The answer to question 1 is going to be a lot more complicated, unfortunately...
