### ISSUE TITLE
Piper contributes to global warming

### ISSUE THREAD

**Issue by whot** [libratbag/piper#133]
There, now I have your attention with that clickbait title, right? :)

When the Piper window is on the buttons mapping page and partially or fully obscured, I get 100% CPU usage from piper. Most of which is taken up by X but python3 takes about 11%.  Bit of print-debugging shows that `MouseMap.do_draw` is called continuously.

**Comment by Hjdskes** [comment]
Thanks! I had been seeing this while developing the MouseMap and then I couldn't reproduce it anymore since -- I thought it had magically fixed itself.
