### ISSUE TITLE
Resolutions DPI labels need initial update

### ISSUE THREAD

**Issue by PlasmaPower** [libratbag/piper#134]
When visiting the resolutions tab, the DPI labels need an initial update, though the sliders are in the correct position.

![screenshot](https://user-images.githubusercontent.com/6006498/29401210-8c16142c-82ed-11e7-9738-5d8f571497a1.png)

Moving the sliders fixes the label.

`ratbagctl info event4` works fine, as expected:

```
    0: 450dpi @ 500Hz
    1: 800dpi @ 500Hz
    2: 1600dpi @ 500Hz (active) (default)
    3: 2400dpi @ 500Hz
    4: <disabled>
```

**Comment by Hjdskes** [comment]
Yep, this is fixed in #132 :)

**Comment by Hjdskes** [comment]
Now committed directly to master in 191cbf6d36bbf50d4dc017db50e93bf1b7447179.

**Comment by PlasmaPower** [comment]
Yep, that fixed it. Thanks!
