### ISSUE TITLE
Piper shouldn't crash when libratbag returns 1001

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#140]
Traceback:

```
GDBus.Error:org.freedesktop.DBus.Error.Failed: Unknown error 1001
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gi/_propertyhelper.py", line 427, in obj_set_property
    prop.fset(self, value)
  File "/home/jente/code/src/github.com/libratbag/piper/piper/ratbagd.py", line 674, in macro
    ret = self._dbus_call("SetMacro", "a(uu)", macro)
  File "/home/jente/code/src/github.com/libratbag/piper/piper/ratbagd.py", line 195, in _dbus_call
    2000, None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Unknown error 1001 (0)
```

**Comment by Hjdskes** [comment]
This is part of a larger problem: none of the exceptions raised from `_dbus_call` in any of the bindings are caught. Furthermore, we cannot leave this up to the callers because the `GObject.Property` decorator doesn't raise exceptions, as we've seen before in 1da54f7d6f6fc2e5bd9a34cc2365de1e897b5b9a.

This means that we need to fix this *in the bindings* and cannot leave it up to the caller. To further complicate this issue: we cannot return values from property setters either (I will at least fix this in a start of fixing the bindings), so all we can do is set some sensible value upon error, or simply do nothing at all.

@whot What do you think we should do here?

**Comment by whot** [comment]
we need to be able to communicate errors somehow. so either we go back to non-property based dbus bindings or have some other state on the class that signals something failed. not sure how we'd use that from the caller though.

**Comment by Hjdskes** [comment]
> we need to be able to communicate errors somehow.

Oke I lied a bit: only the calls to `_dbus_call` from within property setters cannot raise exceptions. If we can thus do away with these setters having to use both `_dbus_call` and `_set_dbus_property` (i.e. doing this transparently within ratbagd) we also solve the problem. There are only four (three if we don't count key mappings which will be dropped anyway) such setters, all of which are in `RatbagdButton`. If we remove those and make their properties writable, it all works and this issue is resolved. See https://github.com/libratbag/libratbag/pull/290 and #148.
