### ISSUE TITLE
Pressing Escape does not restore the printed macro

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#141]
In the ButtonDialog, when capturing a macro on a button that doesn't currently have a macro set and pressing Escape, the label is not restored back to "None" but instead is empty.

I'm currently not sure if the label is restored correctly when a macro is already set.

**Comment by Hjdskes** [comment]
This is now fixed in #136.

**Comment by whot** [comment]
fixed with 1dba057ba3116669fd854e2e7baa16d65fc55f2a
