### ISSUE TITLE
Track down the initialization that can cause a dirty profile

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#151]
Sometimes when I start Piper the profile is dirty; this may be caused by the initialization of a widget somewhere.

**Comment by Hjdskes** [comment]
Of course it doesn't occur anymore now that I'm trying to figure out what causes it... starting to think that it may just have been a dirty ratbag from an earlier Piper execution.

**Comment by whot** [comment]
I've had this a few times, usually when piper crashed on my roccat when commit failed. it was always a case of dirty ratbagd. I'd say we close this one until you figure out the reason.
