### ISSUE TITLE
Can't change ANY setting for G403.

### ISSUE THREAD

**Issue by joaogma** [libratbag/piper#164]
Hi! This is what I've been always looking for, an easy way to configure my Logitech G403, thank you for your work.
I have an issue though. Can't change any setting on my mouse, it remains unchanged no matter the settings I have in Piper.

This is what happens in terminal:
`$ piper`
`Traceback (most recent call last):`
  `File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 132, in _on_save_button_clicked
    self._device.commit(self._commit_cb)`
`AttributeError: 'MousePerspective' object has no attribute '_commit_cb'
`

**Comment by Hjdskes** [comment]
Thanks, I made a mistake in the previous commit. It should be fixed now.
