### ISSUE TITLE
Issues installing on Fedora

### ISSUE THREAD

**Issue by Adobe-Android** [libratbag/piper#165]
From Meson:
Dependency python3 found: NO
From package manager:
Package python3-3.5.3-6.fc25.x86_64 is already installed
From Meson:
Native dependency 'pygobject-3.0' not found
From package manager:
Package python-gobject-3.22.0-1.fc25.x86_64 is already installed

**Comment by whot** [comment]
you need the respective -devel packages installed

**Comment by Adobe-Android** [comment]
Still having issues with the following. I'm still looking for a solution.
Native dependency 'pygobject-3.0' not found

**Comment by Adobe-Android** [comment]
Nevermind. I just found it. It was pygobject3-devel

**Comment by whot** [comment]
99% of the time `dnf install "pkgconfig(pygobject-3.0)"` gets you there, replaced with whatever the dependency is (refers to a pkgconfig .pc file, usually)
