### ISSUE TITLE
'Close' button in infobox not working

### ISSUE THREAD

**Issue by kaymio** [libratbag/piper#174]
The infobox, opened via the symbol in the top left corner of piper, can only be closed with the X in the top right corner. The 'Close' button in the infobox doesn't work.

**Comment by Hjdskes** [comment]
Can you please clarify what you mean with infobox and symbol in the top left corner? As ot reads now I'm assuming you're not using GNOME Shell, hence the symbol being the application icon and the infobox being the about dialog. Is that correct?

**Comment by kaymio** [comment]
![piperwhole](https://user-images.githubusercontent.com/22966929/30476427-4d692ca8-9a0a-11e7-8502-f1f70b944e0a.png)
![piperabout](https://user-images.githubusercontent.com/22966929/30476434-5251a07e-9a0a-11e7-8e9a-3456a4e0dc1c.png)
![infobox](https://user-images.githubusercontent.com/22966929/30476440-56d841b6-9a0a-11e7-8186-f49c26a9b81c.png)

**Comment by Hjdskes** [comment]
Cinnamon is different from GNOME Shell; it's not "a" shell. GNOME Shell is the only GNOME Shell.

Anyway, seems my assumption holds. I'll look into it.

**Comment by whot** [comment]
@kaymio  can you give the above commit a try please? thanks

**Comment by kaymio** [comment]
Sorry, I've been on vacation. 

I've just recompiled and reinstalled libratbag and piper without a hickup. After a restart of ratbagd and starting piper I get:

piper
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 88, in set_device
    self.stack.add_titled(ButtonsPage(device), "buttons", _("Buttons"))
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 50, in __init__
    self._set_profile(self._device.active_profile)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 58, in _set_profile
    self._on_ratbagd_button_action_type_changed(ratbagd_button, None, button)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 86, in _on_ratbagd_button_action_type_changed
    label = _(RatbagdButton.SPECIAL_DESCRIPTION[ratbagd_button.special])
KeyError: 4294967295

I'm not sure where to post this bug.

**Comment by Hjdskes** [comment]
@kaymio this shouldn't occur anymore on the latest master of both piper and libratbag. Are you sure you are using the latest master branches of both?

**Comment by kaymio** [comment]
@Hjdskes @whot 

Here is the whole process of uninstalling, redownloading, recompiling, installing and start of the programmes:

cd build

~/build
▶ cd piper

~/build/piper  master ✗                                                                                         2d ◒
▶ sudo ninja -C builddir uninstall
[sudo] Passwort für nackt:
ninja: Entering directory `builddir'
[0/1] /usr/bin/python /usr/bin/meson --internal uninstall
Deleted: /usr/lib/python3.6/site-packages/piper/resolutionspage.py
Deleted: /usr/lib/python3.6/site-packages/piper/__init__.py
Deleted: /usr/lib/python3.6/site-packages/piper/resolutionrow.py
Deleted: /usr/lib/python3.6/site-packages/piper/window.py
Deleted: /usr/lib/python3.6/site-packages/piper/ledspage.py
Deleted: /usr/lib/python3.6/site-packages/piper/welcomeperspective.py
Deleted: /usr/lib/python3.6/site-packages/piper/ratbagd.py
Deleted: /usr/lib/python3.6/site-packages/piper/profilerow.py
Deleted: /usr/lib/python3.6/site-packages/piper/devicerow.py
Deleted: /usr/lib/python3.6/site-packages/piper/buttonspage.py
Deleted: /usr/lib/python3.6/site-packages/piper/mouseperspective.py
Deleted: /usr/lib/python3.6/site-packages/piper/application.py
Deleted: /usr/lib/python3.6/site-packages/piper/mousemap.py
Deleted: /usr/lib/python3.6/site-packages/piper/gi_composites.py
Deleted: /usr/lib/python3.6/site-packages/piper/optionbutton.py
Deleted: /usr/lib/python3.6/site-packages/piper/buttondialog.py
Deleted: /usr/lib/python3.6/site-packages/piper/errorperspective.py
Deleted: /usr/lib/python3.6/site-packages/piper/leddialog.py
Deleted: /usr/share/piper/piper.gresource
Deleted: /usr/share/applications/org.freedesktop.Piper.desktop
Deleted: /usr/share/icons/hicolor/scalable/apps/org.freedesktop.Piper.svg
Deleted: /usr/bin/piper

Uninstall finished.

Deleted: 22
Failed: 0

Remember that files created by custom scripts have not been removed.

~/build/piper  master ✗                                                                                         2d ◒
▶ cd..

~/build
▶ cd libratbag

~/build/libratbag  master ✗                                                                                     2d ◒
▶ sudo ninja -C builddir uninstall
ninja: Entering directory `builddir'
[0/1] /usr/bin/python /usr/bin/meson --internal uninstall
Deleted: /usr/lib/liblur.so.3.0.3
Deleted: /usr/lib/liblur.so.3
Deleted: /usr/lib/liblur.so
Deleted: /usr/bin/lur-command
Deleted: /usr/bin/ratbagd
Deleted: /usr/bin/ratbagctl
Deleted: /usr/include/liblur.h
Deleted: /usr/share/man/man8/ratbagd.8.gz
Deleted: /usr/lib/pkgconfig/liblur.pc
Deleted: /usr/share/man/man1/lur-command.1
Deleted: /usr/share/libratbag/etekcity-fixme.device
Deleted: /usr/share/libratbag/gskill-MX-780.device
Deleted: /usr/share/libratbag/logitech-g300.device
Deleted: /usr/share/libratbag/logitech-g303.device
Deleted: /usr/share/libratbag/logitech-g403.device
Deleted: /usr/share/libratbag/logitech-g500.device
Deleted: /usr/share/libratbag/logitech-g500s.device
Deleted: /usr/share/libratbag/logitech-g502-Proteus-Core-over-USB.device
Deleted: /usr/share/libratbag/logitech-g502-Proteus-Spectrum-over-USB.device
Deleted: /usr/share/libratbag/logitech-g5-2007.device
Deleted: /usr/share/libratbag/logitech-g5.device
Deleted: /usr/share/libratbag/logitech-g602.device
Deleted: /usr/share/libratbag/logitech-g700.device
Deleted: /usr/share/libratbag/logitech-g700s.device
Deleted: /usr/share/libratbag/logitech-g700s-wireless.device
Deleted: /usr/share/libratbag/logitech-g700-wireless.device
Deleted: /usr/share/libratbag/logitech-g703.device
Deleted: /usr/share/libratbag/logitech-g7.device
Deleted: /usr/share/libratbag/logitech-g900.device
Deleted: /usr/share/libratbag/logitech-g900-wireless.device
Deleted: /usr/share/libratbag/logitech-g9.device
Deleted: /usr/share/libratbag/logitech-g9x-[Call-of-Duty-MW3-Edition].device
Deleted: /usr/share/libratbag/logitech-g9x-[Original].device
Deleted: /usr/share/libratbag/logitech-M325.device
Deleted: /usr/share/libratbag/logitech-M570.device
Deleted: /usr/share/libratbag/logitech-M705.device
Deleted: /usr/share/libratbag/logitech-MX-Master.device
Deleted: /usr/share/libratbag/logitech-T650.device
Deleted: /usr/share/libratbag/logitech-Wireless-Touchpad.device
Deleted: /usr/share/libratbag/roccat-kone-xtd.device
Deleted: /usr/share/libratbag/steelseries-rival-310.device
Deleted: /usr/share/libratbag/gnome/fallback.svg
Deleted: /usr/share/libratbag/gnome/logitech-g300.svg
Deleted: /usr/share/libratbag/gnome/logitech-g303.svg
Deleted: /usr/share/libratbag/gnome/logitech-g403.svg
Deleted: /usr/share/libratbag/gnome/logitech-g500.svg
Deleted: /usr/share/libratbag/gnome/logitech-g500s.svg
Deleted: /usr/share/libratbag/gnome/logitech-g502.svg
Deleted: /usr/share/libratbag/gnome/logitech-g700.svg
Deleted: /usr/share/libratbag/gnome/logitech-g703.svg
Deleted: /usr/share/libratbag/gnome/logitech-g9.svg
Deleted: /usr/share/libratbag/gnome/logitech-g900.svg
Deleted: /usr/share/libratbag/gnome/roccat-kone-xtd.svg
Deleted: /usr/share/libratbag/gnome/steelseries-rival310.svg
Deleted: /usr/lib/systemd/system/ratbagd.service
Deleted: /usr/share/dbus-1/system-services/org.freedesktop.ratbag1.service
Deleted: /usr/share/dbus-1/system.d/org.freedesktop.ratbag1.conf
Deleted: /usr/share/man/man1/ratbagctl.1

Uninstall finished.

Deleted: 58
Failed: 0

Remember that files created by custom scripts have not been removed.

~/build/libratbag  master ✗                                                                                     2d ◒
▶ cd..

~/build
▶ rm -rf libratbag

~/build
▶ rm -rf piper

~/build
▶ git clone https://github.com/libratbag/libratbag.git
Klone nach 'libratbag' ...
remote: Counting objects: 7133, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 7133 (delta 55), reused 82 (delta 37), pack-reused 7013
Empfange Objekte: 100% (7133/7133), 2.23 MiB | 2.90 MiB/s, Fertig.
Löse Unterschiede auf: 100% (5265/5265), Fertig.

~/build
▶ cd libratbag

~/build/libratbag  master ✔                                                                                       2d
▶ LANG=C meson builddir --prefix=/usr/
The Meson build system
Version: 0.43.0
Source dir: /home/nackt/build/libratbag
Build dir: /home/nackt/build/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.2.0)
Native C++ compiler: c++ (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency libudev found: YES 235
Native dependency libevdev found: YES 1.5.7
Native dependency libsystemd found: YES 235
Native dependency systemd found: YES 235
Native dependency glib-2.0 found: YES 2.54.0
Library m found: YES
Configuring libratbag-version.h using configuration
Configuring lur-command.1 using configuration
Program /home/nackt/build/libratbag/data/devices/data-parse-test.py found: YES (/home/nackt/build/libratbag/data/device
s/data-parse-test.py)
Program data/gnome/check-svg.py found: YES (/home/nackt/build/libratbag/data/gnome/check-svg.py)
Native dependency check found: YES 0.11.0
Program valgrind found: YES (/usr/bin/valgrind)
Configuring org.freedesktop.ratbag_devel1.conf using configuration
Message:
                systemd unitdir libdir mismatch detected, changing unitdir to
                        /usr/lib/systemd/system
                or specify with
                        mesonconf -Dsystemd-unit-dir=<path>

                See https://github.com/libratbag/libratbag/issues/188

Configuring ratbagd.service using configuration
Configuring org.freedesktop.ratbag1.service using configuration
Configuring ratbagctl.1 using configuration
Configuring ratbagctl.devel using configuration
Configuring ratbagctl.test using configuration
Program /home/nackt/build/libratbag/builddir/ratbagctl.test found: YES (/home/nackt/build/libratbag/builddir/ratbagctl.
test)
Configuring toolbox.py using configuration
Configuring config.h using configuration
Program swig found: YES (/usr/bin/swig)
Native dependency python3 found: YES 3.6
Build targets in project: 22
Found ninja-1.8.2 at /usr/bin/ninja

~/build/libratbag  master ✗                                                                                     2d ◒
▶ LANG=C ninja -C builddir
ninja: Entering directory `builddir'
[73/73] Linking target _libratbag.so.

~/build/libratbag  master ✗                                                                                     2d ◒
▶ sudo ninja -C builddir install
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing liblur.so.3.0.3 to /usr/lib/liblur.so.3.0.3
Installing lur-command to /usr/bin/lur-command
Installing ratbagd to /usr/bin/ratbagd
Installing ratbagctl to /usr/bin/ratbagctl
Installing liblur.h to /usr/include/
Installing /home/nackt/build/libratbag/ratbagd/ratbagd.8 to /usr/share/man/man8
Installing /home/nackt/build/libratbag/builddir/meson-private/liblur.pc to /usr/lib/pkgconfig
Installing /home/nackt/build/libratbag/builddir/lur-command.1 to /usr/share/man/man1
Installing /home/nackt/build/libratbag/data/devices/etekcity-fixme.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/gskill-MX-780.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g300.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g303.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g403.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g500.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g500s.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g502-Proteus-Core-over-USB.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g502-Proteus-Spectrum-over-USB.device to /usr/share/librat
bag
Installing /home/nackt/build/libratbag/data/devices/logitech-g5-2007.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g5.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g602.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g700.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g700s.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g700s-wireless.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g700-wireless.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g703.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g7.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g900.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g900-wireless.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g9.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-g9x-[Call-of-Duty-MW3-Edition].device to /usr/share/librat
bag
Installing /home/nackt/build/libratbag/data/devices/logitech-g9x-[Original].device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-M325.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-M570.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-M705.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-MX-Master.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-T650.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/logitech-Wireless-Touchpad.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/roccat-kone-xtd.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/devices/steelseries-rival-310.device to /usr/share/libratbag
Installing /home/nackt/build/libratbag/data/gnome/fallback.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g300.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g303.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g403.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g500.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g500s.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g502.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g700.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g703.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g9.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/logitech-g900.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/roccat-kone-xtd.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/data/gnome/steelseries-rival310.svg to /usr/share/libratbag/gnome
Installing /home/nackt/build/libratbag/builddir/ratbagd.service to /usr/lib/systemd/system
Installing /home/nackt/build/libratbag/builddir/org.freedesktop.ratbag1.service to /usr/share/dbus-1/system-services
Installing /home/nackt/build/libratbag/dbus/org.freedesktop.ratbag1.conf to /usr/share/dbus-1/system.d
Installing /home/nackt/build/libratbag/builddir/ratbagctl.1 to /usr/share/man/man1

~/build/libratbag  master ✗                                                                                     2d ◒
▶ cd..

~/build
▶ stop ratbagd

~/build
▶ git clone https://github.com/libratbag/piper.git
Klone nach 'piper' ...
remote: Counting objects: 1442, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 1442 (delta 18), reused 27 (delta 8), pack-reused 1397
Empfange Objekte: 100% (1442/1442), 1.91 MiB | 3.07 MiB/s, Fertig.
Löse Unterschiede auf: 100% (973/973), Fertig.

~/build
▶ cd piper

~/build/piper  master ✔                                                                                           9d
▶ meson builddir --prefix=/usr/
The Meson build system
Version: 0.43.0
Source dir: /home/nackt/build/piper
Build dir: /home/nackt/build/piper/builddir
Build type: native build
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency python3 found: YES 3.6
Native dependency pygobject-3.0 found: YES 3.26.0
Configuring AboutDialog.ui using configuration
Native dependency glib-2.0 found: YES 2.54.0
Message: Getting Python3 install dir
Configuring piper using configuration
Configuring piper.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/nackt/build/piper/meson_install.sh)
Build targets in project: 4
Found ninja-1.8.2 at /usr/bin/ninja

~/build/piper  master ✗                                                                                         9d ◒
▶ ninja -C builddir
ninja: Entering directory `builddir'
[1/1] Generating piper_gresource with a custom command.

~/build/piper  master ✗                                                                                         9d ◒
▶ sudo ninja -C builddir install
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing subdir /home/nackt/build/piper/piper to /usr/lib/python3.6/site-packages
Installing data/piper.gresource to /usr/share/piper/piper.gresource
Installing /home/nackt/build/piper/data/org.freedesktop.Piper.desktop to /usr/share/applications
Installing /home/nackt/build/piper/data/org.freedesktop.Piper.svg to /usr/share/icons/hicolor/scalable/apps
Installing /home/nackt/build/piper/builddir/piper to /usr/bin
Running custom install script '/usr/bin/python /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=piper'
Installing /home/nackt/build/piper/builddir/po/de.gmo to /usr/share/locale/de/LC_MESSAGES/piper.mo
Installing /home/nackt/build/piper/builddir/po/hr.gmo to /usr/share/locale/hr/LC_MESSAGES/piper.mo
Installing /home/nackt/build/piper/builddir/po/nl.gmo to /usr/share/locale/nl/LC_MESSAGES/piper.mo
Installing /home/nackt/build/piper/builddir/po/pl.gmo to /usr/share/locale/pl/LC_MESSAGES/piper.mo
Installing /home/nackt/build/piper/builddir/po/sv.gmo to /usr/share/locale/sv/LC_MESSAGES/piper.mo
Running custom install script '/usr/bin/env sh /home/nackt/build/piper/meson_install.sh'
gtk-update-icon-cache: Cache file created successfully.

~/build/piper  master ✗                                                                                         9d ◒
▶ piper
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 88, in set_device
    self.stack.add_titled(ButtonsPage(device), "buttons", _("Buttons"))
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 50, in __init__
    self._set_profile(self._device.active_profile)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 58, in _set_profile
    self._on_ratbagd_button_action_type_changed(ratbagd_button, None, button)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 86, in _on_ratbagd_button_action_type_changed
    label = _(RatbagdButton.SPECIAL_DESCRIPTION[ratbagd_button.special])
KeyError: 4294967295

~/build/piper  master ✗                                                                                         9d ◒
▶ start ratbagd

~/build/piper  master ✗                                                                                         9d ◒
▶ piper
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 88, in set_device
    self.stack.add_titled(ButtonsPage(device), "buttons", _("Buttons"))
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 50, in __init__
    self._set_profile(self._device.active_profile)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 58, in _set_profile
    self._on_ratbagd_button_action_type_changed(ratbagd_button, None, button)
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 86, in _on_ratbagd_button_action_type_changed
    label = _(RatbagdButton.SPECIAL_DESCRIPTION[ratbagd_button.special])
KeyError: 4294967295

**Comment by kaymio** [comment]
@Hjdskes, @whot 

I'd gladly hear about what I did wrong. Should I take another approach?

**Comment by whot** [comment]
@kaymio please don't paste install logs into comments, having to scroll past pages of logs makes it impossible to get a good grasp on a bug. Always attach log files.

Anyway, the key error is an unrelated bug to this one, until it's fixed we won't be able to continue with the close button issue, at least not with your device. What you can do though is test with the test device so we can at least check the bit about the close button. Unplug your mouse, run `sudo ./builddir/ratbagctl.devel --keepalive list`, that should list a `test_device` and also print an `export RATBAGCTL_DEVEL...` environment variable. Export that, then run `./builddir/piper.devel` in the shell where that environment variable is set. This makes the test device available to piper which shouldn't trigger the above error. You can now go and click on the about dialog to check if the patch above works.

**NOTE:** you'll need to check out the `wip/dialog-close-harder` branch from my repo, not just piper master.

**Comment by Hjdskes** [comment]
I took the liberty to edit @kaymio's messages to hide the logs, now that this bug seems to be active again due to #221.
