### ISSUE TITLE
Piper crashes trying to bind a macro to a button

### ISSUE THREAD

**Issue by joonatoona** [libratbag/piper#176]
```
Ubuntu 17.04
Piper from git at commit 4f560b0d1e13383a075dfe94de106942a2028860
libratbag from git at commit 52e10d029f7cc7573f55b63dc435e706c021d72d
Logitech G502 Proteus Spectrum
```

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 427, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3.5/site-packages/piper/ratbagd.py", line 753, in macro
    self._set_dbus_property("Macro", "a(uu)", macro.keys)
  File "/usr/lib/python3.5/site-packages/piper/ratbagd.py", line 183, in _set_dbus_property
    2000, None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Unknown error 1001 (0)
```

**Comment by bentiss** [comment]
Just a FYI, there are 2 issues here:
- one is already fixed normally, you shouldn't receive a 1001 error anymore if you are running master
- the second is that currently the Logitech devices can't assign a macro (I know, it's a pain). It's a feature for 1.0 and I meant to work on it, but I have other priorities for the next couple of weeks :( (see https://github.com/libratbag/libratbag/issues/271)

**Comment by joonatoona** [comment]
```
G:\master\dirty\home\joonatoona\src\piper>git branch
* master
```

Is there anything I can do to help?

**Comment by bentiss** [comment]
Are you also running libratbag/ratbagd master? Because the fix is there. Sorry I should have been more explicit

**Comment by joonatoona** [comment]
```
G:\master\dirty\home\joonatoona\src\libratbag>git branch
* master
```

**Comment by Hjdskes** [comment]
You're on the branch master but this does not mean your local branch is up to date with the remote branch. Please make sure you are by running `git pull`

**Comment by joonatoona** [comment]
I cloned it 5 minutes ago. I also included the commit hash in the issue, which is indeed the latest commit on master.

**Comment by bentiss** [comment]
@Hjdskes see https://github.com/libratbag/libratbag/blob/master/ratbagd/ratbagd-button.c#L246 and https://github.com/libratbag/libratbag/blob/master/ratbagd/ratbagd-button.c#L257, both should not return r but 0 and send a resync before leaving.

**Comment by Hjdskes** [comment]
> I also included the commit hash in the issue, which is indeed the latest commit on master.

Sorry, I missed that.

I opened https://github.com/libratbag/libratbag/pull/351 to fix the return values.
