### ISSUE TITLE
How to process Resync?

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#182]
Since a while now ratbagd emits the `Resync` signal to indicate to clients that they should, well, resync. This isn't yet implemented in ratbagd.py, which I would like to do. Basically, there are two ways to go about this:

1. Receive the signal in `RatbagdDevice` and emit a GObject signal `resync` so that all users of the device are notified, or
2. Receive the signal in `RatbagdDevice` and implicitly resync everything from within the device, without letting the client know (a well-programmed client should respond automatically to changes made "behind its back"; Piper does).

I think I prefer the second approach because it hides all the logic within the bindings, but I haven't investigated its feasibility. I'm interested in hearing your thoughts.

CC'ing @bentiss @whot, feel free to CC more.

**Comment by whot** [comment]
Definitely 2, that's what we have all the gobject magic for. No need to implement our own.

**Comment by whot** [comment]
was staring at this a bit today.  I think that the 'resync' signal itself doesn't need to be handled by piper other than maybe show an error message. But ratbag should sync itself and update all properties before (after??) it sends the signal. The signal itself doesn't carry any information anyway, so it's just a notification that things are different to what they were before.
