### ISSUE TITLE
Invalid SVG error for G403

### ISSUE THREAD

**Issue by Freggar** [libratbag/piper#201]
Hi! I'm currently trying to configure my G403 but am greeted by the mouse trap "Cannot display device SVG, Device has no image or its path is invalid". But it doesn't seem like a ratbagd error since I get following output when running `ratbagd --verbose`
```
ratbag debug: Logitech G403 Prodigy Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech G403 Prodigy Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: 'Logitech G403 Prodigy Gaming Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 800 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has color effects
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: driver match found: Logitech HID++2.0
event9: "Logitech G403 Prodigy Gaming Mouse", 1 profiles
ratbagd error: Unable to fetch SVG for event9
ratbagd error: Unable to fetch SVG for event9
```
Note that the last two errors `Unable to fetch SVG for event9` occur when starting piper. 

Additional Info (If something is missing please ask)
Distro: **ArchLinux**
WM: **i3**
Hardware: **Dell XPS15 9560**
Piper Package: https://aur.archlinux.org/packages/piper/
Libratbagd Package: https://aur.archlinux.org/packages/libratbag/

**Comment by Hjdskes** [comment]
This is a libratbag issue, not Piper, but I think your libratbag release (which is indeed the latest) is too old (@whot perhaps time to cut a new release to get the latest fixes out?).

Can you try with libratbag master? If you don't know how to do that manually, it seems that https://aur.archlinux.org/packages/libratbag-git should work fine.

**Comment by Freggar** [comment]
Yeah thanks now it's working, should have checked that one earlier. For fellow AUR users: The current  version of the piper package can't be installed with libratbag-git, so I've created a piper-git AUR package.
