### ISSUE TITLE
Error when launching piper.devel [ValueError: Namespace Rsvg not available]

### ISSUE THREAD

**Issue by Alien1993** [libratbag/piper#203]
I've tried compiling the latest version of piper, commit d243325,  but I get this issue when trying to launch `piper.devel` directly from the build directory. `librsvg` is installed, version is 2.40.13.

```
Running from source tree, using local files
Traceback (most recent call last):
  File "./piper.devel", line 39, in <module>
    from piper.application import Application
  File "/home/alien/workspace/piper/piper/application.py", line 18, in <module>
    from .window import Window
  File "/home/alien/workspace/piper/piper/window.py", line 21, in <module>
    from .mouseperspective import MousePerspective
  File "/home/alien/workspace/piper/piper/mouseperspective.py", line 19, in <module>
    from .buttonspage import ButtonsPage
  File "/home/alien/workspace/piper/piper/buttonspage.py", line 20, in <module>
    from .mousemap import MouseMap
  File "/home/alien/workspace/piper/piper/mousemap.py", line 25, in <module>
    gi.require_version("Rsvg", "2.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

Am I doing something wrong or should I go back to some stabler commit? 

By the way if it might be useful libratbag is compiled at commit `cbcdc4b` and running with no issue.

**Comment by whot** [comment]
weird. Not sure what's going on here, the error message is a python import error, it can't find rsvg but you say it's installed? This isn't a piper issue directly, something else is going on here. What happens if you run `python3` and then
```
import gi
gi.require_version("Rsvg", "2.0")
```

**Comment by Alien1993** [comment]
I've solved it. I installed `librsvg2-dev` and it started right away. Thank you for the help anyway. :)
I'm on Ubuntu by the way if that might be useful to someone.

**Comment by AgentConDier** [comment]
Sorry for resurrecting old issues, but for anyone else stumbling upon this:
I solved the same issue by only installing `gir1.2-rsvg-2.0`. Saves about 18MB of disk space (MX Linux 21.1, based on Debian Bullseye)

**Comment by brenly** [comment]
in lubuntu it creates some kind of dependency hell:

sudo apt-get install librsvg2-dev
output:
 librsvg2-dev : Depends: gir1.2-rsvg-2.0 (= 2.50.1+dfsg-1) but it is not going to be installed
                Depends: libcairo2-dev (>= 1.2.0) but it is not going to be installed
                Depends: libgdk-pixbuf2.0-dev (>= 2.23.5-2) but it is not going to be installed
                Depends: libglib2.0-dev (>= 2.50.0) but it is not going to be installed

already installed all of these dependencies via pip. and trying to install librsvg2 via pip isnt working.
