### ISSUE TITLE
Macros do not capture meta (super/windows) key

### ISSUE THREAD

**Issue by phomes** [libratbag/piper#206]
Trying to set a macro with a meta key as modifier does not work. Gnome shell reacts to the keypress and shows the Activities screen.

**Comment by Hjdskes** [comment]
This works for me on GNOME Shell 3.28. What version are you using?

**Comment by phomes** [comment]
I am on fedora 28, and checking again now with gnome shell 3.28 (on wayland) I no longer see the issue.
