### ISSUE TITLE
piper don't start

### ISSUE THREAD

**Issue by Driglu4it** [libratbag/piper#207]
At startup piper gives an error: 
device logitech usb receiver does not support switchable resolutions
where is the mistake?
Mouse - G602

**Comment by Hjdskes** [comment]
Can you post the output of `ratbagctl.devel list -vvv`? This will tell us if your device is properly supported. There is no device SVG, so Piper cannot configure your device, but `ratbagctl` can. Note that `ratbagctl.devel` will be in the build folder of ilbratbag.

**Comment by whot** [comment]
Closing after too many months of watching tumbleweeds roll past
