### ISSUE TITLE
Can't start piper on Ubuntu 18.04

### ISSUE THREAD

**Issue by dgroos** [libratbag/piper#209]
Successfully install libratbag. Service is running:

    ● ratbagd.service - Daemon to introspect and modify configurable mice
       Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
       Active: active (running) since Sun 2018-04-22 14:01:49 CDT; 2h 0min ago
     Main PID: 3140 (ratbagd)
        Tasks: 1 (limit: 4915)
       CGroup: /system.slice/ratbagd.service
               └─3140 /usr/bin/ratbagd

    Apr 22 14:01:49 myputer systemd[1]: Starting Daemon to introspect and modify configurable mice...
    Apr 22 14:01:49 myputer systemd[1]: Started Daemon to introspect and modify configurable mice.

Installed piper. The following is what I did along with the terminal out (note that this is from a reinstall of piper after first removing builddir):

myuser@myputer:~/piper$ meson builddir --prefix=/usr/

    The Meson build system
    Version: 0.45.1
    Source dir: /home/myuser/piper
    Build dir: /home/myuser/piper/builddir
    Build type: native build
    WARNING: Newline character in a string detected, use ''' (three single quotes) for multiline strings instead.
    This will become a hard error in a future Meson release. config_piper_devel.set('devel', ' 43 32
    Project name: piper
    Build machine cpu family: x86_64
    Build machine cpu: x86_64
    Found pkg-config: /usr/bin/pkg-config (0.29.1)
    Native dependency python3 found: YES 3.6
    Native dependency pygobject-3.0 found: YES 3.26.1
    Configuring AboutDialog.ui using configuration
    Native dependency glib-2.0 found: YES 2.56.1
    Message: Getting Python3 install dir
    Configuring piper using configuration
    Configuring piper.devel using configuration
    Program meson_install.sh found: YES (/usr/bin/env sh /home/myuser/piper/meson_install.sh)
    Build targets in project: 4
    Found ninja-1.8.2 at /usr/bin/ninja

myuser@myputer:~/piper$ ninja -C builddir

    ninja: Entering directory `builddir'
    [1/1] Generating piper_gresource with a custom command.

myuser@myputer:~/piper$ sudo ninja -C builddir install

    ninja: Entering directory `builddir'
    [0/1] Installing files.
    Installing subdir /home/myuser/piper/piper to /usr/lib/python3.6/site-packages/piper
    Installing data/piper.gresource to /usr/share/piper/piper.gresource
    Installing /home/myuser/piper/data/org.freedesktop.Piper.desktop to /usr/share/applications
    Installing /home/myuser/piper/data/org.freedesktop.Piper.svg to /usr/share/icons/hicolor/scalable/apps
    Installing /home/myuser/piper/builddir/piper to /usr/bin
    Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=piper'
    Installing /home/myuser/piper/builddir/po/de.gmo to /usr/share/locale/de/LC_MESSAGES/piper.mo
    Installing /home/myuser/piper/builddir/po/hr.gmo to /usr/share/locale/hr/LC_MESSAGES/piper.mo
    Installing /home/myuser/piper/builddir/po/nl.gmo to /usr/share/locale/nl/LC_MESSAGES/piper.mo
    Installing /home/myuser/piper/builddir/po/pl.gmo to /usr/share/locale/pl/LC_MESSAGES/piper.mo
    Installing /home/myuser/piper/builddir/po/sv.gmo to /usr/share/locale/sv/LC_MESSAGES/piper.mo
    Running custom install script '/usr/bin/env sh /home/myuser/piper/meson_install.sh'
    gtk-update-icon-cache: Cache file created successfully.

Upon clicking on the piper app launcher it looks like piper is trying to launch, but after 5 or so seconds disappears. Going to syslog one sees:

    Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: Traceback (most recent call last):
    Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: File "/usr/bin/piper", line 36, in
    Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: from piper.application import Application
    Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: ModuleNotFoundError: No module named 'piper'

I've got the crash report but not sure if that's helpful, also not sure if it's a good idea to share all that info on a pastebin page.
Any ideas?

**Comment by dgroos** [comment]
Here are a few answers, not sure which might be most helpful:

`python -m site --user-site`

> /home/myuser/.local/lib/python2.7/site-packages

`python`

> Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
> [GCC 7.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.

`>>> import site; site.getsitepackages()`

> ['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

`python3 -m site --user-site`

> /home/myuser/.local/lib/python3.6/site-packages

`python3`

> Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.

`>>> import site; site.getsitepackages()`

> ['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']

The lists generated when I enter:
```
python
>>>help('modules')

```
or for python 3:
```
python3
>>>help('modules')
```

do NOT include piper.

**Comment by whot** [comment]
You're not the first to run into this issue, so I decided to install a 18.04 vm. And the result is: blame the ubuntu defaults, they're screwed up:

* https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092
* https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092

The summary is: meson gets the directory where to install to from python's `sysconfig` module, but that doesn't point to where python actually loads modules from. Best for your sanity is probably to symlink `site-packages` to `dist-packages` and continue from there. But not something we can fix in piper without adding weird hacks.

**Comment by dgroos** [comment]
I'll give the symlink a go this evening, thanks for figuring this out! 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Peter Hutterer <notifications@github.com> Date: 4/22/18  11:34 PM  (GMT-06:00) To: libratbag/piper <piper@noreply.github.com> Cc: David G <djgroos@gmail.com>, Author <author@noreply.github.com> Subject: Re: [libratbag/piper] Can't start piper on Ubuntu 18.04 (#209) 
You're not the first to run into this issue, so I decided to install a 18.04 vm. And the result is: blame the ubuntu defaults, they're screwed up:

https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092
https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092

The summary is: meson gets the directory where to install to from python's sysconfig module, but that doesn't point to where python actually loads modules from. Best for your sanity is probably to symlink site-packages to dist-packages and continue from there. But not something we can fix in piper without adding weird hacks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/libratbag/piper","title":"libratbag/piper","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/libratbag/piper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whot in #209: You're not the first to run into this issue, so I decided to install a 18.04 vm. And the result is: blame the ubuntu defaults, they're screwed up:\r\n\r\n* https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092\r\n* https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092\r\n\r\nThe summary is: meson gets the directory where to install to from python's `sysconfig` module, but that doesn't point to where python actually loads modules from. Best for your sanity is probably to symlink `site-packages` to `dist-packages` and continue from there. But not something we can fix in piper without adding weird hacks."}],"action":{"name":"View Issue","url":"https://github.com/libratbag/piper/issues/209#issuecomment-383451686"}}}

**Comment by dgroos** [comment]
Gave it a try and not working:
`myuser@myputer:~$ sudo ln -s /usr/lib/python3.6/site-packages/piper /usr/lib/python3/dist-packages`

When I launch piper in terminal I get:
`myuser@myputer:~$ piper`

> Traceback (most recent call last):
>   File "/usr/bin/piper", line 36, in <module>
>     from piper.application import Application
>   File "/usr/lib/python3/dist-packages/piper/application.py", line 17, in <module>
>     from .ratbagd import Ratbagd, RatbagdDBusUnavailable
>   File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 28, in <module>
>     from evdev import ecodes
> ModuleNotFoundError: No module named 'evdev'

Though:
`myuser@myputer:~$ ls -la /usr/lib/python3/dist-packages/ | grep piper`

> lrwxrwxrwx   1 root root     38 Apr 23 21:35 piper -> /usr/lib/python3.6/site-packages/piper

Did I do that right?

**Comment by whot** [comment]
well, that's better than the previous attempt... :)

you need the python3-evdev module or whatever it's called on ubuntu.
Generally any "ModuleNotFoundError" means you're missing some dependency.
But that error message means piper itself is starting now.

**Comment by dgroos** [comment]
```
sudo apt-get install python3-evdev
sudo apt install python3-lxml #also hadn't installed
piper
```
And piper launched!
Next I quit piper, enabled ratbagd.service with: `sudo systemctl enable ratbagd.service`
I again launched piper but it again showed the simple gray box as shown below. 

I'm not sure how to add (enable?) a profile. I'm using a device that seems to have a profile in /usr/share/libratbag/devices/: logitech-M705.device. Did I miss something in the readme or elsewhere?
![screenshot from 2018-04-24 20-23-40](https://user-images.githubusercontent.com/4097759/39221663-eaa088bc-47fd-11e8-9e12-4e555172e2a6.png)

**Comment by dgroos** [comment]
I thought I had started ratbagd last night with:
`sudo systemctl enable ratbagd.service` but after a reboot this morning and rerunning this command again and checking with `pgrep ratbagd` and it returning nothing I checked my notes again and saw I needed to run:
`sudo systemctl start ratbagd.service` 
which appeared to work since pgrep command returned a pid and the output of
`sudo systemctl status ratbagd.service`

> ● ratbagd.service - Daemon to introspect and modify configurable mice
>    Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2018-04-25 06:59:46 CDT; 1min 24s ago
>  Main PID: 5432 (ratbagd)
>     Tasks: 1 (limit: 4915)
>    CGroup: /system.slice/ratbagd.service
>            └─5432 /usr/bin/ratbagd
> 
> Apr 25 06:59:46 ubu2 systemd[1]: Starting Daemon to introspect and modify configurable mice...
> Apr 25 06:59:46 ubu2 systemd[1]: Started Daemon to introspect and modify configurable mice.
> Apr 25 07:00:00 ubu2 ratbagd[5432]: ratbagd error: event8: failed to fetch SVG
 
The piper icon is in gnome's menubar (also shown below)

![screenshot from 2018-04-25 07-22-57](https://user-images.githubusercontent.com/4097759/39245491-92c88eda-4859-11e8-974d-9874830e8575.png)

**Comment by dgroos** [comment]
OK. Thanks @Hjdskes for your help with this. Now I've got a summer project... :-D
David

**Comment by erdincay** [comment]
sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service
