### ISSUE TITLE
LG M705

### ISSUE THREAD

**Issue by zapphyre** [libratbag/piper#215]
Hello!
Is this software intended to work with mouse type stated in title?
What it does on my end is that piper starts with blank screen and one active profile. Nothing in console.
Basic mouse but has a few buttons that would be nice to configure.

Thanks for your input!

**Comment by bentiss** [comment]
It is not made for the M705, no. The M705 has no hardware programmable buttons, and we do not support button emlation in libratbag (yet?). The Windows driver of the M705 has some capabilities but it is difficult to reproduce those here.
