### ISSUE TITLE
PyGI templates support is officially supported now

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#219]
Someone was asking about Gtk.Builder templates support in Python. When referring this person to my summary of the unofficial `gi_composites.py`, I found that recently official template support was added to PyGObject. See https://gitlab.gnome.org/GNOME/pygobject/merge_requests/52.

If this supports all our needs, we might be able to drop the unofficial `gi_composites.py` for newer versions of Piper. Less unofficial hacks == more goodness.

**Comment by whot** [comment]
fwiw, requires GTK 3.30, so let's hold off on that for a bit longer.

**Comment by Hjdskes** [comment]
Sure, but let's keep this issue open to track it.
