### ISSUE TITLE
Can't compile piper. 

### ISSUE THREAD

**Issue by Gnun1x** [libratbag/piper#225]
When typing in 
`meson builddir --prefix=/usr/`
I get this error: 

> Meson encountered an error in file meson.build, line 1, column 0:
> Not enough arguments to project(). Needs at least the project name and one language

What can I do about this?

**Comment by Gnun1x** [comment]
`meson --version`
`0.37.1`

What I did to get here? follow the tutorial.

**Comment by whot** [comment]
Sorry, you'll need a newer meson version, we require at least 0.40.0. And unfortunately 0.37 doesn't seem to parse the "meson_version" requirement in the first line :(
