### ISSUE TITLE
Can't run Piper. 

### ISSUE THREAD

**Issue by Gnun1x** [libratbag/piper#228]
OS: Debian sid (10) 
Piper doesn't run. 
Starting piper in the application window doesn't work. Says it's starting up in the top of the screen, but crashes. 
Can't run it in Xterm, `no module named piper`
followed the issues #15 and #66, still doesn't work. 

`~$ PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6/site-packages piper`

`Traceback (most recent call last):`
  `File "/usr/lib/python3.6/site-packages/piper/application.py", line 45, in do_startup`
    `self._ratbag = Ratbagd()`
  `File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 257, in __init__`
    `self._devices = [RatbagdDevice(objpath) for objpath in result]`
  `File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 257, in <listcomp>`
    `self._devices = [RatbagdDevice(objpath) for objpath in result]`
  `File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 325, in __init__`
    `self._profiles = [RatbagdProfile(objpath) for objpath in result]`
  `File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 325, in <listcomp>`
    `self._profiles = [RatbagdProfile(objpath) for objpath in result]`
  `File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 423, in __init__`
    `self._leds = [RatbagdLed(objpath) for objpath in result]`
`TypeError: 'NoneType' object is not iterable`
`

**Comment by dasunsrule32** [comment]
Same error for me on 18.04.
