### ISSUE TITLE
Piper fails to launch when Logitech G502 connected

### ISSUE THREAD

**Issue by microbug** [libratbag/piper#232]
When I run Piper with my G502 mouse connected:

- Piper does not launch:
- I get this output:

```
(piper:2008): Gtk-WARNING **: 23:03:07.967: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:2008): Gtk-WARNING **: 23:03:07.967: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:2008): Gtk-WARNING **: 23:03:07.967: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

If I disconnect the G502:

- **Piper launches successfully**
- The 'cannot find any devices' screen is shown (as expected)
- When I reconnect the G502 the same error (`TypeError: Couldn't find foreign struct converter for 'cairo.Context'`) is shown before the window closes
- Once Piper has exited the console output is the same as the full log above:

```
(piper:3123): Gtk-WARNING **: 23:08:12.865: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:3123): Gtk-WARNING **: 23:08:12.865: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:3123): Gtk-WARNING **: 23:08:12.865: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

I have checked that I have `python-gi-cairo` installed. The full installation I used is as follows (probably not relevant but I couldn't find it listed anywhere else in full):

```
# install libratbag
# the next 4 lines are taken from https://github.com/libratbag/libratbag/blob/master/circle.yml
sudo apt-get install -y software-properties-common
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install -y tree git gcc g++ pkg-config meson check libudev-dev libevdev-dev libsystemd-dev valgrind python3-gi python3-evdev libglib2.0-dev python3-lxml python3-dev swig systemd
cd ~
git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir --prefix=/usr/
ninja -C builddir
sudo ninja -C builddir install
sudo systemctl start ratbagd
sudo systemctl enable ratbagd

# install piper
sudo apt install build-essential python3 python3-dev python3-pip pkg-config gettext python-gi-dev meson ninja-build git python3-evdev python3-lxml librsvg2-dev
cd ~
git clone https://github.com/libratbag/piper.git
cd piper
meson builddir --prefix=/usr/
ninja -C builddir
sudo ninja -C builddir install

# run piper
PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6/site-packages piper
```

**Comment by microbug** [comment]
I just tested this with the [unofficial PPA](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/ratbag-piper) and experienced the same problem.

**Comment by microbug** [comment]
I believe that has been replaced with `python-gi-cairo` in recent versions. That is already installed (`python-gi-cairo is already the newest version (3.26.1-2).`)

**Comment by whot** [comment]
sorry, not sure where that is. we've had no end of issues with Ubuntu's handling of python/gi and piper works fine as-is on Fedora. So I'm putting my bets on this being yet another screwup with Ubuntu's python.

**Comment by microbug** [comment]
Thanks, I'll try to get it working on Fedora then.

I just found #202 — official Flatpak builds would be really helpful.

**Comment by mati865** [comment]
On Ubuntu 18.04 with PPA mentioned before it works fine for me with G502 Proteus Spectrum.

**Comment by microbug** [comment]
Huh ok, I might have messed up my installation at some point. I'm on Kubuntu 18.04.1 so should be the same. I'll give it another try tonight.

**Comment by microbug** [comment]
I managed to fix this by installing python3-gi-cairo (as opposed to python-gi-cairo): `apt install python3-gi-cairo`. Piper is now working properly.

**Comment by Vandool** [comment]
> I managed to fix this by installing python3-gi-cairo (as opposed to python-gi-cairo): `apt install python3-gi-cairo`. Piper is now working properly.

I can't find the package through AUR or pacman or pamac, I run manjaro ...
