### ISSUE TITLE
Leader lines are not updated on resize

### ISSUE THREAD

**Issue by phomes** [libratbag/piper#233]
This is most likely not a bug in Piper, but a problem we should look into either way. I just tested Piper on fedora 29 and the leader lines are drawn in a wrong location and do not update with the rest of the SVG when resizing the window.

**Comment by Hjdskes** [comment]
Does fedora 29 have a newer librsvg than fedora 28, assuming you used that previously?

**Comment by phomes** [comment]
Yes, this regressed in librsvg. Between 2.42.6 and 2.43.4. I tried installing the latter from rawhide onto a F28 installation and tested with it. Same issue.

**Comment by whot** [comment]
Has anyone filed an issue in librsvg for this yet?

**Comment by Hjdskes** [comment]
I thought @phomes had, but I can't find anything on librsvg's tracker. I can write up an issue tonight or tomorrow if noone beats me to it.

**Comment by phomes** [comment]
I wanted to bisect the problem first but never found the time. I have filed an issue for librsvg now:
https://gitlab.gnome.org/GNOME/librsvg/issues/334

**Comment by federicomenaquintero** [comment]
Hi; I'm the maintainer of librsvg.

I don't have a gaming mouse, so piper just shows me the mousetrap image :smile: 

To test this, I'd like to know what the rendering state is when piper renders the individual elements in the SVG.  As far as I can tell, [this](https://github.com/libratbag/piper/blob/master/piper/mousemap.py#L417-L419) is where piper renders each of the individual leaders and paths.  

Could you put some print statements before that spot, to figure out the following?

* Type of the `cr`'s destination surface.
* Current transformation matrix in the `cr`

I'd love to know if the output for both a working version of librsvg and a non-working version.  Thanks!

**Comment by Hjdskes** [comment]
>  As far as I can tell, this is where piper renders each of the individual leaders and paths.

Correct.

> Could you put some print statements before that spot, to figure out the following?

For transparency, I added the following lines right before the loop that draws the children:

```
print("Surface: ", cr.get_target())
print("Matrix: ", cr.get_matrix())
```

On a non-working version (2.44.6) this gives:

```
Surface:  <cairo.ImageSurface object at 0x7fd3a82db430>
Matrix:  cairo.Matrix(1, 0, 0, 1, 0, 0)
```

On a working version (2.42.6), I get:

```
Surface:  <cairo.ImageSurface object at 0x7f9c142c6590>
Matrix:  cairo.Matrix(1, 0, 0, 1, 66, 186)
```

If there is anything more that you need, please let us know!

**Comment by federicomenaquintero** [comment]
In 2.42.6, the matrix comes in with a translation.  As far as I can tell, that translation is from the `cr.translate()` in `do_draw()`.  The translation offsets come from `_translate_to_origin()`.

I'm not 100% clear on how the children's geometries are computed.  However, `_get_svg_sub_geometry()` is the only place that calls `handle.get_position_sub()` and `handle.get_dimensions_sub()`.  Could you please print the (fragment ID, has_pos, svg_pos, has_dim, svg_dim) inside `_get_svg_sub_geometry()`, for both versions?

Or can you think of anything else in the code flow that would cause that translation matrix to be different?

**Comment by federicomenaquintero** [comment]
I've found a way to reproduce this; librsvg is resetting the affine transformation in the `cr` during each call to `render_cairo_sub()`.  I'll investigate.

**Comment by federicomenaquintero** [comment]
Fixed in librsvg 2.44.7.

**Comment by Hjdskes** [comment]
Awesome! Thanks! Apologies I haven't been able to provide you what you asked.

**Comment by federicomenaquintero** [comment]
No problem; it was enough to narrow it down to the print statements you put in :smile:   Testing is appreciated, of course.
