### ISSUE TITLE
TypeError: 'NoneType' object is not iterable - [RatbagdDevice(objpath) for objpath in result]

### ISSUE THREAD

**Issue by rporter220** [libratbag/piper#237]
Just found out about libratbag/piper recently and today compiled from git and receiving the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/piper/application.py", line 45, in do_startup
    self._ratbag = Ratbagd()
  File "/usr/lib/python3.7/site-packages/piper/ratbagd.py", line 257, in __init__
    self._devices = [RatbagdDevice(objpath) for objpath in result]
TypeError: 'NoneType' object is not iterable
```
Mouse: Logitech G602
Manjaro

**Comment by whot** [comment]
Is there a corresponding error in the ratbagd output? This function should always receive an empy list (`[]`) and never None, not sure how this can happen with the current code.
