### ISSUE TITLE
Instructions to run the code locally

### ISSUE THREAD

**Issue by hackedbellini** [libratbag/piper#238]
The README is missing instructions to run the code without installing it in the system.

I would like to run the code and maybe even contribute to it, but I don't like manually installing things in my debian system. There's also people out there that doesn't have root access to their machines.

**Comment by Hjdskes** [comment]
Build Piper as explained in the README. Then run `./builddir/piper.devel`.

**Comment by Hjdskes** [comment]
This will require an installed libratbag, though. AFAIK there is no easy way around that.

**Comment by hackedbellini** [comment]
@Hjdskes ok thanks!

Regarding the `libratbag` it is not a problem since I can install it from apt. The reason I don't like installing things manually is because it will generate a lot of cruft in my system in the long run, while when using apt/dpkg I can easily track the files origin and remove them acordingly when I do some cleanup.

Either way, if you can add that info to the `README` it would probably help other people like me! :)

**Comment by Hjdskes** [comment]
In that case, #235 will make you happy too :)

> Either way, if you can add that info to the README it would probably help other people like me! :)

Seems like a good first PR, don't you think? ;)

**Comment by hackedbellini** [comment]
> Seems like a good first PR, don't you think? ;)

Touché my friend! Leave it to me ;)

**Comment by whot** [comment]
> This will require an installed libratbag, though

libratbag requires root to write to the devices. once you're at that point, you can usually install anyway ;)

**Comment by hackedbellini** [comment]
> libratbag requires root to write to the devices. once you're at that point, you can usually install anyway ;)

Using the `ratbagd` from debian experimental did the trick for me. I'm now able to run this locally.
I'm just waiting for a reply to [this question](https://github.com/libratbag/piper/issues/239#issuecomment-415972044) and then I'll create a PR to improve the documentation regarding both issues.

**Comment by whot** [comment]
fwiw, PR #248 will address the minimum version requirement but I'd rather **not** have that in the documentation directly (just a link to meson.build would be enough). Otherwise it's one more place where documentation can go stale.
