### ISSUE TITLE
Button missing on G502

### ISSUE THREAD

**Issue by microbug** [libratbag/piper#240]
There is no option to assign a button for the left scrollwheel click on the G502 (Core). The scrollwheel can be pushed left or right, there is an option to assign an action for the right scrollwheel click but not the left one. See the attached image: there should be another label on the left side of the scrollwheel like the one on the right side.

![screenshot_20180825_145650](https://user-images.githubusercontent.com/3200101/44618942-74442e00-a877-11e8-9be7-6e56bac9d267.png)

**Comment by Crazily** [comment]
I can confirm that it's still not there. And keyboard shortcuts never save either.
![screenshot from 2018-10-14 00-56-45](https://user-images.githubusercontent.com/26858841/46912744-131e0a00-cf4c-11e8-9d1a-f3b56816bc74.png)

**Comment by whot** [comment]
Issue is in libratbag, see the above linked pull request. Just a typo but please test, thanks.
