### ISSUE TITLE
Can't bind button to keystroke

### ISSUE THREAD

**Issue by MyLegGuy** [libratbag/piper#242]
I open the menu to set a mouse button's binding (I use mouse button 4). I click "send keystroke" at the bottom of the list. I type something and it appears correctly. I press return to confirm my keystroke. It still appears correctly. (https://i.imgur.com/ohA8lWv.png) When I click apply, nothing happens. The actual label for the mouse button doesn't change from what it as before. Pressing the mouse button doesn't send the keystroke.

Distro: Arch
Mouse: G502
piper version: latest git, 5fbeacc
libratbag version: latest git, 23ff4e753d68267096ea66e729337bb3653fc650

**Comment by whot** [comment]
Are there any logs in ratbagd? You may have to start with --verbose to see the logs there.

**Comment by MyLegGuy** [comment]
There are, but it's all just regular stuff. Nothing new comes up when I try to bind a key to a mouse button.
[code]
$ sudo ratbagd --verbose
ratbag debug: Logitech Gaming Mouse G502 is device '/dev/hidraw3'.
ratbag debug: Logitech Gaming Mouse G502 is device '/dev/hidraw4'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: 'Logitech Gaming Mouse G502' is using protocol v4.2
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1750 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: driver match found: Logitech HID++2.0
event15: "Logitech Gaming Mouse G502", 3 profiles
ratbag debug: dictionary: 00 01 01 00 00 02 01 00 00 03 01 00 ff ff 00 00
[/code]

**Comment by AshotN** [comment]
Trying to set one of my side buttons to page up

```
sudo ratbagd --verbose
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw5'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw6'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw7'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech USB Receiver Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 400 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device is using ROM settings
ratbag debug: ROM settings loaded
ratbag debug: device has configurable mouse button spy
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: driver match found: Logitech HID++2.0
event13: "Logitech USB Receiver Mouse", 5 profiles
ratbag debug: dictionary: 00 01 01 00 00 02 00 00 00 03 00 00 00 04 00 00 00 05 00 00 ff ff 00 00 ff ff ff ff ff ff ff ff

```

**Comment by codedcosmos** [comment]
Also happening to me with the MX Master 2S

```
atbag debug: Logitech MX Master 2S is device '/dev/hidraw5'.
ratbag debug: report ID 01
ratbag debug: report ID 0e
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech MX Master 2S' is using protocol v4.5
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 8 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device is at 1000 dpi (variable between 200 and 4000).
ratbag debug: device has 8 buttons
ratbag debug: driver match found: Logitech HID++2.0
event5: "Logitech MX Master 2S", 1 profiles
```

**Comment by Hjdskes** [comment]
This is likely an issue in libratbag. I'll open an issue to track it there.
