### ISSUE TITLE
Provide an option to unbind a button

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#247]
See https://github.com/libratbag/piper/issues/241#issuecomment-416886673 and the following comment.

**Comment by khimaros** [comment]
as a workaround, you can use `ratbagctl`, for example:

```
$ ratbagctl cheering-viscacha button 7 action get
Button: 7 is mapped to 'resolution-up'
$ ratbagctl cheering-viscacha button 7 action set special unknown
```

it may be necessary to still manually "Apply" the change in the Piper interface afterward.
