### ISSUE TITLE
Meson fails: Not enough arguments to project()

### ISSUE THREAD

**Issue by redstik** [libratbag/piper#265]
Following the instructions exactly stated on the main page, when I do`meson builddir --prefix=/usr/` this is returned: 
`The Meson build system`
`Version: 0.37.1`
`Source dir: /home/xxxx/piper`
`Build dir: /home/xxxx/piper/builddir`
`Build type: native build`

`Meson encountered an error in file meson.build, line 1, column 0:`
`Not enough arguments to project(). Needs at least the project name and one language`
(Debian Stretch, G502)

**Comment by Hjdskes** [comment]
I think your meson version is too old. Can you try with a newer version? See https://mesonbuild.com/Getting-meson.html

**Comment by redstik** [comment]
Now this is returned.

`The Meson build system`
`Version: 0.48.0`
`Source dir: /home/xxxx/piper`
`Build dir: /home/xxxx/Downloads/meson-0.48.0/meson-0.48.0/buildir`
`Build type: native build`
`meson.build:1: WARNING: Passed invalid keyword argument "project".`
`WARNING: This will become a hard error in the future.`

`meson.build:1:0: ERROR:  Not enough arguments to project(). Needs at least the project name.`

`A full log can be found at /home/xxxx/Downloads/meson-0.48.0/meson-0.48.0/buildir/meson-logs/meson-log.txt`

**Comment by redstik** [comment]
This appears to work.
