### ISSUE TITLE
Missing buttons tab and  can't add profile

### ISSUE THREAD

**Issue by Seb-Solon** [libratbag/piper#268]
Hi there,

Thanks a lot for the project, it is a very good replacement for LGS! :wink: 

I have setup piper and ratbag from git with meson as Debian seems to be pretty "late" for the packaging, it was the best option I found. After a small fix (becase 'meson install' setup path did not match my python path),  I managed to get it working except for 2 things :

* Buttons tab shown in the screenshot is not here in my case. Other tabs are working 
* I am unable to create an extra profile, the  button is grayed.

You can see both problem in the screenshot : 

![capture d ecran de 2018-10-07 17-48-00](https://user-images.githubusercontent.com/856137/46587345-37b04880-ca59-11e8-80d4-d7c1ae40cdde.png)

For the button issue I can see there is a condition to add this tab here :  https://github.com/libratbag/piper/blob/master/piper/mouseperspective.py#L90

When I query the device with ratbagctl I have : 

```
event0 - Logitech G403 Prodigy Gaming Mouse
               SVG: logitech-g403.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, disable-profile, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 400dpi @ 1000Hz
    1: 800dpi @ 1000Hz (default)
    2: 1600dpi @ 1000Hz (active)
    3: 3200dpi @ 1000Hz
    4: <disabled>
  Button: 0 type unknown is mapped to 'button 1'
  Button: 1 type unknown is mapped to 'button 2'
  Button: 2 type unknown is mapped to 'button 3'
  Button: 3 type unknown is mapped to 'button 4'
  Button: 4 type unknown is mapped to 'button 5'
  Button: 5 type unknown is mapped to 'resolution-cycle-up'
  LED: 0 type: logo, depth: rgb, mode: off
  LED: 1 type: side, depth: rgb, mode: off
```

There is nothing about Button in the capabilities list, maybe it's just that my mouse is not supported? 
It's strange because the demo screens here are made with this mouse : https://github.com/libratbag/piper/wiki/Piper-Redesign

Other info :

The only error I can get are from journalctl when starting up piper : 
```
 dbus[573]: [system] Rejected send message, 2 matched rules; type="error", sender=":1.199" (uid=0 pid=2032 comm="/usr/bin/ratbagd ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.203" (uid=1000 pid=2099 comm="python3 /usr/bin/piper "
```

```
ratbagd --version
0.9.903
```

**Comment by Stanton-B** [comment]
Hello, I thought I'd just add that for this mouse, I'm having the same issue on linux mint 19 tara (based on ubuntu 18.04 LTS), and xinput shows me this: 
<pre>xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech G403 Prodigy Gaming Mouse      	id=8	[slave  pointer  (2)]
⎜   ↳ Logitech G403 Prodigy Gaming Mouse      	id=9	[slave  pointer  (2)]
</pre>

Additionally, when I run xev, some of the buttons don't register as buttons, but simply as "events"...here is the button down/button up log for the back button on the mouse:
<pre>EnterNotify event, serial 50, synthetic NO, window 0x6400001,
    root 0x1e0, subw 0x0, time 4751991, (24,9), root:(885,465),
    mode NotifyNormal, detail NotifyInferior, same_screen YES,
    focus YES, state 16

KeymapNotify event, serial 50, synthetic NO, window 0x0,
    keys:  4294967264 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 </pre>

**Comment by whot** [comment]
`NotifyGrab` is the key here - something (probably your  window manager) has a grab on that button and the button is never delivered to your xev instance. That's normal for a bunch of buttons and keys that are claimed by the window manager by default. 

As a general rule: don't use xev for event debugging unless you really care about the X events, use `evemu-record` or `libinput record`, both of those tools will show you what comes out of the kernel without interference from the windowing system/manager.


> It's strange because the demo screens here are made with this mouse

Note that those are designs made in inkscape, without any relation to the actual devices supported.

I'm closing this in favour of https://github.com/libratbag/libratbag/issues/533 though because Piper itself doesn't enable devices, it merely uses whatever info it gets over dbus. And in this case the capability is missing, so Piper does the right thing even if libratbag is wrong.
