### ISSUE TITLE
Interfaze missplacement

### ISSUE THREAD

**Issue by rapsaGnauJ** [libratbag/piper#271]
Interfazes displays incorrectly as shown on the screenshots. I'm using a 4k display, maybe that's the cause. The mice is a G502, can't test with any other.

![screenshot_20181014_200335](https://user-images.githubusercontent.com/24842781/46920350-57adb200-cfed-11e8-86fd-ef5874fda085.png)
![screenshot_20181014_201050](https://user-images.githubusercontent.com/24842781/46920351-57adb200-cfed-11e8-8314-09a0937f058d.png)
![screenshot_20181014_201105](https://user-images.githubusercontent.com/24842781/46920352-57adb200-cfed-11e8-9c69-a8ada59f88fc.png)

**Comment by Hjdskes** [comment]
This is due to a bug in librsvg, see #233. There is nothing we can do here, you either need to downgrade to an older working version or upgrade to a newer one with the fix. You can find which versions work in the linked issue.
