### ISSUE TITLE
Can't update Piper anymore

### ISSUE THREAD

**Issue by devopsmica** [libratbag/piper#273]
Yesterday, while running apt-get upgrade, I ran into a major issue.

The following packages have unmet dependencies:
 libratbag-tools : Depends: lur-command but it is not installed
                   Depends: ratbagd
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

Everything I try to do to fix this seems to lead me into circular issues...

**Comment by devopsmica** [comment]
➜  ~ sudo apt-get install lur-command
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libratbag-tools : Depends: ratbagd
 lur-command : Depends: liblur3 (>= 0.4) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by devopsmica** [comment]
➜  ~ sudo apt-get install lur-command
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libratbag-tools : Depends: ratbagd
 lur-command : Depends: liblur3 (>= 0.4) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by muzena** [comment]
@devopsmica 
Read this two posts.
https://github.com/libratbag/libratbag/issues/553#issuecomment-436403347

**Comment by devopsmica** [comment]
Thanks it helped, but before, removing the ppa, then uninstalling did the trick.
