### ISSUE TITLE
Please provide package names in readme.md

### ISSUE THREAD

**Issue by simbalion** [libratbag/piper#280]
The install section of readme.md mentions packages available for major distributions but does not say what they are. I did some searching in debian but was unable to locate a specific package. 

Debian certainly qualifies as a major distribution, can you please include the specific package names for each distro? This is especially important if some major distributions do not have packages.

**Comment by whot** [comment]
The wiki has a section on this: https://github.com/libratbag/piper/wiki/FAQ

**Comment by jellykells** [comment]
The wiki says nothing regarding installing Piper using a package manager. The readme says:

> Most popular distributions package Piper and it is available through the packaging system (apt, dnf, yum, pacman, zypper, ...). This is the preferred way of installing Piper.

No relevant packages found using keyword "piper" with apt.

**Comment by whot** [comment]
piper is listed on the [Prospective packages](https://www.debian.org/devel/wnpp/prospective.en.html) page, so looks like Debian doesn't ship it yet.

**Comment by jellykells** [comment]
Perhaps the readme should be updated to reflect currently available packages? Apt can at least be removed from the list to prevent confusion. Looks like piper [is available](https://www.archlinux.org/packages/?sort=&q=piper) from pacman, but I don't have a way to check any others at the moment.

**Comment by whot** [comment]
ubuntu ships piper last I checked (albeit an outdated version, iirc), so apt is appropriate for that, no?

**Comment by jellykells** [comment]
Where did you check? Ubuntu package search came up with nothing for the last three LTS releases.

**Comment by Hjdskes** [comment]
I added [a page](https://github.com/libratbag/piper/wiki/Installation) to Piper's wiki and updated the README to point to that instead.
