### ISSUE TITLE
Mouse button page not really usable on HiDPI display

### ISSUE THREAD

**Issue by kode54** [libratbag/piper#281]
I'm using a 3840x2160 monitor with my desktop, and have KDE configured to 2x scaling, and this is the result on the button configuration page:

![image](https://user-images.githubusercontent.com/796316/50427219-a16d1100-0856-11e9-8828-7294a2008b26.png)

The rest of the program is fully usable, though.

**Comment by Hjdskes** [comment]
Thanks for reporting this. I don't have a HiDPI display myself, but I'll look into it. Would you be available to test anything once I come up with a possible solution?

**Comment by bentiss** [comment]
Just thinking out loud. Could it be possible for piper to get the dpi scaling and just apply a global dpi scaling to the svg before drawing it?

**Comment by Hjdskes** [comment]
This should fix the issue, yes. I'm not sure if this is possible (and how), so this needs some investigation.

**Comment by Hjdskes** [comment]
@kode54 Can you please test #287? From what I can see when launching a ["fake HiDPI screen"](https://wiki.gnome.org/HowDoI/HiDpi), this should work.
