### ISSUE TITLE
Piper resets settings on computer restart

### ISSUE THREAD

**Issue by codedcosmos** [libratbag/piper#282]
I seem to only be able to retain my settings for the current session. I can hit apply, and it seems to save alright. It will always say I have unsaved settings, but when I reopen the window it seems to have saved fine.

I can use those settings for the entire session. But when I restart, the settings revert to original.

I am using the MX master 2s, and am also trying to use the unifying receiver, which doesn't seem to work consistently with the mouse and piper.

**Comment by Hjdskes** [comment]
This is likely an issue with libratbag and not Piper. Piper is just a graphical interface to libratbag. Can you open an issue at https://github.com/libratbag/libratbag/issues/?

**Comment by codedcosmos** [comment]
On it
