### ISSUE TITLE
another poorly documented ware

### ISSUE THREAD

**Issue by dimyme** [libratbag/piper#283]
without a mouse, one never knows WTF the app is even about.

So the programmers have not thought about the very first things.

**Comment by Dragon8oy** [comment]
Have you ever read the readme?

**Comment by Hjdskes** [comment]
I'm inclined to close this as trolling. You get one chance to explain what the problem is exactly, because I don't understand your point. Without a (gaming) mouse, you don't need Piper. Problem solved?

**Comment by whot** [comment]
closing, this is not an acceptable way of interacting with developers of free software.
