### ISSUE TITLE
Logitech G600 G-Keys

### ISSUE THREAD

**Issue by BurgerJerk** [libratbag/piper#284]
I noticed that there is no way to edit the G-key function on this mouse. You can bind the " Second Mode " to the mouse on the third mouse click (This mouse has an extra button at the far right of the mouse, where your ring finger would normally rest), but there is no way to edit the G-key functions of the mouse via the piper UI.

**Comment by Hjdskes** [comment]
If Piper does not show it, it is likely a missing feature or bug in libratbag. Piper is a simple frontend to capabilities offered by libratbag over DBus, hence Piper doesn't do any special casing for different devices and whatnot. Can you open this issue over at the [libratbag repository](https://github.com/libratbag/libratbag)?
