### ISSUE TITLE
Make SVG check more robust

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#286]
Per #170, the check we currently perform (i.e.e, checking for the three layers to exist) was a quick 'n dirty check while we were in the transition phase to new style SVGs. The consensus from #170 is that we should keep and extend this check, possibly in the way that [`check_svg`](https://github.com/libratbag/libratbag/blob/master/data/gnome/check-svg.py) from libratbag does right now.

**Comment by whot** [comment]
The SVG check script has moved from libratbag to here now, so let's close this one.
