### ISSUE TITLE
Piper crashes after mouse goes into standby mode

### ISSUE THREAD

**Issue by lluchs** [libratbag/piper#289]
I'm using the MX Master 2S connected via bluetooth. After the mouse sits unused for a while, it seems to go into some standby mode and reconnects once you move it again. The mouse then forgets all previous configuration (i.e., the DPI setting), but piper still shows the old setting (this is a bit of an interesting sub-case of libratbag/libratbag#596, as piper does actually retain the setting longer than the mouse, but of course does not currently re-apply it). If you try to change the DPI slider, piper crashes with the following output (this is for piper 0.2.902):

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/gi/_propertyhelper.py", line 404, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3.7/site-packages/piper/ratbagd.py", line 623, in resolution
    self._set_dbus_property("Resolution", "(uu)", res)
  File "/usr/lib/python3.7/site-packages/piper/ratbagd.py", line 183, in _set_dbus_property
    2000, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.ratbag1" does not exist (3)
```

After a restart, piper works as expected again.

**Comment by Hjdskes** [comment]
That error indicates that ratbagd has restarted in the background. The latest master of Piper should be able to deal with ratbagd disappearing. What versions of Piper and libratbag are you using?

**Comment by lluchs** [comment]
I'm using Piper 0.2.902 and some fairly recent master version of libratbag. I'm going to try the master version of piper. I had a quick look at the commit list before opening the issue, but did not notice anything relevant.

**Comment by Hjdskes** [comment]
These are the two commits you want:

1. https://github.com/libratbag/piper/commit/1d40b147228317d9841d5a5689a129ee621ed753
2. https://github.com/libratbag/piper/commit/1ac9b31e89d6774040e5f81fc41397e48b5f0f84

**Comment by whot** [comment]
For the sake of simplicity, let's close this bug and @lluchs, please re-open it if it still happens with git master.

**Comment by lluchs** [comment]
I can confirm that these commits indeed fix the crash. However, I'm not convinced that this is a good solution, as I still have to restart piper manually (exactly the same thing as after the crash). Can't piper do whatever the restart does automatically without user interaction? Or there could at least be a "Restart" button on the error screen.

**Comment by whot** [comment]
it's a fair bit of effort to make piper surive a ratbag restart properly (short of just execve-ing itself). that effort would be better spent making ratbagd not crash in the first place, IMO

**Comment by lluchs** [comment]
I checked for that, and ratbagd doesn't crash at all. It's printing "Exiting after idle" to the log, so it looks like an intentional thing.

**Comment by whot** [comment]
Oh, right. That should only trigger after ~20min of idle, see libratbag commit e38bc7a7608a88137eda2daa5664b43ece451928. That's an intentional behaviour though, we didn't expect piper to be open for longer than 20min (and sit there unused for the whole time).

I guess we could work around this by piper sending a ping to ratbagd to keep it awake (would need a  new interface in ratbagd). Or have a "restart me" button in piper.

**Comment by lluchs** [comment]
Ah, well, the reason I'm keeping piper always open is because my mouse does not support persistent profiles, so I have to periodically reset my target DPI. I suppose ratbagd won't exit anymore once someone implements proper support for these mice.

**Comment by szmarczak** [comment]
> That's an intentional behaviour though, we didn't expect piper to be open for longer than 20min

Why is the time limit needed at all?

**Comment by whot** [comment]
that time limit is one in ratbagd, it exits if nothing has been changed on the device for 20 min. This means you don't have another process running forever when, in the majority of use-cases, it doesn't do anything after the initial commit. It's socket-activated so restarting piper means it'll restart ratbagd as well.

for the case of non-persistent profiles: this should really be handled in ratbagd so it doesn't actually exit in that case, having piper running seems like bad UX.
