### ISSUE TITLE
Piper doesn't read the current DPI profile in the G603

### ISSUE THREAD

**Issue by FFY00** [libratbag/piper#296]
When piper starts, the current dpi profile of my G603 isn't being loaded.

**Comment by Hjdskes** [comment]
Strange. Piper doesn't do anything by itself with the devices though, so this has to be an issue with libratbag or the driver.

**Comment by FFY00** [comment]
Ugh, you're right. ratbagctl gets the wrong dpi setting. This seems kinda weird since we have a proper function to do that. I need to see what going on. Closing this as it doesn't appear to be a piper issue, sorry.
