### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by danbuntu** [libratbag/piper#3]
Hello

Can you provide some install instructions for ubuntu please?

I've done python setup.py build, python setup.py install.

But I'm getting:

ImportError: No module named 'ratbagd'

When I run it.

**Comment by LewisMCYoutube** [comment]
[install ratbagd](https://github.com/libratbag/ratbagd)?

**Comment by whot** [comment]
bit late, but yes - ratbagd is required for the python module. 

This is about to change though, we just dropped the ratbagd python bindings and they'll move into piper directly. Stay tuned.
