### ISSUE TITLE
NO pkg config NO python3 dependency

### ISSUE THREAD

**Issue by synops9** [libratbag/piper#301]
Hi guys,

Tried downloading multiple dependencies, got this list below from archlinux wiki and downloaded all the below dependencies as well as python3 variants.

Dependencies (7)

    libratbag>=0.9.900
    python
    python-cairo
    python-evdev
    python-gobject
    python-lxml
    meson (make)

I have piper installed in my home directory, still getting the below message when I try to run 
meson builddir --prefix=/usr/

The Meson build system
Version: 0.49.2
Build type: native build
Project name: piper
Project version: 0.2.903
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found Pkg-config: NO
Dependency python3 found: NO 

meson.build:11:0: ERROR:  Pkg-config not found.

Sorry if this has been raised before, I have searched around alot and all attempted solutions (mainly installing different dependencies) does not work. Is it an issue with installing it in my home/*/ directory?

Thanks

**Comment by Hjdskes** [comment]
> got this list below from archlinux wiki

Care to link the page? There is no page on Piper.

> meson.build:11:0: ERROR: Pkg-config not found.

When compiling packages on Arch Linux, it is generally assumed you have the `base-devel` group installed. This group comes with `pkgconf`, which provides `pkg-config`. With `pkg-config` installed, meson should be able to find python.

That said, is there any reason you're not using the [provided Arch package](https://www.archlinux.org/packages/community/any/piper/) for Piper?

**Comment by synops9** [comment]
> > got this list below from archlinux wiki
> 
> Care to link the page? There is no page on Piper.
> 
> > meson.build:11:0: ERROR: Pkg-config not found.
> 
> When compiling packages on Arch Linux, it is generally assumed you have the `base-devel` group installed. This group comes with `pkgconf`, which provides `pkg-config`. With `pkg-config` installed, meson should be able to find python.
> 
> That said, is there any reason you're not using the [provided Arch package](https://www.archlinux.org/packages/community/any/piper/) for Piper?


From here:
https://www.archlinux.org/packages/community/any/piper/

Im using Xubuntu actually, I just find myself using archwiki regularly since it has been useful in the past.

**Comment by Hjdskes** [comment]
That's not the Arch Wiki, and that is definitely not how you should install packages if you don't know what you're doing.

There is a PPA available for Ubuntu and I recommend you use that. See [our Wiki](https://github.com/libratbag/piper/wiki/Installation). Otherwise, you'll need to find the equivalent Ubuntu package for Arch's `pkgconf` so that you pull in `pkg-config`.

**Comment by synops9** [comment]
> That's not the Arch Wiki, and that is definitely not how you should install packages if you don't know what you're doing.
> 
> There is a PPA available for Ubuntu and I recommend you use that. See [our Wiki](https://github.com/libratbag/piper/wiki/Installation). Otherwise, you'll need to find the equivalent Ubuntu package for Arch's `pkgconf` so that you pull in `pkg-config`.

Thanks I got it installed and then updated. One final thing.. Piper cannot find my mouse (G603) tried with bluetooth connectivity and with the wifi USB dongle, I can also see the G603 is in the list of compatible devices.

**Comment by synops9** [comment]
Ok ... pretty sure I worked it out, I need to paste the below code into my libratbag folder as a .svg file type? is that correct? Sorry very new to Linux

# Logitech G603
[Device]
Name=Logitech G603
DeviceMatch=bluetooth:046d:b01c
Driver=hidpp20
Svg=logitech-g603.svg

**Comment by Hjdskes** [comment]
The G603 should be supported already. If it doesn't work, open an issue on libratbag and list the exact steps you took when installing libratbag. I guess something went wrong because you installed libratbag/piper (you did install both, right?) in your home directory, but without you listing your exact steps we can only guess.
