### ISSUE TITLE
Problems with Logitech MX Master 2S 

### ISSUE THREAD

**Issue by elichai** [libratbag/piper#303]
Hi, it's pretty cool that it supports the Logitech MX Master 2S, but there are a few problems:

1. somehow the DPI and Hz gets resetted to 50 and 1000 every once in a while.

2. I can't change the buttons, if I try I get:
`Something went wrong. The device has been reset to previous state.`

**Comment by bentiss** [comment]
> 1. somehow the DPI and Hz gets resetted to 50 and 1000 every once in a while.

This is because the changes are not persistent. They are in the volatile memory, and we would need to have `ratbagd` to monitor for connection/disconnection of the device and re-apply the settings. I think there are already a few bugs opened for that in libratbag.

>    2\. I can't change the buttons, if I try I get:
>        `Something went wrong. The device has been reset to previous state.`

Care to provide more logs? This should be a libratbag issue, so we will need you to use the CLI (IIRC we need `ratbagctl.devel -vvv list` and then which command you are trying to set on the mouse.)

**Comment by elichai** [comment]
I'll make the logs and open it on the libratbag.
and I thought that the mouse has it's own storage for these things.
Maybe I can add these settings through the CLI to bashrc or a cron job?

**Comment by bentiss** [comment]
> I'll make the logs and open it on the libratbag.

thanks

> I have `ratbagctl` but not `ratbagctl.devel`, is that a debug mode build? or is this the same thing?

you need to use the git master branch to have access to those `devel` packages. This is what we use to debug the tool before installing, so you should not have to install. Just clone the tree, compile it and run the produced `ratbagctl.devel`.

> and I thought that the mouse has it's own storage for these things.

We might not switch the correct flag, but most of the time, you need a daemon on the host to detect the reset and set the parameters.

> Maybe I can add these settings through the CLI to bashrc or a cron job?

You will always end up racing with the mouse. You never know when the mouse disconnects or when it reconnects. The solution is to listen for the incoming events, and see when the mouse reconnects, and then send the whole config.
So this needs to be in ratbagd, but the code is not in place right now.

thanks.

**Comment by elichai** [comment]
@bentiss So manually doing: 
`sudo ./ratbagctl.devel button 5 set action button 1  event18` actually works.
So I guess it is a bug in piper.

When I try setting a macro I get `Error: assigning a macro is not supported on this device` which is too bad.

I'll see if I can still make it do cool thing mapping it only to buttons.
But thanks for your help

**Comment by bentiss** [comment]
> When I try setting a macro I get `Error: assigning a macro is not supported on this device` which is too bad.

You should be able to set a 'simple' macro: key and modifiers. The device doesn't support full macros.

**Comment by elichai** [comment]
How can I do that? (there aren't a lot of examples in libratbag on what I can set exactly)
Trying to do `sudo ./ratbagctl.devel button 5 action set macro KEY_A event18` gives me the macro is not supported

Thank you!

**Comment by bentiss** [comment]
> Trying to do `sudo ./ratbagctl.devel button 5 action set macro KEY_A event18` gives me the macro is not supported

Then that means I was wrong and your mouse doesn't support assigning a key to a button. The Windows software might be able to do it, but it injects itself the key events, which we are not doing in Linux. In libratbag, we rely on the mouse to send the key events.

**Comment by elichai** [comment]
of the software is the one to inject the macro and it just listens for the event from the mouse?
hmmmm,
maybe i'll assign it a random button and try to play with xinput and stuff like that.

It's really sad that logitech doesn't support linux.

**Comment by Hjdskes** [comment]
> So manually doing:
`sudo ./ratbagctl.devel button 5 set action button 1 event18` actually works.
So I guess it is a bug in piper.

Weird, Piper uses the exact same DBus bindings as ratbagctl. Can you list the exact steps you're taking in Piper?

**Comment by elichai** [comment]
@Hjdskes So while I recreated my steps I noticed something.
In piper I only tried special buttons and macros, when I tried to choose something regular like "Right mouse button click" it just works, so it turns out I was wrong and this isn't about piper.
Sorry.

**Comment by Hjdskes** [comment]
Cool, thanks for taking another look. I think that solves all the problems raised in this issue. If not, feel free to reopen.
