### ISSUE TITLE
piper empty window

### ISSUE THREAD

**Issue by tethragon** [libratbag/piper#307]
I use linux mint 19.1 fully updated. After yesterday's ratbag update (old version 0.9.904-3-201902200959 // new version 0.9.904-3-201902260819~ubuntu18.04.1), piper will launch but shows an empty window. Uninstalling and reinstalling didn't help.

**Comment by whot** [comment]
libratbag had a flurry of API changes in the last week or so, you'll need #306 to catch up to those. If it still happens then, we'll need to look at what is happening.

**Comment by TacoRaptor67** [comment]
I'm on Netrunner 19.01 and the same is happening for me. I installed libratbag weeks ago and I swear it updates so often.. I couldn't get Piper to work by the normal install, but it seems to work when installed as a flatpak. Though, it shows up an empty window minus the Profile button and the menu button that brings down the About button. I updated libratbag just before installing Piper.

**Comment by whot** [comment]
see https://github.com/libratbag/piper/issues/307#issuecomment-467727561, libratbag does not ship the SVGs anymore, they're now in piper. unless you have an updated version of that (piper git master will do) it simply won't work.

**Comment by Hjdskes** [comment]
Please reopen if this issue persists after updating to the latest versions.

**Comment by tethragon** [comment]
Just now my software manager (Linux mint 19.1) updated piper and everything works great!

**Comment by TacoRaptor67** [comment]
> Just now my software manager (Linux mint 19.1) updated piper and everything works great!

Got rid of Piper because I had no clue what I was doing, but installed after I saw this and it works just fine here as well.
