### ISSUE TITLE
left/right-handed setting doesn't update the buttons

### ISSUE THREAD

**Issue by whot** [libratbag/piper#309]
seen on 106a071ebf0ef7dcabf1328fa70adb6c7ec91b3b with an MX Anywhere 2S: switching between left/righthanded mode in the button panel doesn't update what is displayed for the two buttons. The left button keeps showing "Left mouse button click" despite the button now being a right one and the same for the right button.

It's correct after restarting piper but there's a notification missing somewhere.

**Comment by Hjdskes** [comment]
I can confirm this locally. It seems like we only sent out a signal for when the button's action type changes. so we'll need to add some logic for other properties here as well.
