### ISSUE TITLE
Resolutions page needs a way to set a profile's default resolution.

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#31]
The mockups left this out, so this isn't yet decided.

@whot [suggested](https://github.com/libratbag/piper/pull/28#issuecomment-313603601) a check mark next to the delete button (functioning like a radio button, e.g. only one can be selected at any given time) or an "advanced" popup menu that has the check mark in there, and if supported by the device also exposes the scale for the y-resolution. My personal preference would be the former, but let's open a discussion on this.

**Comment by bentiss** [comment]
I also would prefer to minimize the interactions, and thus having a radio button next to the resolutions seem IMO the best option

**Comment by whot** [comment]
cc @jimmac

**Comment by Hjdskes** [comment]
In progress in #36; please move the discussion there.
