### ISSUE TITLE
Piper wont find Mouse

### ISSUE THREAD

**Issue by ThanosPlanetSmasher** [libratbag/piper#313]
Hey All, I'm a new user to Linux (Mint) and I am at my wits end trying to get Libratbag and Piper to work. So far I have installed both from the PPA, Ratbag is rooted and running, but Piper just will not see it. I have enabled the ratbagd.service in the terminal and my mouse is definitely supported (G602)

**Comment by tethragon** [comment]
Linux mint's software manager just updated piper. Try the update and see if it works now.

**Comment by whot** [comment]
Try running `ratbagctl list` and see if that shows anything. If it shows your device, it's probably a version mismatch between piper and libratbag, you need piper 0.2.904 and libratbag 0.9.905.

If `ratbagctl` complains, it's a libratbag issue, something is off with the ratbagd install.

If `ratbagctl` doesn't complain but doesn't show your device, it's a libratbag issue too, we'll need the `ratbagctl -vvv list` output attached to an issue in libratbag.

Meanwhile, closing this one because I'm 99% sure it's just the version mismatch.

**Comment by ThanosPlanetSmasher** [comment]
![image](https://user-images.githubusercontent.com/48135859/53815999-052f4c80-3f20-11e9-8af9-3d05827107b7.png)
This is the list output.  Looks like it doesnt see my device. 

I'm sure you get this a million times, but I'm pretty new to Linux so Im learning as I go.

**Comment by ThanosPlanetSmasher** [comment]
[cid:mcid-598d1030-20c6]

This is my output from the List command.

Am I missing something?  I am new to Linux and I'm learning as I go, so I apologize if its something I missed installing or another newb mistake.

Thanks!

Sent from Mailspring<https://link.getmailspring.com/link/8819F7B1-A9A8-4325-8868-7AA74B8A8D4B@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDJkZTdlYjMwNTU5OWZjNThmZjA4ODRkMTk3ZjU5NzM2ODZkZTVmNDAwZWY3NGY1OTJjZjAwMDAwMDAxMTg5NDE3OWE5MmExNjljZTE4Y2Y0YWQ3QHJlcGx5LmdpdGh1Yi5jb20%3D>, the best free email app for work
On Mar 3 2019, at 3:30 pm, Peter Hutterer <notifications@github.com> wrote:
Try running ratbagctl list and see if that shows anything. If it shows your device, it's probably a version mismatch between piper and libratbag, you need piper 0.2.904 and libratbag 0.9.905.

If ratbagctl complains, it's a libratbag issue, something is off with the ratbagd install.

If ratbagctl doesn't complain but doesn't show your device, it's a libratbag issue too, we'll need the ratbagctl -vvv list output attached to an issue in libratbag.

Meanwhile, closing this one because I'm 99% sure it's just the version mismatch.

**Comment by ThanosPlanetSmasher** [comment]
![image](https://user-images.githubusercontent.com/48135859/53834986-97981600-3f49-11e9-8643-a634b1801809.png)
I am using the latest version of both Piper and Ratbag to my knowledge

**Comment by whot** [comment]
right, you still have piper 0.2.902 which isn't compatible with the 905 ratbag. You'll need piper 0.2.904 which isn't available in the PPA yet for some reason, cc @muzena

**Comment by tethragon** [comment]
It is available. My software manager (Linux mint 19.1) updaded piper a couple of days ago to ver. 0.2.904

**Comment by whot** [comment]
The PPA we link to and that is used in the screenshots above still references 902: https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git, not sure where Mint gets it from.

**Comment by ThanosPlanetSmasher** [comment]
Can I just install 0.2.904 without the PPA?  No matter what I do or update, apt-cache still churns out Version 0.2.902.0

**Comment by tethragon** [comment]
> Can I just install 0.2.904 without the PPA? No matter what I do or update, apt-cache still churns out Version 0.2.902.0

Just install it no matter what software center says. Then run it and click "about". It will be 0.904

**Comment by ThanosPlanetSmasher** [comment]
[cid:mcid-04ad767c-c28e]

This is my latest error message.  :(

I love what this app would offer, but I just dont think its going to work for me.

Thanks for the help though.

Sent from Mailspring<https://link.getmailspring.com/link/E5AB0605-B692-4A76-874B-2825CC193245@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDJkZTdlYjMzZjE4YmZkZTM1MGEyNjdkMjE4ZDM3ZDdkODhkMDhmZGI2ODg1MjI3OTJjZjAwMDAwMDAxMTg5YTYzOTQ5MmExNjljZTE4Y2Y0YWQ3QHJlcGx5LmdpdGh1Yi5jb20%3D>, the best free email app for work
On Mar 8 2019, at 10:08 am, tethragon <notifications@github.com> wrote:
Can I just install 0.2.904 without the PPA? No matter what I do or update, apt-cache still churns out Version 0.2.902.0
Just install it no matter what software center says. Then run it and click "about". It will be 0.904

**Comment by muzena** [comment]
@ThanosPlanetSmasher 
try Install from this older [PPA](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/ratbag-piper-nightly)

**Comment by muzena** [comment]
@ThanosPlanetSmasher 
Try now install I updated piper version.

**Comment by ArjunSahlot** [comment]
![image](https://user-images.githubusercontent.com/44180430/101299549-7b449f80-37e7-11eb-84a6-251325e9e58a.png)
I still can't find my M720 mouse. It is connected to my computer.

**Comment by ferlanero** [comment]
Same error here with a Logitech M705 "Piper cannot find any devices" while, as it is said in documentation, Logitech M705 is supported by ratbag.

I'm trying in Ubuntu 20.04.1

![Captura de pantalla de 2021-01-11 12-14-13](https://user-images.githubusercontent.com/1192395/104173770-8d2cea00-5406-11eb-8e50-e4fcf4233d4a.png)

**Comment by darshan527** [comment]
> Same error here with a Logitech M705 "Piper cannot find any devices" while, as it is said in documentation, Logitech M705 is supported by ratbag.
> 
> I'm trying in Ubuntu 20.04.1
> 
> ![Captura de pantalla de 2021-01-11 12-14-13](https://user-images.githubusercontent.com/1192395/104173770-8d2cea00-5406-11eb-8e50-e4fcf4233d4a.png)

I had the same issue, so I downloaded the device file from the repository and saved it to `/usr/share/libratbag/`. That worked for me.

**Comment by darshan527** [comment]
@ArjunSahlot I had the same issue, so I downloaded the device file from the repository and saved it to `/usr/share/libratbag/`  That worked for me.

**Comment by ferlanero** [comment]
> @ArjunSahlot I had the same issue, so I downloaded the device file from the repository and saved it to `/usr/share/libratbag/` That worked for me.

What repository do you mean? Can you point to its URL, please?

**Comment by ferlanero** [comment]
> @ArjunSahlot I had the same issue, so I downloaded the device file from the repository and saved it to `/usr/share/libratbag/` That worked for me.

I think you mean this repository: [](https://github.com/libratbag/libratbag/tree/master/data/devices)

**Comment by ferlanero** [comment]
But after replacing old .device file with the new one from the repository above, still no luck:

![Captura de pantalla de 2021-05-04 16-51-11](https://user-images.githubusercontent.com/1192395/117023250-36bb2280-acf9-11eb-9b05-99b76baef8b7.png)

**Comment by alxtrtw** [comment]
What worked for me:
I tried doing the commands suggested in [](https://github.com/libratbag/libratbag/issues/1000#issuecomment-657194129):
```
$ sudo pkill ratbagd
$ sudo ratbagd --verbose
```
And the logs showed that there were no files found for my mouse.

After that I also replaced the device file in `/usr/share/libratbag/` with the one found in [](https://github.com/libratbag/libratbag/tree/master/data/devices) as suggested above. Killing and rerunning ratbagd after that fixed everything.

**Comment by ferlanero** [comment]
> What worked for me: I tried doing the commands suggested [here](https://github.com/libratbag/libratbag/issues/1000#issuecomment-657194129):
> 
> ```
> $ sudo pkill ratbagd
> $ sudo ratbagd --verbose
> ```
> 
> And the logs showed that there were no files found for my mouse.
> 
> After that I also replaced the device file in `/usr/share/libratbag/` with the one found in https://github.com/libratbag/libratbag/tree/master/data/devices as suggested above. Killing and rerunning ratbagd after that fixed everything.

Replacing advised file, still no luck: "ratbag error: libratbag bug: Logitech M705: invalid dpi list"

**Comment by loc85pro** [comment]
### Maybe issue is incorrect **DeviceMatch** value in config file that located at "/usr/share/libratbag/"

This is my solution for my Logitech102:

1. **Trying to find usb port's address in my laptop** => run in terminal `sudo lsusb`
You probably saw results like this

> root@laptop:/home/pxl# lsusb
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 001 Device 005: ID 0bda:5675 Realtek Semiconductor Corp. Integrated_Webcam_HD
> Bus 001 Device 004: ID 27c6:5301 Shenzhen Goodix Technology Co.,Ltd. Fingerprint Reader
> Bus 001 Device 003: ID 258a:002a SINO WEALTH Keyboard
> Bus 001 Device 006: ID 0cf3:e009 Qualcomm Atheros Communications 
> Bus 001 Device 002: ID 046d:c09d Logitech, Inc. G102 LIGHTSYNC Gaming Mouse
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

2 . **Edit file is named same with name of your mouse.** 
Example: I have know that my mouse connecting on `046d:c09d ` by above result `Bus 001 Device 002: ID 046d:c09d Logitech, Inc. G102 LIGHTSYNC Gaming Mouse`. => In file `/usr/share/libratbag/logitech-g102-g203.device`, change `DeviceMatch` value to `usb:046d:c09d`
Note: You can edit file with nano comand (or not) :D
3. Restart piper for **Done**

**Note:** Iam using Ubuntu 22.04.2

**Comment by staticssleever668** [comment]
Note: in case of G102, this will be fixed in the upcoming libratbag and Piper releases (https://github.com/libratbag/libratbag/pull/1389).

**Comment by DiracSpace** [comment]
> What worked for me: I tried doing the commands suggested [here](https://github.com/libratbag/libratbag/issues/1000#issuecomment-657194129):
> 
> ```
> $ sudo pkill ratbagd
> $ sudo ratbagd --verbose
> ```
> 
> And the logs showed that there were no files found for my mouse.
> 
> After that I also replaced the device file in `/usr/share/libratbag/` with the one found in https://github.com/libratbag/libratbag/tree/master/data/devices as suggested above. Killing and rerunning ratbagd after that fixed everything.

I have the Logitech G203 and this fixed my issue. Although the image appears with 404 but it doesn't affect the rest of the functionality.

**Comment by Christiancoding** [comment]
Any fixes? I still have the problem on version 0.7 on Ubuntu.
