### ISSUE TITLE
Mouse doesn't remember DPI settings.

### ISSUE THREAD

**Issue by nrayamajhee** [libratbag/piper#330]
Excellent software. Just the thing I was looking for after I bought my MX Anywhere S2.

However, I have run into this issue where if I change the DPI to say 2400 then turn the mouse off and turn in back on, the DPI is reset to 1000. Although piper doesn't show it, I can feel the change and if I restart ratbadg.service, piper will correctly display that it is indeed 1000.

Am I missing something here. I am running the `piper-git` package via `AUR` in Arch linux. And I have enabled and started `ratbadg.service`. Isn't there a way to make the dpi changes persistent. I do want to be able to turn off my mouse when not in use.

**Comment by whot** [comment]
IIRC it's an issue with that particular mouse, it resets when it goes to sleep or is turned off. libratbag would have to re-apply the settings on wakeup but those hooks aren't in place yet. Either way, this is a libratbag bug, please file the issue there. Piper is merely a pretty UI to libratbag's DBus interface but doesn't handle anything with the mouse directly.

**Comment by QazCetelic** [comment]
I'm still having this issue.

**Comment by nrayamajhee** [comment]
@QazCetelic Seems like this case is specific to Logitech MX series. Since we don't have official drivers, the mouse doesn't get the proper dpi setting from the host(OS) itself. So instead I setup this udev rule to set dpi everytime there's a power event for this mouse. It still doesn't work sometimes when the mouse goes to sleep. But in that case, I manually turn it off and on to trigger this rule:

`/etc/udev/rules.d/90-mx-anywhere-on.rule`
```
ACTION=="change"\
, SUBSYSTEM=="power_supply"\
, ENV{POWER_SUPPLY_MODEL_NAME}=="Wireless Mobile Mouse MX Anywhere 2S"\
, ENV{POWER_SUPPLY_ONLINE}=="1"\
, ENV{POWER_SUPPLY_STATUS}=="Discharging"\
, RUN+="/usr/bin/su root -c 'ratbagctl Logitech\ MX\ Anywhere\ 2S dpi set 4000'"
```

Run this command to verify that your computer detects mouse power events:

`udevadm monitor --environment --udev`

If you see the mouse power supply setting displayed when you turn the mouse off/on, then the above rule should start doing its job. 

Arch linux has more info for wiriting udev rules: https://wiki.archlinux.org/index.php/Udev.

**Comment by QazCetelic** [comment]
Thanks

**Comment by QazCetelic** [comment]
I'll try if it works now

**Comment by rogelioamancisidor** [comment]
@QazCetelic  I want to create a udev rule for this command `ratbagctl singing-gundi button 7 action set button 3`, which works fine when written in the terminal. I followed your above example (but with my ratbagctl command), but it doesnt work. How do I find the `POWER_SUPPLY_MODEL_NAME` env variable in my case? I also notice that you use `\` in your ratbagctl command, why is that?

**Comment by rogelioamancisidor** [comment]
@nrayamajhee  The output in my case does not show any `change` action, just `add`, `bind` and `remove`. I have tried to use an `add` and `bind` action, together with some of their env variables, but I didnt succeed.

**Comment by nrayamajhee** [comment]
I don't mean to divert you guys from the problem at hand, but if it's just about swapping buttons and not configuring logitech (e.g. setting dpi), you can use xbindkeys. 

Here's a tutorial:
<http://xahlee.info/linux/linux_xbindkeys_tutorial.html>

More info here:
<https://wiki.archlinux.org/title/Xbindkeys>

If you have `xautomation` package (`xte` command) in whatever linux you're using, then you can even map button to keypresses very easily. Here's my configuration to map extra buttons to PageUp/Down:
<https://github.com/nrayamajhee/dotfiles/blob/master/.xbindkeysrc>

I hope this helps.

However, I should say that the udev rule should still work. I am not an expert by any means, but I think a suitable `ACTION`, not necessarily `change` should do it. My rules on my mouse (MX Anywhere) doesn't work when the mouse sleeps after inactivity. I have to manually turn it off and on to trigger it.

Also, we should discuss this here: https://github.com/libratbag/libratbag/issues/596
Since applying settings during mouse power events is a feature that we want in ratbagd, its not really an issue with piper.

**Comment by rogelioamancisidor** [comment]
I finally manage to create the udev rule for my mouse that it is connected via bluetooth. Here it is, in case anybody else has the same problem, 

`ACTION=="add"\
, SUBSYSTEM=="bluetooth"\
, ATTR{idVendor}=="hci0"\
, ATTR{idProduct}=="3585"\
, RUN+="/usr/bin/su root -c 'ratbagctl M720\ Triathlon button 7 action set button 3'"`

**Comment by rogelioamancisidor** [comment]
I have tried to replicate the above udev rule in a difference pc and it is not working. If I just run `ratbagctl M720\ Triathlon button 7 action set button 3` from the terminal it works fine (so `ratbagctl` works fine). What can it be now?

**Comment by BloodyIron** [comment]
I'm having the same issue where whenever I unlock my computer, or stuff like that, my G604 goes back to some sort of DPI that's way lower than what it was last set to.

Can we please have this re-opened and a permanent solution implemented? This is really obnoxious, and is specific to Linux, as this doesn't happen in Windows.

**Comment by PadTrick** [comment]
have the same issue, with a logitech g203.
after every reboot, shutdown, sleep etc. the DPI is changed back to the default low dpi setting.
anyone found a working fix/workaround ?

**Comment by BloodyIron** [comment]
Still happening for me... It's incredibly frustrating. It happens 100% of the time for me.

**Comment by vanlueckn** [comment]
Yes for me too
