### ISSUE TITLE
Piper package for opensuse (Tumbleweed) not up-to-date

### ISSUE THREAD

**Issue by germangoergs** [libratbag/piper#331]
Hello guys,

Piper is shown in Suse repo as 904, but is 903 and therefore not usable, since it's not compatible to ratbagctl 905.

It would be cool if the repo could be updated. :)

Thanks in advance!
Cheers!

**Comment by whot** [comment]
please file a bug with suse, we have no influence on the distribution packages (other than Fedora for which I am the maintainer for)

**Comment by germangoergs** [comment]
Well, it was updated now. so thanks. :D
