### ISSUE TITLE
DEB/PPA please?

### ISSUE THREAD

**Issue by BloodyIron** [libratbag/piper#333]
Any chance we can get deb packaging or a PPA for piper? Compiling from source really is not congruent to a good package manager ecosystem, and really many gamers are not good at compiling code, let alone knowing where to begin.

Plus, if we can get a PPA or deb packages going on, we can increase usage and help gaming on Linux grow!

libratbag is already in the main ubuntu repos.

Is this possible? Please?

**Comment by whot** [comment]
See the [installation](https://github.com/libratbag/piper/wiki/Installation) wiki page, it has the link to the recommended PPA.

Distribution-specific packaging is up to the devs of that distribution, we don't include that in the repo.

**Comment by BloodyIron** [comment]
Oops sorry about that! I looked for it and must have missed it D:
