### ISSUE TITLE
Executing commands and not just keystrokes?

### ISSUE THREAD

**Issue by ghost** [libratbag/piper#336]
Is this possible? I've been trying to get my g502 to work with i3 but i'm not sure if it's the software or me.
Further looking into this, it seems that piper does not record things like ctrl and meta keys?

**Comment by Simon-Laux** [comment]
In theory it could be possible to set the the buttons to otherwise "unused" keys like `F13` - `F24` that you can then map to macros.

**Comment by Hjdskes** [comment]
@whot Is this something that can be done?

> Further looking into this, it seems that piper does not record things like ctrl and meta keys?

Ctrl should definitely work, but it depends on your window manager / compositor. What keys are you trying to bind, and under which window manager or compositor?

**Comment by whot** [comment]
you could set things to f13 and above, the keymap for those is available by default in X. Only problem is: the keystroke recording in piper requires you to press those keys...

**Comment by whot** [comment]
closing because the way the stack works it's not directly possible in piper. The mouse hw which we program through piper+ratbagd can only send key strokes. And what those strokes do in the end is up to everything else in the stack.
