### ISSUE TITLE
UI should update when the active resolution is changed behind Piper's back

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#340]
As mentioned in #339: when the active resolution changes behind Piper's back (e.g. through a button on the device, or ratbagctl) this change should be reflected in Piper.

**Comment by stephanlachnit** [comment]
I think this is in fact a libratbag problem. We already have a DBus signal if the active resolution changed, but it's not emitted by libratbag if the device changes it.

**Comment by staticssleever668** [comment]
Piper now listens to updates on the D-Bus: #856

> through a button on the device

This sounds complicated, as we would need another event loop on libratbag side to listen for incoming USB HID packets. Either way, this depends on libratbag, if implemented, it will just send the updates through D-Bus.
