### ISSUE TITLE
Piper crashes immediately with No module named 'piper'

### ISSUE THREAD

**Issue by lavadrop** [libratbag/piper#341]
Hi, I just installed Ubuntu Budgie 19.04 and somehow my Logitech G600 suddenly stopped recognizing some buttons. I then searched and found your utility. However I can't use it. I took a look at #66 and all I get is:
```
python3 -c "import sys; print('\n'.join(sys.path))"

/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages

python3 -c "import sysconfig; print(sysconfig.get_path('purelib'));"

/usr/lib/python3.7/site-packages

PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6/site-packages piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'
```

**Comment by Dinozilla** [comment]
I am having this problem too, I think it is from Ubuntu 19.04 because before when I had ubuntu 18.04 it started fine, but after upgrading I get the exact same problem as you. Hopefully it can be fixed soon.

**Comment by Helios747** [comment]
Run this:

`PYTHONPATH=$PYTHONPATH:/usr/lib/python3.7/site-packages piper`

**Comment by jhakonen** [comment]
Looks like the deb-package creates a symbolic link that points to wrong location:
```
$ ll /usr/lib/python3/dist-packages/piper
lrwxrwxrwx 1 root root 38 Apr 25 21:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.6/site-packages/piper
$ ll /usr/lib/python3.6/site-packages/piper
ls: cannot access '/usr/lib/python3.6/site-packages/piper': No such file or directory
```
The link's target should be `/usr/lib/python3.7/site-packages/piper`.
Here's alternative way to fix this:
`$ sudo ln -nsf /usr/lib/python3.7/site-packages/piper /usr/lib/python3/dist-packages/piper`

**Comment by whot** [comment]
Is this the real debian package or the PPA?

**Comment by jhakonen** [comment]
PPA in my case. Not sure what you mean by real debian package.

**Comment by whot** [comment]
wasn't there an official debian package at some point? I'm probably misremembering. Either way, it's a packaging issue, nothing we can do here as the upstream, cc @muzena though.

**Comment by muzena** [comment]
I Will test it in Ubuntu 19.04, in 18.04 I don't have any problems.
@jhakonen 
Which distribution/version do you have?

**Comment by jhakonen** [comment]
Here's mine:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

**Comment by NoxNebula** [comment]
I installed piper via ppa on Ubuntu 19.04, it crashes immediately:
```
$ piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'
```
and when trying pythonpath:
```
$ PYTHONPATH=$PYTHONPATH:/usr/lib/python3.7/site-packages piper
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3.7/site-packages/piper/window.py", line 69, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3.7/site-packages/piper/window.py", line 147, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.7/site-packages/piper/mouseperspective.py", line 90, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3.7/site-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/usr/lib/python3.7/site-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/usr/lib/python3.7/site-packages/piper/mousemap.py", line 111, in __init__
    svg_bytes = get_svg(ratbagd_device.model)
  File "/usr/lib/python3.7/site-packages/piper/svg.py", line 32, in get_svg
    if model.startswith('usb:') or model.startswith('bluetooth:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
it doesn't want to start both ways, I get the same issue when I built it myself. Help.

**Comment by muzena** [comment]
@jhakonen  @NoxNebula 
You can try now, I test it in 19.04 and it work for me.

**Comment by NoxNebula** [comment]
@muzena I tested it 6 hours ago on a fresh Ubuntu 19.04 install and it didn't work. Does the PPA got an update in the meantime? Because the git repository didn't.

**Comment by jhakonen** [comment]
Yep, the PPA works for me too, thank you :)

**Comment by fllaryora** [comment]
> Looks like the deb-package creates a symbolic link that points to wrong location:
> 
> ```
> $ ll /usr/lib/python3/dist-packages/piper
> lrwxrwxrwx 1 root root 38 Apr 25 21:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.6/site-packages/piper
> $ ll /usr/lib/python3.6/site-packages/piper
> ls: cannot access '/usr/lib/python3.6/site-packages/piper': No such file or directory
> ```
> 
> The link's target should be `/usr/lib/python3.7/site-packages/piper`.
> Here's alternative way to fix this:
> `$ sudo ln -nsf /usr/lib/python3.7/site-packages/piper /usr/lib/python3/dist-packages/piper`

That fix my problem !!  Thank you Janne Hakonen

**Comment by muzena** [comment]
@denciu 
which version of Python has Ubuntu 21.04 3.8 or 3.9?

**Comment by denciu** [comment]
@muzena 
``` 
$ python3 -V
Python 3.9.4

**Comment by muzena** [comment]
@denciu 
Try now install from PPA, I add symlinking for [python 3.9](https://git.launchpad.net/~libratbag-piper/piper/+git/piper-packaging/commit/?id=bbc627c80e11cfd98535a00b7358c8c56986bbde).

**Comment by danielalejandrin** [comment]
> > Looks like the deb-package creates a symbolic link that points to wrong location:
> > ```
> > $ ll /usr/lib/python3/dist-packages/piper
> > lrwxrwxrwx 1 root root 38 Apr 25 21:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.6/site-packages/piper
> > $ ll /usr/lib/python3.6/site-packages/piper
> > ls: cannot access '/usr/lib/python3.6/site-packages/piper': No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The link's target should be `/usr/lib/python3.7/site-packages/piper`.
> > Here's alternative way to fix this:
> > `$ sudo ln -nsf /usr/lib/python3.7/site-packages/piper /usr/lib/python3/dist-packages/piper`
> 
> Just tried it out on Ubuntu 21.04 and worked under python 3.8. For those who wish to copy/paste:
> `$ sudo ln -nsf /usr/lib/python3.8/site-packages/piper /usr/lib/python3/dist-packages/piper`

This works for me in Ubuntu 20.04

**Comment by gregor3000** [comment]
This is still open for 18.04 LTS in the PPA the site points to. this resolves it:
`sudo ln -nsf /usr/lib/python3.6/site-packages/piper /usr/lib/python3/dist-packages/piper`

it launched the application, but unfortunately my generic mouse is incompatible it seems.

**Comment by pipes80-collab** [comment]
i have the same problem but it seems that the command for symbolic link is not working, my Piper on arch is in the Python 3.10 folder but there is no way to use that link and it is in detached and not site-packages

**Comment by egyas** [comment]
> Looks like the deb-package creates a symbolic link that points to wrong location:
> 
> ```
> $ ll /usr/lib/python3/dist-packages/piper
> lrwxrwxrwx 1 root root 38 Apr 25 21:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.6/site-packages/piper
> $ ll /usr/lib/python3.6/site-packages/piper
> ls: cannot access '/usr/lib/python3.6/site-packages/piper': No such file or directory
> ```
> 
> The link's target should be `/usr/lib/python3.7/site-packages/piper`. Here's alternative way to fix this: `$ sudo ln -nsf /usr/lib/python3.7/site-packages/piper /usr/lib/python3/dist-packages/piper`

This ... FOR THE WIN!  Thank you sir!  :)

**Comment by gssj85** [comment]
Nothing makes it work here in 22.04 :/

**Comment by whot** [comment]
> Nothing makes it work here in 22.04 :/

Check where the module is installed, `meson install` will list all files installed and meson keeps a log of installed files somewhere in the builddir too. If the package comes from a PPA, the deb file will have the list and can be queried with `dpkg`, don't know the command off-hand though.

Piper needs to be installed as `/usr/lib/python3.X/site-packages/piper` where `X` is your python minor version (`python --version`). If the `piper` module is not there, python won't find it and you need to either add the respective `..../site-packages` directory (NOT the `piper` directory) to `$PYTHONPATH` or fix the install so it installs in the right path.
