### ISSUE TITLE
Logitech G600 G-Key Can't be set to CTRL, SHIFT, or ALT

### ISSUE THREAD

**Issue by SpencerXZX** [libratbag/piper#342]
Like the title says, Logitech G600 G-key (The third mouse button on far right of mouse) can't be set to send keystrokes SHIFT, ALT, or CTRL. This is a big problem for me because I use this key to shift modify other keys by assigning SHIFT keystroke to the button. I am using Manjaro and cannot do this. It looks like it sets it in Piper but when I press the key, instead of shift, it outputs a "1" keystroke instead.

**Comment by Madserge11** [comment]
I am getting the same problems as well, wish i had a solution for ya

**Comment by SmurgBurglar** [comment]
same

**Comment by Madserge11** [comment]
> Like the title says, Logitech G600 G-key (The third mouse button on far right of mouse) can't be set to send keystrokes SHIFT, ALT, or CTRL. This is a big problem for me because I use this key to shift modify other keys by assigning SHIFT keystroke to the button. I am using Manjaro and cannot do this. It looks like it sets it in Piper but when I press the key, instead of shift, it outputs a "1" keystroke instead.

Hey I mentioned this issue thats linked to the piper project in libratbag there is a temp solution https://github.com/libratbag/libratbag/issues/710 check it out here and scroll down to the end and read ctchikmo's post it seem to be a decent one that might help out

**Comment by staticssleever668** [comment]
Since the problem is completely on libratbag side, let's track it there.
