### ISSUE TITLE
Setting profiles externally, or automatic switching

### ISSUE THREAD

**Issue by Pikl** [libratbag/piper#343]
Howdy,

I'd love to be able to have profiles switched automatically when starting up certain programs, is this currently possible somehow? I've looked around a bit and can't find any discussion on the topic.

If not, what would it take to be able to set profiles externally? Or even better - to have Piper detect running processes/focussed window and switch profiles based on that, like how Logitech's application works. 
I'd like to be able to do this myself but I'm a fresh Linux user and not very knowledgable in development with Python or GTK yet, so could really use a pointer in the right direction. 

Thanks for your time.

**Comment by whot** [comment]
piper is the GUI to ratbagd (from libratbag) which is the daemon that controls the device itself. You can use libratbag's `ratbagctl` commandline tool to interact with ratbagd.

> - to have Piper detect running processes/focussed window and switch profiles based on that, like how Logitech's application works.

this is a fair bit of work in X and impossible under Wayland unless the compositor agrees. And flatpaks probably add another layer of difficulty here. Windows simply makes this easier (afaik). Running `ratbagctl` is your best bet atm. Or try to create some working prototype, once you have that we can look at how difficult this would be to integrate into piper.
