### ISSUE TITLE
Doesn't seem to be able to detect wireless mouse

### ISSUE THREAD

**Issue by camdenorrb** [libratbag/piper#344]
Hello, I bought the e-sports edition logitech mouse recently and was wondering if there is any way to either make persistent settings on the mouse or utilize piper without it being wired. Right now if I set my setting on the mouse, they revert over time.

**Comment by whot** [comment]
Piper merely uses libratbag to make the actual changes, so please file any issue that don't affect the actual GUI itself with [libratbag](https://github.com/libratbag/libratbag)
