### ISSUE TITLE
Piper always show "Something went wrong. The device has been reset to previous state"

### ISSUE THREAD

**Issue by shirshendubhowmick** [libratbag/piper#349]
OS: Ubuntu 19.04
Device: Logitech MX Master 2S

Every time i try to apply any settings piper shows error "Something went wrong. The device has been reset to previous state"

![Screenshot from 2019-05-18 17-59-40](https://user-images.githubusercontent.com/12836504/57969631-c80f1e00-7996-11e9-940a-0d5059377710.png)

**Comment by whot** [comment]
Check the journal for any error messages from ratbagd, this should provide a hint at what's going on here.

**Comment by shirshendubhowmick** [comment]
@whot 
Thanks for your reply.
I ran journalctl -u ratbagd.service and posting the screenshot

![Screenshot from 2019-05-22 23-24-39](https://user-images.githubusercontent.com/12836504/58196956-f66b6100-7ce8-11e9-8fdc-a1a60fd660a0.png)

**Comment by whot** [comment]
fwiw the output of journalctl is text, easier to attach or copy/paste the relevant sections than taking screenshots.

Nothing interesting in here though so it doesn't crash at least. Might be worth killing ratbagd and starting it manually with `--verbose` to see if anything useful appears. Either way, this is a [ratbagd/libratbag issue](https://github.com/libratbag/libratbag/issues), let's continue the discussion there.

**Comment by andrefcorreia** [comment]
Problem solved?
