### ISSUE TITLE
Problem installing from source

### ISSUE THREAD

**Issue by kortschak** [libratbag/piper#350]
Following the install instructions in the README fails on Ubuntu 16.04.

```
~/piper [master]$ meson builddir --prefix=/usr/
Error during basic setup:

[Errno 2] No such file or directory: '~/piper/builddir'
```

My guess is that this is a meson version issue. Unfortunately I cannot see what version you are testing against since you are testing on fedora.

However, if I `mkdir builddir` I do get a little further, still failing though.

```
~/piper [master]$ mkdir builddir
~/piper [master]$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.29.0
Source dir: ~/piper
Build dir: ~/piper/builddir
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

What am I missing here?

**Comment by whot** [comment]
> Ubuntu 16.04.

tbh, I don't think we support 16.04, it's too old. So old that it doesn't support the `meson_version` option (which specifies the minimum meson version) we have in the first few lines of the `meson.build` file ;)

**Comment by kortschak** [comment]
Perhaps add minimal meson version in docs somewhere?

**Comment by whot** [comment]
well, it is already in the `meson.build` file. I tend to dislike duplicating docs like this because they often go stale. Anyway, I've added it to the [Installation](https://github.com/libratbag/piper/wiki/Installation) wiki page now.

**Comment by kortschak** [comment]
Thanks
