### ISSUE TITLE
Can't bind button to (just) META

### ISSUE THREAD

**Issue by p4block** [libratbag/piper#352]
On my old mouse, I had set a side button to the windows key on the windows Logitech software.

This worked beautifully in linux and I could click the button to get ie. the app launcher but I could also hold down the key to grab and move windows around.

On Piper, just setting meta causes it to display the "Something went wrong" dialog and it appears as if it doesn't get actually saved.

Looking at my old mouse via piper, the key is set to something along the lines of "down meta, proprietary action, up meta" 

The windows Logitech software appears to be able to save some internal command that tells the mouse to handle the key in a special, not simply a keystroke, way.

**Comment by p4block** [comment]
After more heavy usage of Piper I also found that I am unable to save the profile if I have other keys such as Home, Mail or Tools in the shortcut.

**Comment by FFY00** [comment]
Does this work on `ratbagctl`? I think this is a libratbag issue.

**Comment by vn-ki** [comment]
As a workaround I bound the button to `Ctrl + ~`. When I hold down the button since Ctrl + grave is not bound to anything, it just acts as ctrl modifier. Hope I don't run into any issues with this.

**Comment by foo2k** [comment]
I'm getting the error "Something went wrong The device has been reset to a previous state." every time I try and bind a keystroke. 

I'm using a Logitech MS Anywhere 2 on Fedora 30. 

Any ideas what's causing this?

**Comment by youngstuart** [comment]
Same "Something went wrong..." error when simply setting the button below the wheel to middle-click. Logitech MX 2S, Pop_os.

**Comment by debugrr** [comment]
Same on Logitech MX Master. 

> Same "Something went wrong..." error when simply setting the button below the wheel to middle-click.

On Archlinux

**Comment by ZaLiTHkA** [comment]
I'm battling with the same issue on Zorin 15 with a G502 Hero.. it's more than just an *inconvenience* for me though, since I am physically disabled (my left arm is paralysed) I **rely** on a multi-button mouse for the things that other fully-able-bodied people do without thinking, such as `ctrl + click`, `shift + click`, `ctrl + pgup`, `ctrl + pgdn`, etc..

I've booted into Windows and configured a single default profile, stored on the mouse itself, and in Windows 10 it works perfectly.. but when I boot into Linux, I cannot use any of the modifier keys (with `ctrl`, `alt` and `shift` assigned to my left 3 thumb buttons).

fair warning: I'm not too familiar with Python (full stack JS dev over here), so I'm not sure I would be able to do much myself, but I'm more than willing to dig into it myself with some guidance... if someone is willing to help?

so, how much work is involved in resolving this issue then?

**Comment by okand** [comment]
Probably related issue over in the libratbag repo: https://github.com/libratbag/libratbag/issues/1205

**Comment by ygurin** [comment]
A temporary workaround use [this application](https://github.com/sezanzeb/input-remapper) to bind (inject) the key that you want for the mouse, see [this]( https://i.imgur.com/509ZFoZ.png).

**Comment by AlexandrosFerles** [comment]
> About one year later I encountered the same problem. If you still have not solved it, or for whoever finds this in the future, here is how:
> 
> 1. Installed `xdotool`. It is a CLI tool that returns a keystroke (or any combination for that matter).
> 2. Created a shortcut in settings (gnome in my case) for a key combination that I will never use (eg Ctrl+Alt+9) with the command `xdotool key --clearmodifiers Super_L`
> 3. Bind the same shortcut (eg Ctrl+Alt+9) with piper
> 4. It works
> 
> I know that it is the least ideal way to do it but it gets the job done.

Can you elaborate in how to do this? I have the exact same problem with a Logitech 502 but it the exact steps are unclear to me.

**Comment by okand** [comment]
I think they mean the following:

- Go to Settings > Keyboard > View and Customise Shortcuts > Custom Shortcuts > Add Shortcut
- Set it to something you'll never press on the keyboard, such as ctrl+alt+9 in the quoted example
- Use `xdotool key --clearmodifiers Super_L` as the command for your custom shortcut
- Open Piper and remap the button on your mouse to press ctrl+alt+9

**Comment by AlexandrosFerles** [comment]
@okand thanks for the clarification, that worked exactly as expected!

**Comment by Tywacol** [comment]
> A temporary workaround use [this application](https://github.com/sezanzeb/input-remapper) to bind (inject) the key that you want for the mouse, see [this](https://i.imgur.com/509ZFoZ.png).

Thanks! It worked for me even inside Wine. I was able to map Control_L to one of my logitech mouse buttons.

**Comment by staticssleever668** [comment]
This is a libratbag problem https://github.com/libratbag/libratbag/issues/1205
