### ISSUE TITLE
Logitech M535

### ISSUE THREAD

**Issue by EthanDarling8** [libratbag/piper#355]
I was looking through the list of supported devices and noticed that the Logitech M535 isn't on the list. It is a wireless Bluetooth mouse and it isn't really for gaming, mostly just daily use. Are there any plans to support this mouse or a direction I can take to help it get supported? Thanks!

**Comment by whot** [comment]
Please see [the FAQ](https://github.com/libratbag/piper/wiki/FAQ#does-piper-support-my-device)

Most of the modern Logitech mice use HID++2.0, `hidpp20` in libratbag-speak. Check the [libratbag wiki](https://github.com/libratbag/libratbag/wiki/Adding-a-device) and [find a device](https://github.com/libratbag/libratbag/tree/master/data/devices) that has the hidpp20 driver already assigned, then use that as blueprint.
