### ISSUE TITLE
Piper won't update, can't remove it, can't reinstall it.

### ISSUE THREAD

**Issue by TacoRaptor67** [libratbag/piper#357]
Few days ago I got an update for Piper, and it failed. 
![Screenshot_20190621_121439](https://user-images.githubusercontent.com/46816918/59936661-91597700-941e-11e9-8d78-b13ed5b8f731.png)
After hitting close, my Update Manager shows this in the "Details" section:
https://paste.ubuntu.com/p/M9QWyZ8wKp/

I tried removing Piper but it tells me it's in an "inconsistent state" and should be reinstalled, but I can't get that to work either, due to it giving me the same error as when trying to update it. What can I do? Also sorry if this isn't posted correctly.. I'm fairly new to Linux, as well as Git.

EDIT: Alright, I figured it out.. removed all files associated with it in /var/lib/dpkg/info and force removed it. Can't understand why it didn't just update like it has before.

**Comment by whot** [comment]
we don't control the ubuntu packaging, sorry. not much we can do here.
