### ISSUE TITLE
Piper shows the cycle button for the G Pro in the resolutions tab

### ISSUE THREAD

**Issue by FFY00** [libratbag/piper#369]
![g-pro-button](https://user-images.githubusercontent.com/11718923/61446764-9e975200-a947-11e9-86cc-0306115d2e9b.png)

**Comment by stephanlachnit** [comment]
The same is true for the G Pro (old). I think this behavior is actually intended (have to check the code but I think there was something like this in there), meaning that all resolution related buttons are shown jn the resolution tab (which makes kinda sense).

**Comment by FFY00** [comment]
I thinks this should only be shown in the buttons tab. @whot what is your opinion?

**Comment by whot** [comment]
yeah, that's intended. See `ResolutionsPage::_init_ui` - piper searches for resolution-related buttons to show them here. makes sense IMO too because it a) points out which buttons affect the resolution and b) makes the display of the graphic useful.
