### ISSUE TITLE
logitech g900 chaos spectum issues

### ISSUE THREAD

**Issue by terroreek** [libratbag/piper#372]
Hi,

A couple of issues since the 0.2.905 update, when I am on wireless my g900 doesn't show up in the piper interface.  I get a 404 error, in the screen shot.  If I revert back to the March 23rd update from flathub it works fine.  The other thing I have notices is the LED for the DPI are not configurable with Piper on either version

0.2.904
![piper-0 2 904-2019-03-23](https://user-images.githubusercontent.com/7308768/61988316-c8a6df00-afed-11e9-98c4-e7762164c888.png)
0.2.905
![piper-0 2 905](https://user-images.githubusercontent.com/7308768/61988318-cc3a6600-afed-11e9-8513-ce48b73d637c.png)
LEDs configuration missing
![piper-missing LED](https://user-images.githubusercontent.com/7308768/61988322-cf355680-afed-11e9-9c29-fa349e0c5976.png)

Running Debian Sid with 0.9.905 of ratbagd.  

Output from "ratbagctl bellowing-paca info"
> bellowing-paca - Logitech USB Receiver
 Number of Buttons: 12
    Number of Leds: 2
Number of Profiles: 5
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi
    1: 1600dpi (default)
    2: 3600dpi (active)
    3: 7500dpi
    4: 12000dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'button 4'
  Button: 6 is mapped to 'button 5'
  Button: 7 is mapped to 'resolution-down'
  Button: 8 is mapped to 'resolution-up'
  Button: 9 is mapped to 'wheel-left'
  Button: 10 is mapped to 'wheel-right'
  Button: 11 is mapped to 'profile-cycle-up'
  LED: 0, depth: rgb, mode: on, color: aa0000
  LED: 1, depth: rgb, mode: on, color: aa0000
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)

**Comment by whot** [comment]
**never** run stock debian packages for libratbag together with the flathub versions, debian doesn't update at the same speed and the APIs are still in flux. Unfortunately, if you're running piper from flathub you will need to run libratbag from git (and yes, I wish there was a way to package libratbag in flatpak). Please do try libratbag 0.9.906, it should work with piper. If not, please re-open the issue and we can go from there.
