### ISSUE TITLE
Incompatible ratbagd API version error

### ISSUE THREAD

**Issue by wylel** [libratbag/piper#379]
I am installing using the PPA on the wiki for Ubuntu 19.04. I did `sudo apt install ratbagd piper` and it installs just fine. `ratbagctl` works just fine, but when I open Piper I get the following error:

Incompatible ratbagd API version (required:1, provided: -1). Please update both piper and libratbag to the latest versions.

If I look, it installs ratbagd 0.9.905 and piper 0.2.904-201907310101 (which is what shows in the PPA is the latest for 19.04) but when I open Piper and go to About Piper, it shows 0.2.905.

**Comment by whot** [comment]
https://github.com/libratbag/piper/wiki/FAQ#piper-complains-about-incompatible-ratbagd-api-version-error

The PPA needs to update to libratbag git for that version of piper to work.

**Comment by wylel** [comment]
So, even though its part of the same repo, I need to compile one from git and install the other from the PPA?

**Comment by whot** [comment]
that's what this PPA already seems to do (libratbag release + piper git). This worked-ish until now except for random segfaults in some cases, now we prevent this with the new API in libratbag. So both have to be either from git or from releases, but no more mix-and-match.

@muzena can you fix this in the PPA please? Thanks

**Comment by EddieEldridge** [comment]
This issue is still not resolved

**Comment by chwba** [comment]
I have the same problem with the flatpak version. Now tried to build it myself but getting the same error. (debian 10)

**Comment by whot** [comment]
flatpak piper is on 0.3, you will need libratbag 0.10. piper should've warned about this during the `meson` stage. 

Just checked the [PPA](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git) and it's still providing stuff from a few weeks back, this needs to be updated before the bug is resolved. I don't know how that PPA is handled (automatically or manually?) but it looks like it stopped building libratbag after it  [failed a build a few weeks back](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git/+build/17279097). Piper keeps rebuilding, libratbag apparently doesn't. That issue has been fixed in libratbag already, so it's really down to the PPA to trigger a rebuild of libratbag to get 0.10 out.

**Comment by chwba** [comment]
How can I install libratbag 0.10 on debian 10? I tried sudo apt install -t buster-backports ratbagd but I can only get 0.9.905

**Comment by bennybenjaman** [comment]
When I run meson builddir --prefix=/usr

I get this issue:

Run-time dependency pygobject-3.0 found: NO (tried pkgconfig and cmake)

meson.build:16:0: ERROR: Dependency "pygobject-3.0" not found, tried pkgconfig and cmake


I have all the dependencies listed above and I am running debian Testing.

**Comment by whot** [comment]
see https://who-t.blogspot.com/2018/07/meson-fails-with-native-dependency-not-found.html, you'll need whatever provides `pygobject-3.0.pc` which is e.g. pygobject3-devel on Fedora, not sure of the debian name.

**Comment by whot** [comment]
FTR, the PPA now has libratbag 0.10 so this issue should be properly resolved.

**Comment by Cris70** [comment]
On openSUSE Tumbleweed I still get this error.
Piper and libratbag versions seem to be OK:
```
~> LANG=C zypper se -s piper libratbag
Loading repository data...
Reading installed packages...

S | Name            | Type    | Version  | Arch   | Repository
--+-----------------+---------+----------+--------+------------------------
  | libratbag-devel | package | 0.10-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
  | libratbag-devel | package | 0.10-1.1 | i586   | openSUSE-Tumbleweed-Oss
  | libratbag-tools | package | 0.10-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
  | libratbag-tools | package | 0.10-1.1 | i586   | openSUSE-Tumbleweed-Oss
  | piper           | package | 0.3-1.1  | noarch | openSUSE-Tumbleweed-Oss
```
What is happening here?

**Comment by whot** [comment]
did you restart after installing ratbagd? I wonder if the old version is still running. Otherwise, check with `d-feet` whether ratbag exports the `APIVersion` property - if not, there's some leftover somewhere.

**Comment by Cris70** [comment]
I just made a discovery while toying with ratbagctl: if I execute ratbagctl with sudo, I get the expected results.

```
~ > ratbagctl list
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2468, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2452, in main
    _r = open_ratbagd(verbose=cmd.verbose)
  File "/usr/bin/ratbagctl", line 2418, in open_ratbagd
    r = Ratbagd(1)
  File "/usr/bin/ratbagctl", line 266, in __init__
    raise RatbagdIncompatible(self.api_version or -1, api_version)
__main__.RatbagdIncompatible: ratbagd API version is -1 but we require 1
```

```
~ >  sudo ratbagctl list
No devices available.
```

Is this expected behavior?

**Comment by Cris70** [comment]
> did you restart after installing ratbagd? I wonder if the old version is still running. Otherwise, check with `d-feet` whether ratbag exports the `APIVersion` property - if not, there's some leftover somewhere.

Yes, it exports the `APIVersion` property.
But - again - I had to launch d-feet as root otherwise it would throw an error while trying to inspect org.freedesktop.ratbag1.

**Comment by whot** [comment]
oh, right, that rings a bell now. There was a bug on suse where the dbus-config they ship doesn't allow talking to ratbagd unless you're in the (iirc) `games` group.

... found it: https://github.com/libratbag/libratbag/issues/802#issuecomment-525754861

**Comment by Cris70** [comment]
Great, thank you @whot !

**Comment by Cris70** [comment]
I was too fast in declaring victory :-(
Adding my user to the games group does not make any difference:
```
~ > groups
users games vboxusers

~ > ratbagctl list
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2468, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2452, in main
    _r = open_ratbagd(verbose=cmd.verbose)
  File "/usr/bin/ratbagctl", line 2418, in open_ratbagd
    r = Ratbagd(1)
  File "/usr/bin/ratbagctl", line 266, in __init__
    raise RatbagdIncompatible(self.api_version or -1, api_version)
__main__.RatbagdIncompatible: ratbagd API version is -1 but we require 1

~ > sudo ratbagctl list
[sudo] password di root:
No devices available.
```

Moreover, even when I launch piper (or ratbagctl) as root, my device is not recognized, even if lsusb shows it (on the 6th line):
```
~ > cat /usr/share/libratbag/logitech-g102-g203.device
# G102 and G203 (USB)
[Device]
Name=Logitech Gaming Mouse G102/G103
DeviceMatch=usb:046d:c084
Driver=hidpp20
LedTypes=logo;side;

~ > lsusb
Bus 009 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 004: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 009: ID 046d:c084 Logitech, Inc. G203 Gaming Mouse
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 008: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 006: ID 0d3d:0040 Tangtop Technology Co., Ltd PS/2 Adapter
Bus 001 Device 005: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

~ > sudo ratbagctl list
No devices available.
```
I am running out of ideas... :-(

**Comment by whot** [comment]
`lsusb` just lists the USB devices, `ratbagd` lists supported devices only. Something must go wrong during setup here, `ratbagd --verbose=raw` should provide some info but that's a separate issue.

I'd try installing ratbag from git with our upstream dbus config file, maybe that fixes the issue. Right now I'm still finger-pointing at the suse config as the source of the problem and making accusatory noises.

**Comment by Cris70** [comment]
Well, looking at ratbagd's output it seems the mouse is recognized:
```
~ > sudo /usr/sbin/ratbagd --verbose=raw
ratbag debug: New device: USB CAT5
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0d3d:0040
ratbag debug: New device: USB CAT5
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0d3d:0040
ratbag debug: New device: Logitech G203 Prodigy Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc084
ratbag debug: Logitech G203 Prodigy Gaming Mouse is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: American Power Conversion Back-UPS XS 950U   FW:925.T2 .I USB FW:T2
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 051d:0002
```
however, ratbagctl (and piper) still insist there's no device available.

**Comment by Cris70** [comment]
Seems a known issue.
See https://github.com/libratbag/libratbag/issues/814 and https://github.com/libratbag/libratbag/issues/808
