### ISSUE TITLE
"Cannot find any devices" with Logitech g502

### ISSUE THREAD

**Issue by marcosroot** [libratbag/piper#388]
I run through the terminal to see if there were any errors, but I didn't get any errors. I also reconnected the mouse, and it didn't work.

$ lsusb
Bus 003 Device 004: ID 046d:c07d Logitech, Inc. G502 Mouse

**Comment by whot** [comment]
does `ratbagctl list` show any devices? if so, what does `ratbactl -vvv info <device name>` say?

**Comment by marcosroot** [comment]
Now it worked. I think the problem is with the mouse: the macros I recorded on it are no longer working most of the time, and sometimes it works again, like now. And I took that to do the test again, and now I can see the mouse when I open the program.

**Comment by Vandool** [comment]
> does `ratbagctl list` show any devices? if so, what does `ratbactl -vvv info <device name>` say?

Hi, I have the same problem.

`ratbagctl` list returns `No devices avaliable.`

**Comment by staticssleever668** [comment]
@Vandool what is the output of `lsusb`?

**Comment by Vandool** [comment]
> @Vandool what is the output of `lsusb`?

Bus 004 Device 002: ID 05e3:0612 Genesys Logic, Inc. Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 008: ID 046d:082d Logitech, Inc. HD Pro Webcam C920
Bus 003 Device 010: ID 046d:c095 Logitech, Inc. G502 X PLUS
Bus 003 Device 006: ID feed:6060 Omkbd ErgoDash rev1.2
Bus 003 Device 005: ID 05e3:0751 Genesys Logic, Inc. microSD Card Reader
Bus 003 Device 004: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 003 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 002: ID 04e8:3301 Samsung Electronics Co., Ltd ML-1660 Series
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 005: ID 0b05:1939 ASUSTek Computer, Inc. AURA LED Controller
Bus 001 Device 004: ID 0b05:190e ASUSTek Computer, Inc. ASUS USB-BT500
Bus 001 Device 003: ID 046d:c547 Logitech, Inc. USB Receiver
Bus 001 Device 002: ID 057c:8503 AVM GmbH FRITZ!WLAN AC 860
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by staticssleever668** [comment]
@Vandool, thanks, can you also provide the output of `lsusb` again but with mouse connected in wired mode (or in wireless mode if this was wired)? 

This is a new mouse model that is not known to libratbag yet. Please, try making a new device file by the following path: `/usr/share/libratbag/logitech-g502-x-plus-wireless.device`; with such contents:

```dosini
[Device]
Name=Logitech G502 X Plus
DeviceMatch=usb:046d:c095
Driver=hidpp20
```

**Comment by Vandool** [comment]
> @Vandool, thanks, can you also provide the output of `lsusb` again but with mouse connected in wired mode (or in wireless mode if this was wired)?
> 
> This is a new mouse model that is not known to libratbag yet. Please, try making a new device file by the following path: `/usr/share/libratbag/logitech-g502-x-plus-wireless.device`; with such contents:
> 
> ```ini
> [Device]
> Name=Logitech G502 X Plus
> DeviceMatch=usb:046d:c095
> Driver=hidpp20
> ```
> 
> Then do `sudo systemctl restart ratbagd.service` and restart Piper.

The last one was wired, this one is wireless:
Bus 004 Device 002: ID 05e3:0612 Genesys Logic, Inc. Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 007: ID 046d:082d Logitech, Inc. HD Pro Webcam C920
Bus 003 Device 006: ID feed:6060 Omkbd ErgoDash rev1.2
Bus 003 Device 005: ID 05e3:0751 Genesys Logic, Inc. microSD Card Reader
Bus 003 Device 004: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 003 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 002: ID 04e8:3301 Samsung Electronics Co., Ltd ML-1660 Series
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 005: ID 0b05:1939 ASUSTek Computer, Inc. AURA LED Controller
Bus 001 Device 004: ID 0b05:190e ASUSTek Computer, Inc. ASUS USB-BT500
Bus 001 Device 003: ID 046d:c547 Logitech, Inc. USB Receiver
Bus 001 Device 002: ID 057c:8503 AVM GmbH FRITZ!WLAN AC 860
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

And I have done what you've suggested but unfortunately the piper still doesn't recognize the device.

Thanks for helping!

**Comment by staticssleever668** [comment]
(removed duplicated comment)

@Vandool 
Seems like for now it should only work in wired mode (because in wireless mode only the receiver is shown, which we don't support yet).
Could you double check that you put the device file into the correct place (it should be a `.device` file along files with the same extension), and try rebooting your PC after that (the service restart should be enough, but just to be sure).

**Comment by Vandool** [comment]
@staticssleever668 

It won't be recognize neither in wired nor in wireless mode.

The file name is `logitech-g502-x-plus-wireless.device`

Just in case I've tried it with piper in AUR as well as flatpak, with restarting the computer. Nonetheless nothing works for me. Running flatpak piper in CL I get this though:
❯ flatpak run org.freedesktop.Piper

(piper:2): Gtk-WARNING **: 17:55:13.537: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 17:55:13.537: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:55:13.537: Failed to load module "canberra-gtk-module"
 
Is something wrong on my side?

**Comment by staticssleever668** [comment]
Please run `sudo killall ratbagd ; sudo ratbagd --verbose` (this will manually first kill and then start the service) and post the output. (Note: to stop the process after that do Ctrl + C in the terminal window where it's running, or do `sudo killall ratbagd` in another terminal).

**Comment by Vandool** [comment]
I have no idea why I can't see the recent comments...

I have done as you've suggested, killing the `ratbagd` and running it again and all, but still no gain = (

**Comment by staticssleever668** [comment]
Huh, that's a.. uhm, an interesting error. Sorry, I don't think I can help you further, that's not something I've seen before...

However I found that an issue for such error has already been opened: libratbag/libratbag#1344.

**Comment by Vandool** [comment]
@staticssleever668 I appreciate your effort! Thanks = )

**Comment by ericshenshs** [comment]
Hi Vandool, I have the same issue with the same output by `sudo ratbagd --verbose | rg G502`.

**Comment by kerren** [comment]
> @Vandool, thanks, can you also provide the output of `lsusb` again but with mouse connected in wired mode (or in wireless mode if this was wired)?
> 
> This is a new mouse model that is not known to libratbag yet. Please, try making a new device file by the following path: `/usr/share/libratbag/logitech-g502-x-plus-wireless.device`; with such contents:
> 
> ```ini
> [Device]
> Name=Logitech G502 X Plus
> DeviceMatch=usb:046d:c095
> Driver=hidpp20
> ```
> 
> Then do `sudo systemctl restart ratbagd.service` and restart Piper.

This worked for me and then I restarted `ratbagd` from @staticssleever668 (https://github.com/libratbag/piper/issues/388#issuecomment-1253932929) and when I opened `piper` again it showed.

**Comment by humbug83** [comment]
A colleague of mine had the same problem.

We created the file, killed the service and restarted it in verbose mode. It shows the name but said it couldn't find any data related to this device.

Funny thing: it shows the id "046d:c099" instead of "046d:c095" so we changed it and restarted the service again and now the mouse was recognized and the dpi settings can be changed (only the logo is missing but i guess thats a fine).
Maybe that help in any way ...

**Comment by tehdango** [comment]
I did this fix also but like @humbug83 said, there is no way to define buttons since the icon is missing. Anyone found a way to fix this?

**Comment by Herschdorfer** [comment]
I have also a g502 x Plus wireless. I also have a different ID:
```
Bus 007 Device 004: ID 046d:c547 Logitech, Inc. USB Receiver
```

but even when i create a config file like:

```
[Device]
Name=Logitech G502 X Plus
DeviceMatch=usb:046d:c547
Driver=hidpp20
```

There is an error during stating of ratbagd

```
~$ sudo ratbagd --verbose
Initializing libratbag
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc547
ratbag debug: Logitech USB Receiver is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 ff 8f 00 18 01 00
ratbag debug:     HID++ error from the device (255): ERR_UNKNOWN (01)
ratbag debug: New device: Microsoft Microsoft® 2.4GHz Transceiver v8.0
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 045e:07b2
ratbag debug: New device: Microsoft Microsoft® 2.4GHz Transceiver v8.0
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 045e:07b2
ratbag debug: New device: Microsoft Microsoft® 2.4GHz Transceiver v8.0
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 045e:07b2
ratbag debug: New device: HP Inc. HP Thunderbolt Dock G4
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 03f0:0488
ratbag debug: New device: SYNA8018:00 06CB:CE67
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 06cb:ce67
DBus server ready
```

**Comment by Herschdorfer** [comment]
Related issue on libratbag

https://github.com/libratbag/libratbag/issues/1488

**Comment by tehdango** [comment]
Have you tried to open piper after? I never ran a debug on start but I can change DPI. The button mapping is missing though.

**Comment by ueberfordert2201** [comment]
I'm having crashes with the following games: War Thunder and Valorant. The games are messing up for me, can the Logitech software cause it to mess up? Freeze system?

**Comment by andrea-nisti** [comment]
> Unfortunately Piper still did not recognise it. But in the linked issues is mentioned kernel 6.6+ is needed.
> 
> Ok in 6.5 OEM. So I guess I need to wait a little.

Hi, any updates about this issue? I am having the same exact problem on fedora bluefin

**Comment by DavidRLTG** [comment]
> I have no idea why I can't see the recent comments...
> 
> I have done as you've suggested, killing the `ratbagd` and running it again and all, but still no gain = (
> 
> However I get this:
> 
> ```
> ❯ sudo ratbagd --verbose | rg G502
> ratbag debug: New device: Logitech G502 X PLUS
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw9'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw8'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw11'.
> ratbag debug: 'Logitech G502 X PLUS' is using protocol v4.2
> ratbag raw: 'Logitech G502 X PLUS' has 33 features
> ratbag error: Profile layout not supported: 0x05.
> ratbag error: Logitech G502 X PLUS: error opening hidraw node (Operation not supported)
> ratbag debug: New device: Logitech G502 X PLUS
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw9'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw8'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw11'.
> ratbag debug: 'Logitech G502 X PLUS' is using protocol v4.2
> ratbag raw: 'Logitech G502 X PLUS' has 33 features
> ratbag error: Profile layout not supported: 0x05.
> ratbag error: Logitech G502 X PLUS: error opening hidraw node (Operation not supported)
> ratbag debug: New device: Logitech G502 X PLUS
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw9'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw8'.
> ratbag debug: Logitech G502 X PLUS is device '/dev/hidraw11'.
> ratbag debug: 'Logitech G502 X PLUS' is using protocol v4.2
> ratbag raw: 'Logitech G502 X PLUS' has 33 features
> ratbag error: Profile layout not supported: 0x05.
> ratbag error: Logitech G502 X PLUS: error opening hidraw node (Operation not supported)
> ```

I have the same mouse and get that last error as well (profile layout not supported).
Any ideas?

**Comment by tehdango** [comment]
Have you tried building ratbag? I believe when you build it, it has more recent fixes than whatever your getting from a package manager. I do have a different version than you so that may also be why mine works.

`❯ sudo ratbagd --verbose | rg G502
ratbag debug: New device: Logitech G502 X
ratbag debug: Logitech G502 X is device '/dev/hidraw5'.
ratbag debug: Logitech G502 X is device '/dev/hidraw6'.
ratbag debug: 'Logitech G502 X' is using protocol v4.2
ratbag raw: 'Logitech G502 X' has 22 features
`
