### ISSUE TITLE
Save profile command as text instead of applying?

### ISSUE THREAD

**Issue by GodOfPlutonium** [libratbag/piper#390]
Is there any way to configure a mouse profile in piper and then save it as a ratbagctl command for later application?

My G502 has 3 profiles of memory. I want to be able to use different sets of profiles on my desktop and off it so I was wondering if there was anyway to automatically save a profile as a ratbagctl command from piper so i can later apply it automatically using a shell script

**Comment by whot** [comment]
There isn't, in part because piper doesn't use ratbagctl but the DBus API directly. You'll have to figure out the script based on ratbagctl yourself, sorry.
