### ISSUE TITLE
Crashes with No Module named 'gi'

### ISSUE THREAD

**Issue by S-B99** [libratbag/piper#395]
Same thing when I run `PYTHONPATH=$PYTHONPATH:/usr/lib/python3.7/site-packages piper`

Installed via the PPA, KDE Neon 5.16.

```
usr@usr-kdeneon:~/Downloads$ which python && which piper
/usr/bin/python
/usr/bin/piper
```
for sanity.

**Comment by whot** [comment]
you need python3-gobject or whatever that package is called on your distribution.

**Comment by S-B99** [comment]
[Output](https://pastebin.com/4ir0B0v2)

**Comment by S-B99** [comment]
pip3 install PyGObject and pycairo, along with `sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 ` doesn't help either, I already have all of it apparently.

**Comment by whot** [comment]
quick test is: `python3 -c 'import gi'` - as long as that fails, piper will too.

`python3-gobject` is the fedora package name, our CI says that Arch calls it `pygobject3-devel`, I guess debian/ubuntu call it something similar. Not sure that's available in pip3 btw since it binds to the native libraries.

**Comment by S-B99** [comment]
It's called PyGObject and still doesn't work :/

**Comment by whot** [comment]
`python-gi-dev` is what you need, apparently. See https://github.com/libratbag/piper/blob/master/.circleci/config.yml#L102

**Comment by S-B99** [comment]
Same thing. Tell me if there's any logs I can provide to help. I think my python install is completely broken at this point tbh. I'll try fixing it as soon as I can and see if it fixed it.

**Comment by whot** [comment]
Dunno how to further debug this tbh. I'd pip remove everything you've installed in the last few days, see if that package alone fixes it and then go from there. Beyond that - I don't know, sorry.

**Comment by gssj85** [comment]
Having the same issue, got this when attempting to install python-gi-dev:

```
The following packages have unmet dependencies:
 libpcre2-dev : Depends: libpcre2-8-0 (= 10.39-3ubuntu0.1) but 10.40-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
                Depends: libpcre2-16-0 (= 10.39-3ubuntu0.1) but 10.40-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
                Depends: libpcre2-32-0 (= 10.39-3ubuntu0.1) but 10.40-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-13ubuntu0.22.04.1) but 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
