### ISSUE TITLE
Enhancement: add a toggle mode

### ISSUE THREAD

**Issue by AnonymousPomp** [libratbag/piper#398]
Like decrease DPI while the right mouse button is pressed and increase it again when its released

**Comment by whot** [comment]
I don't think that's a feature supported by any of the hardware we currently support. It would have to be emulated in software and that's explicitly a non-goal for libratbag at this point.

(note: it's not a piper bug anyway because piper is just the UI for whatever libratbag supports)

**Comment by AnonymousPomp** [comment]
aah  I see

**Comment by bentiss** [comment]
> I don't think that's a feature supported by any of the hardware we currently support.

It's supported on the Logitech mice, with `RATBAG_BUTTON_ACTION_SPECIAL_RESOLUTION_ALTERNATE`.

I *think* piper exports it too, but if the mouse doesn't support it, then there is not much we can do, indeed.

**Comment by AnonymousPomp** [comment]
I'm using logitech G402 and I'll search about it

**Comment by cybarspace** [comment]
@developomp Did you find anything? I want to use the G-button (or whatever it's called) to map extra macros to the keys. Currently I have to load Windows *just* to change a mouse button... :(

**Comment by developomp** [comment]
@cybarspace unfortunately but no. I didn't look for more info after this issue was closed since I didn't use that feature in the first place. I was just experimenting with piper.

**Comment by cybarspace** [comment]
Ah that's a shame. So many buttons... I use i3wm, so I could map some shortcuts to it.
Thank you for the information tho. Much appreciated. 😊
