### ISSUE TITLE
crash due to lack of compatibility with ratbag

### ISSUE THREAD

**Issue by 11111010000** [libratbag/piper#4]
commit ff3730f3fba7dc9e4660fe841097d4f1fe1793e8 in ratbag changed naming convention.

piper/__init__.py line 172 and line 177 contain `description` instead of `name`. Replacing those lines prevents crash if device is not recognized. There might be more examples of such incompatibility in the code.

**Comment by Hjdskes** [comment]
This is fixed in 9a158c7f458c2e41bc29003b4ea7cda14ae9ed14 and 45c669b8ad32a0a03cb6f1a87fb05b725e9104f9, closing.
