### ISSUE TITLE
Missing svg for Logitech MX Ergo

### ISSUE THREAD

**Issue by jehane** [libratbag/piper#413]
The Logitech MX Ergo mouse / trackball is supported by libratbag but the svg is not available in Piper. 
Is it possible to add it ?

**Comment by whot** [comment]
Yes, please send a PR for the SVG to be added (the git history shows plenty of examples here), it's a relatively trivial process.

**Comment by markusressel** [comment]
@whot I'm not sure what you consider "trivial". Although in theory its not that complicated, without much experience I was working approx. 6 hours on the version for the G604 you can see [here](https://github.com/libratbag/piper/pull/415). I don't want to scare people away but be mindful that Inkscape - although a great tool - can be a bitch more often than you might think.

**Comment by whot** [comment]
well, the trivial bit about it is the process: "add svg, add to meson.build, done" :)

the actual process of making the SVG is time-consuming but honestly, there is very little we can do about that bit. or at least nothing I can think of. But your efforts are very much appreciated, thanks!

**Comment by Xoas** [comment]
> The Logitech MX Ergo mouse / trackball is supported by libratbag but the svg is not available in Piper.
> Is it possible to add it ?

Appears in Piper, but no macro can be assigned to the mouse buttons...
Yes, I will make a new pull request with the svg.

**Comment by Xoas** [comment]
#416 Ready

**Comment by xoascf** [comment]
Sorry, wrong account. Svg already in the PR #418

**Comment by stephanlachnit** [comment]
Closed by #418 
/cc @whot
