### ISSUE TITLE
Piper should check a device's capabilities before exposing configuration

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#42]
In #35 I added a check for `RatbagdDevice.CAP_RESOLUTION` and `RatbagdDevice.CAP_LED` before adding the resolutions and led page respectively.

The resolutions page should probably also check for `RatbagdDevice.CAP_SWITCHABLE_RESOLUTION` and only expose the list when it is set, or something like that. @whot What do you think?

**Comment by whot** [comment]
Ignore CAP_SWITCHABLE_RESOLUTION, because that one only indicates it can be switched. I suspect the number of devices that have writable resolutions but not switchable ones is nil. If not, we can deal with it then, but it's not worth thinking about for now.
