### ISSUE TITLE
Buttons page GUI messed up

### ISSUE THREAD

**Issue by chax** [libratbag/piper#425]
I'm running Solus with recent version of piper, built from git hash (6fe74582a6dcfd4bc57bfced853b30e63738f9e9)

GUI for configuring buttons is messed up to a point that it's unusable.
I also tried flatpak version and that one works ok. I also tried changing bunch of system themes, but looks the same on each of them.

Solus package version:
![image](https://user-images.githubusercontent.com/632945/68767648-4f291000-0621-11ea-8093-d98ddd27ade2.png)

Flatpak version:
![image](https://user-images.githubusercontent.com/632945/68767745-8697bc80-0621-11ea-8fa7-197eb17c141d.png)

BTW, you can put Solus on your list of distros that piper ships with: `sudo eopkg it piper`.
Currently i'm the only one with this problem on Solus, at least no-one else confirmed it.
Also, just to point out, there is nothing special in build/package script for piper on Solus to rule this out, so i would like to see what else can i check.

**Comment by whot** [comment]
IIRC there was a broken version of librsvg that triggered issues similar to that, maybe that's the issue?

**Comment by chax** [comment]
i have librsvg 2.46.2

**Comment by whot** [comment]
ok, not the same issue as #233 because you have a newer librsvg than that. Could still be that, but honestly - no-one has the time to work on piper these days beyond basic polish and the occasional release. So this will come down to you debugging it, sorry.

**Comment by chax** [comment]
Solus just updated librsvg to 2.46.3 and this issue is fixed now for me. I will close this issue.

BTW, you can put Solus on your list of supported linux distributions like i mentioned in first comment.
https://github.com/libratbag/piper/wiki/Installation#using-your-distributions-repository

**Comment by whot** [comment]
> BTW, you can put Solus on your list of supported linux distributions like i mentioned in first comment.

done, thanks!
