### ISSUE TITLE
Something went wrong. The device has been reset to previous state!

### ISSUE THREAD

**Issue by thknx** [libratbag/piper#431]
Debian 10
Logitech Mx Master

I have been struggling to run Piper since 6 hours. Tried to uninstall and install again and again a lot of times both with debian distro package manager and github source codes. The error is same everytime: "Something went wrong. The device has been reset to previous state"

[ratbagctl.devel.log](https://github.com/libratbag/piper/files/3901018/ratbagctl.devel.log)
[all.log](https://github.com/libratbag/piper/files/3897352/all.log)

**Comment by dastier** [comment]
The package in Debian Buster is outdated. Only manually built from most recent versions of Piper and ratbag sources worked in my case.

**Comment by thknx** [comment]
> The package in Debian Buster is outdated. Only manually built from most recent versions of Piper and ratbag sources worked in my case.

Yes, I already tried to install from source. Both master branch and version 0.3 but unfortunately result is same.

**Comment by FFY00** [comment]
Can you start the daemon manually with verbosity? Make sure it isn't running first.

```
ratbagd --verbose=raw
```

**Comment by thknx** [comment]
> Can you start the daemon manually with verbosity? Make sure it isn't running first.
> 
> ```
> ratbagd --verbose=raw
> ```

[ratbagd.log](https://github.com/libratbag/piper/files/3924075/ratbagd.log)
![Screenshot from 2019-12-05 00-45-46](https://user-images.githubusercontent.com/47588062/70184429-e05b4600-16f8-11ea-8032-7225344017c8.png)

**Comment by stephanlachnit** [comment]
> debian distro package manager

Do you mean you installed the packages from bullseye ([libratbag](https://packages.debian.org/bullseye/ratbagd), [piper](https://packages.debian.org/bullseye/piper))? I don't see anything wrong with the logs, so maybe you just have missing dependencies. If you haven't tried yet, maybe try to install the packages from bullseye (uninstall and reboot before).

**Comment by thknx** [comment]
> > debian distro package manager
> 
> Do you mean you installed the packages from bullseye ([libratbag](https://packages.debian.org/bullseye/ratbagd), [piper](https://packages.debian.org/bullseye/piper))? I don't see anything wrong with the logs, so maybe you just have missing dependencies. If you haven't tried yet, maybe try to install the packages from bullseye (uninstall and reboot before).

There must be anything wrong with the logs because I see everytime this **cryptic error message** (Something went wrong. The device has been reset to previous state!)

I am using Debian 10 Buster, Just in case I had tried to install with 'apt install' to see what happens. But you know packages in repo are old. So why building from source code is not sufficent to see what is problem?

**Comment by FFY00** [comment]
What are you trying to configure in the mouse. I think key remapping is broken, changing DPI should be working though.

**Comment by stephanlachnit** [comment]
> I am using Debian 10 Buster, Just in case I had tried to install with 'apt install' to see what happens. But you know packages in repo are old. So why building from source code is not sufficent to see what is problem?

That's why I poseted the links for the packages in bullseye, they are up-to-date. You can install them with `sudo apt install -f ./libratbag.deb ./piper.deb` (you can download the `.deb`'s on the links I provided). I thought it could be a dependence issue since you didn't install them except `python3-evdev`.
I guess the message `Something went wrong. The device has been reset to previous state!` is from piper, but piper doesn't have a verbose mode afaik, so that's why it's not in the log I guess. Can you configure the mouse with `ratbagctl`?

**Comment by zjeffer** [comment]
This happens to me when trying to set buttons to the nextsong and previous song macros. The volume up/down macros work fine, but when I set a button to nextsong or previoussong, the settings fail to apply, giving the above error.

Using a G502 Hero SE.

**Comment by stephanlachnit** [comment]
We really need to step up the debug outputs of ratbagd. The raw's are okay, but I doesn't tell what it's trying to do. The last two line are useless output lines, I actually want to replace them. I'm sorry I can't help here, but maybe I will implement proper debug outputs at some point.

**Comment by zjeffer** [comment]
Thanks for the quick reply. Good luck with development :)

**Comment by thknx** [comment]
> What are you trying to configure in the mouse? I think key remapping is broken, changing DPI should be working though.

I am trying to change buttons, if I change DPI the result has no any effect on mouse. I mean value is being changing but, seems there is no any difference.



> > I am using Debian 10 Buster, Just in case I had tried to install with 'apt install' to see what happens. But you know packages in repo are old. So why building from source code is not sufficent to see what is problem?
> 
> That's why I poseted the links for the packages in bullseye, they are up-to-date. You can install them with `sudo apt install -f ./libratbag.deb ./piper.deb` (you can download the `.deb`'s on the links I provided). I thought it could be a dependence issue since you didn't install them except `python3-evdev`.
> I guess the message `Something went wrong. The device has been reset to previous state!` is from piper, but piper doesn't have a verbose mode afaik, so that's why it's not in the log I guess. Can you configure the mouse with `ratbagctl`?

Yes I tried but I can't get ratbagd work properly with these packages. Nevertheless Thank you so much for your help @stephanlachnit 

`ratbagd error: Failed to start ratbagd: Invalid argument`
`m@d:~$ sudo systemctl status ratbagd
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/lib/systemd/system/ratbagd.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-12-13 15:42:59 +03; 7h ago
  Process: 400 ExecStart=/usr/bin/ratbagd (code=exited, status=1/FAILURE)
 Main PID: 400 (code=exited, status=1/FAILURE)

Dec 13 15:42:59 debian systemd[1]: Starting Daemon to introspect and modify configurable mice...
Dec 13 15:42:59 debian ratbagd[400]: ratbagd error: Failed to start ratbagd: Invalid argument
Dec 13 15:42:59 debian systemd[1]: ratbagd.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 15:42:59 debian systemd[1]: ratbagd.service: Failed with result 'exit-code'.
Dec 13 15:42:59 debian systemd[1]: Failed to start Daemon to introspect and modify configurable mice.
`

**Comment by BETLOG** [comment]
Apparently this is still an issue in 2022
Kubuntu 20.04 - because 22.04 has numerous issues that are showstoppers for me personally.
Attempting to bind a macro to a button, or change sensitivity sliders, or probably anything else fails.
Iv'e tried:
- removing piper and libratbag, and installing from the repo.
- installing meson/ninja (including all the ancillary installs: cmake libudev-dev libevdev-dev libsystemd-dev libglib2.0-dev libjson-glib-dev libunistring-dev check valgrind swig) and compiling from git.

I'm not sure what other option there is.
...and yet piper still fails to retain any change I make.

**Comment by Twistx77** [comment]
I have the exact same issue in Kubuntu 22.04. 

Mapping standard functions seems to work. When setting a key macro it fails.

**Comment by BETLOG** [comment]
Mine seems to work now.
Binding 1) single key macro (spacebar) and 2) reverting to default function 
on G502 Hero to buttons normally bound to resolution up and resolution down

Piper Version: 0.6

uname -a
Linux betlogbeast 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by everag** [comment]
This is still broken (or something else did). I installed piper for mapping the Super key to my Logitech G502 Lightspeed's "aim" button, and when trying to do so I get same message.

OS: Nobara 38
Piper 0.7 (flatpak)

**Comment by pernydev** [comment]
Happening to me on Fedora 40 and an MX Master. I get that message on the app and the logs say:
``` ratbagd[257907]: ratbag error: hidpp20: failed to update report rate (-95)
Jun 23 20:04:41 torni ratbagd[257907]: ratbagd error: error committing device (-1000)
```

**Comment by navisayslisten** [comment]
> Running Fedora 40 with Piper 0.7 (flatpak) and Logitech G502 X. Having same errors as above.
> 
> For my case this "worked":
> 
>     * Change report rate to something else than 1000 (could not apply any settings if report rate was 1000)
> 
>     * Bind a "trash" character with the modifier you want. For example, I wanted the "aim" button to work as Control, so I bound it to Ctrl+U. The additional 'U' doesn't interfere with the bindings in the games I play.

Yeah, found that trying to bind an empty Macro (no inputs) was what caused it. Changed to mouse buttons 7-10 I'll never use instead and then it could save

**Comment by pedrom34** [comment]
Thanks @Napuu that did the trick.

**Comment by psychodox** [comment]
Thanks @Napuu I was able to  use the Scroll Lock key instead of a letter, and it worked for me.

> Running Fedora 40 with Piper 0.7 (flatpak) and Logitech G502 X. Having same errors as above.
> 
> For my case this "worked":
> 
> * Change report rate to something else than 1000 (could not apply any settings if report rate was 1000)
> * Bind a "trash" character with the modifier you want. For example, I wanted the "aim" button to work as Control, so I bound it to Ctrl+U. The additional 'U' doesn't interfere with the bindings in the games I play.
