### ISSUE TITLE
The Off page in the LED dialog needs an image

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#45]
It needs an image according to the [empty states](https://developer.gnome.org/hig/stable/empty-placeholder.html.en) guidelines, see also https://wiki.gnome.org/Design/OS/EmptyStates

**Comment by whot** [comment]
I think we can just re-use `/usr/share/icons/Adwaita/scalable/devices/input-mouse-symbolic.svg` here? At least as a temporary measure.

**Comment by Hjdskes** [comment]
I was thinking of a generic device with a general LED somehow showing an "off" state. But yea, the image itself doesn't really matter so long as we display *something*.

**Comment by whot** [comment]
you could easily take one of the themed device SVGs and scale it down. would look more consistent with the rest of piper

**Comment by Hjdskes** [comment]
That might be a good idea as well, I'll play around a bit.
