### ISSUE TITLE
Missing usb:046d:c08d for [Logitech G502 Hero Wireless] in data/svgs/svg-lookup.ini

### ISSUE THREAD

**Issue by YoyPa** [libratbag/piper#456]
**Describe the bug**
In <a href=https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g502-hero-wireless.device>logitech-g502-hero-wireless.device<a/> (libratbag) two usb devices are listed:
```
DeviceMatch=usb:046d:407f;usb:046d:c08d
```
In <a href=https://github.com/libratbag/piper/blob/master/data/svgs/svg-lookup.ini>svg-lookup.ini<a/> ```usb:046d:c08d``` is missing:
```

[Logitech G502 Hero Wireless]
DeviceMatch=usb:046d:407f
Svg=logitech-g502.svg

```

**Comment by FFY00** [comment]
Feel free to send a PR.
