### ISSUE TITLE
It doesn't detect any device (NISUTA NS-MOW35)

### ISSUE THREAD

**Issue by julioalpa** [libratbag/piper#469]
Recently installed piper but receive a message "No devices found"

My USB Mouse is a Nisuta model: NS-MOW35
OS: Elementary OS Hera

Can anybody help me?

**Comment by FFY00** [comment]
That device is not supported.

**Comment by stephanlachnit** [comment]
> Can anybody help me?

You can try to reverse engineer the protocol and implement it in libratbag, but without the hardware (and time), we can't help you.
