### ISSUE TITLE
Logitech G402 Hyperion fury has no customizable color LED

### ISSUE THREAD

**Issue by developomp** [libratbag/piper#476]
I'm using Logitech G402 Hyperion fury and I noticed that piper gives you option to change the color of your LED in the `LEDs` tab. But G402 doesn't have such customizability. The only thing we can change is the "breathe" where the LED dims every x amount of time. Please remove color-changing feature from G402.

**Comment by FFY00** [comment]
Yes. We should export led capabilities to be able to identify monocolor ledd.

**Comment by tomchiverton** [comment]
Duplicate of #338 which links to the required fix : https://github.com/libratbag/libratbag/issues/694

**Comment by staticssleever668** [comment]
You are right, good job noticing that! :)
