### ISSUE TITLE
Cannot install on Debian 10

### ISSUE THREAD

**Issue by WictorT** [libratbag/piper#477]
From documentation

When I run `sudo apt-get install piper` I get `E: Unable to locate package piper`.

If I run
```
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
sudo apt-get update
```

I get a GPG error.

**Comment by FFY00** [comment]
@skitt could you have a look?

**Comment by skitt** [comment]
@FFY00 yes!

There are two issues here: `piper` isn’t available in Debian 10, and configuring the PPA needs more work. I don’t know the details of the PPA, so I can’t help there, but I’ll upload backports of `piper` and its dependencies to Debian 10, and update the wiki to explain how to install them.

**Comment by FFY00** [comment]
Great, thanks!

**Comment by stephanlachnit** [comment]
Same as #475 btw, @WictorT in this issue you find installation instruction for Buster.

**Comment by WictorT** [comment]
Thank you all!
