### ISSUE TITLE
refering to #380 still not possible

### ISSUE THREAD

**Issue by Aevermann** [libratbag/piper#481]
refering to the defautlt setzting from here: https://www.logitech.com/assets/44964/3/g600-mmo-gaming-mouse-quickstart-guide.pdf graphics on page 3

I want to set the current right click to button No, 3 (outer right one) and use button 2 (large button right of mouse wheel) to be middle mouse click. Butt the buttons 1 and 2 can only swapped which make no sense.
To avouid users from looking them out u could use a feedback system similar to how monitors settings are made. New settings have to be confirmed within a timespan by clicking the right and left mouse buttons befor appling the new settings. In logitwechs software on windwos y can set the buttons as desired (only on cmputer profiles).

**Comment by Aevermann** [comment]
also it is currently totaly possible to lock yourself out of the mous settings, as the default profile on thou mouse can be set with the mode button and if there is no suitable profile saved  (eg it is set as I esired in Logitech Gaming Software on Wiindows) Linux pulls an not working setting from sowmwhere and nthe mouse operates with 200 dpi and none of the buttons (incl. leftclick) worjking. Thus I have to either connect a second mouse and reset the profile or have to boot to windows to fix the mess using the logitech gaming software. really annoying

**Comment by staticssleever668** [comment]
> I want to set the current right click to button No, 3 (outer right one) and use button 2 (large button right of mouse wheel) to be middle mouse click. Butt the buttons 1 and 2 can only swapped which make no sense.

TBH I think current interface is good as-is for preventing user mistakes, and described use-case is extremely niche.
However, this is just a safety guard in Piper, if absolutely needed, it can be done anyway through ratbagctl - the command line interface for libratbag.

> also it is currently totaly possible to lock yourself out of the mous settings

If this still happens, please, make a new issue for that following the suggested issue template.
