### ISSUE TITLE
Second Mode - Need Documentation

### ISSUE THREAD

**Issue by UltraBlackLinux** [libratbag/piper#487]
*Its not quite a feature request, but also no bug so im here...*
How do I set keys for the second mode, i mean i can activate it, but idk how i can setup the second mode keys ontop of another

**Comment by FFY00** [comment]
I am not sure if we support that in any driver. It should be possible to implement in the HID++ 2.0 driver but someone needs to do it.

**Comment by UltraBlackLinux** [comment]
What kinda Driver do you mean? Is there a way to download the driver?
(And please remove the second mode Setting from Piper, I spend hours of searching, how I can use it, cause its one of those options, I really need...)
