### ISSUE TITLE
Set polling rate below 500?

### ISSUE THREAD

**Issue by cncz42** [libratbag/piper#491]
Some games in wine have issues with high polling rates and even 500 will cause some lag, however, this software can only go down to 500 even though in windows it can reach 250

I'd like the ability to change polling rates to 250 and 750 in settings

Currently configuring polling rates in terminal is a chore

**Comment by stephanlachnit** [comment]
I could do a PR, shouldn't be too hard to add another box for 250Hz. However I have to check first how this is supported in libratbag. (cc @FFY00)
@cncz42 is 250Hz low enough? I don't want to add tons of boxes^^

**Comment by cncz42** [comment]
250Hz is low enough as it's the same lowest amount in most equivalent windows software

**Comment by cncz42** [comment]
Looked a bit deeper, 125 is the lowest equivalent windows software can go

**Comment by stephanlachnit** [comment]
For Logitech devicrs maybe, but we support more than just one vendor. I don't think every vendor supports 125Hz, and if 250Hz is low enough I'll just add that.

**Comment by rphsoftware** [comment]
125Hz should be the HID default, right? It would be weird for a vendor *not* to support 125Hz

I guess this still requires testing on various hardware...

**Comment by stephanlachnit** [comment]
> 125Hz should be the HID default, right? It would be weird for a vendor not to support 125Hz

Thanks for pointing this out. Since 250 Hz doesn't work for me, I will just go for 125 Hz only, if it's HID standard it should work everywhere.
@cncz42 does 125 Hz fit your use case? Also I'd like to point out, that I have a with #494 a PR, so please test it if you want to see this in a release.

**Comment by cncz42** [comment]
> @cncz42 does 125 Hz fit your use case? Also I'd like to point out, that I have a with #494 a PR, so please test it if you want to see this in a release.

yes because lower is better for apps that can't process high polling rates well

**Comment by fopor** [comment]
+1 would appreciate this, as I am guessing that a lower polling rate helps preserving wireless moues battery

**Comment by staticssleever668** [comment]
Fixed by https://github.com/libratbag/piper/pull/703
