### ISSUE TITLE
Adding feature to disable 

### ISSUE THREAD

**Issue by ByteFeather** [libratbag/piper#492]
I'm using Logitech G402 Hyperion fury and it can store up to 5 different DPi settings.
![disable 1](https://user-images.githubusercontent.com/40858122/77499578-77f1c980-6e8d-11ea-8659-f75c5da63515.png)
When I set them to a certain value, I cannot disable them anymore.
Please add a feature to disable a set DPI.

+EDIT---------------------------------
Also, while adding DPI disabling feature, please add an option to disable a button too.
I don't personally use the DPI toggle button so I want it to be disabled.
Now, piper shows disabled button as `Unknown`.
![disable 2](https://user-images.githubusercontent.com/40858122/77499690-bf785580-6e8d-11ea-9e64-732b91e85433.png)

**Comment by FFY00** [comment]
WIP: libratbag/libratbag#870

About the buttons, we should have a "None" action mapping.

**Comment by ByteFeather** [comment]
Thank you!
