### ISSUE TITLE
Create a Flatpak including libratbag and ratbagd

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#5]
Hello,

@whot asked me to look into creating a Flatpak of Piper which includes libratbag and ratbagd. This issue is meant to track required items. I will edit this post to add items as I go; other findings will be added as comments.

RUNTIME: we will require GNOME's runtime as we require GLib and GTK+ for Piper. Versions generally don't matter, but we need to see what version of GTK+ we want to use. Newer versions have fancier widgets, but this might limit availability in distributions like Debian when Piper is installed without Flatpak.

TODO:
- [ ] Make ~~libratbag, ratbagd and~~ Piper build systems compliant with the [Build API](https://github.com/cgwalters/build-api/) as required for `flatpak-builder`
  - [x] libratbag
  - [x] ratbagd
  - [ ] Piper
- [ ] AppData file for Piper (optional)
- [ ] All files exported from the Flatpak need to have the application ID as their prefix. We can either rename the relevant source files or use `flatpak-builder` to rename the files at build time. My preference would be the former to keep it simple.
  - [ ] Desktop file
  - [ ] Application icon
  - [ ] `ratbagd.service.in` (not sure how this works with an `org.freedesktop.ratbagd` ID in the Flatpak for Piper with `org.freedesktop.Piper` yet)

**Comment by Hjdskes** [comment]
Just found out that [Meson is supported natively by `flatpak-builder`](https://github.com/flatpak/flatpak/pull/420) so we don't need to touch libratbag and ratbagd's build systems.

**Comment by whot** [comment]
but we don't need to *build* anything for a pure python application, don't we? We just need to *run* it, and that should be possible without any extra work, it can be treated like the hello world example application: http://flatpak.org/hello-world.html

I think so, anyway :)

**Comment by Hjdskes** [comment]
Right, I thought it'd be best to stick to executing `setup.py` in the Flatpak but simply copying files over should work too. I've begun building with the former, though, as it seems this can then be automated with `flatpak-builder` whereas the hello-world example seems to imply it's manual work.

I've run into another, nastier issue, though:
```
Meson encountered an error in file meson.build, line 44, column 0:
Native dependency 'libudev' not found
```

Apparently, udev is not available inside the sandbox. [GNOME's applications work around this](https://github.com/GNOME/gnome-apps-nightly/commit/1ac358ce915498ca06b7a5a9242ec6680eb3befa) by building without it, e.g. [gnome desktop](https://git.gnome.org/browse/gnome-desktop/commit/?id=140aa80ae4b3d83505e374d0d3a53068a6489e17) but this would render ratbagd and libratbag useless. Related: https://github.com/flatpak/flatpak/issues/7, https://github.com/flatpak/flatpak/issues/12.

In researching this I have also come across multiple mentions that devices are *not* available inside the sandbox, so while I haven't investigated this it is not looking good...

**Comment by Hjdskes** [comment]
Here is the `org.freedesktop.Piper.json` file I'm working with ATM if you want to test things yourself:

```
org.freedesktop.Piper.json 
{
    "app-id": "org.freedesktop.Piper",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.24",
    "sdk": "org.gnome.Sdk",
    "command": "piper",
    "finish-args": [
        "--share=ipc", "--socket=x11",
        "--socket=wayland"
    ],
    "buildsystem": "simple",
    "build-commands": [
        "python setup.py build --prefix=/usr",
        "python setup.py install --prefix=/usr --optimize=1 --skip-build"
    ],
    "cleanup": [ ],
    "modules": [
        {
            "name": "ratbagd",
            "builddir": true,
            "buildsystem": "meson",
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/libratbag/ratbagd.git"
                }
            ],
            "name": "libratbag",
            "buildsystem": "meson",
            "builddir": true,
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/libratbag/libratbag.git"
                }
            ]
        }
    ]
}
```

**Comment by whot** [comment]
huh, good point. no access to /dev and no udev is a bit of a spanner in the works now. I guess we need to put this on backburner until we have support for at least /dev. We *could* potentially somehow work around a lack of libudev, but it's a fair bit of work.

I think piper itself could still be interesting as flatpak. even though we should be able to just run it straight from the repo, I suspect over time people may become accustomed to downloading flatpaks.

Thanks heaps for the research!

**Comment by Hjdskes** [comment]
I've been trying to package only Piper (with the idea that it will at least allow us to ship *that*, and that it should be a simple addition of two modules once Flatpaks have access to udev and `/dev` to add libratbag and ratbagd), but I've been running into the issue that piper, installed into `/app`, cannot find the Python libraries installed under `/usr/lib/python3.5/`. I have a query going on IRC but so far no replies.

Another solution in my mind is to stop using `pkg_resources` and use Gio's [GResource](https://developer.gnome.org/gio/stable/GResource.html) files. This, to me, feels like a much nicer approach than the current one with `pkg_resources`, especially considering that Piper is (trying to be) a GNOME application.

However, support for GResource files is non-existent in setuptools. The .xml file has to be compiled, the result of which needs to be distributed with the binary. I suppose this would be a good reason to use Meson instead of setuptools: to get the integration with the GNOME stack (AppData, GResource, GSchema, et cetera) basically for free. Another advantage is that a Meson build system does not require any tricks to get working with Flatpak. I've looked into it and Meson [has support](https://github.com/mesonbuild/meson/issues/1208) building languages that do not require compilation.

The more I think about it, the more I start to like porting to Meson. I can work something out for to test with your approval.

**Comment by whot** [comment]
short answer: I'm not going to argue against meson, because I'm more familiar with it than setuptools :)
you certainly don't need my approval for that, give it a try and see if it works. if it doesn't, we've learned something. A lot of this is very much trial and error so far, none of us are real python developers anyway

**Comment by Hjdskes** [comment]
Quick update: I mistakenly got the idea that the host system can provide dependencies to the Flatpak, so packaging only Piper isn't going to help (even though I think I have that part taken care of now, see [my WIP branch](https://github.com/Hjdskes/piper/blob/flatpak/org.freedesktop.Piper.json)). If you run that you get an `AttributeError` which I think is Python's way of letting us know that the module cannot be initialised due to it being unable to resolve the ratbagd Python bindings.

According to IRC some Flatpaks do bundle udev (example: https://github.com/endlessm/electron-flatpak-base-app/blob/master/io.atom.electron.BaseApp.json#L27-L38) so I'm off to see if we can use that to bundle libratbag and ratbagd.

**Comment by Hjdskes** [comment]
Sadly all those udev versions are too old:

```
../src/libratbag.c: In function ‘ratbag_unref’:
../src/libratbag.c:561:16: error: void value not ignored as it ought to be
   ratbag->udev = udev_unref(ratbag->udev);
```

Before I dig into this deeper it's time to get some sleep, meanwhile any tips you know of are welcome!

**Comment by whot** [comment]
hmm, that'd be an argument to move the ratbagd python bindings into a separate repository. Or even ship them with piper, the bindings are just for a dbus interface anyway, not anything else. There shouldn't be any dependency on ratbagd otherwise for the python bindings, so splitting them out should work.

the udev issue would be easy to fix too I think, because it always return NULL anyway.

**Comment by Hjdskes** [comment]
Even if we did manage to install udev into the Flatpak, it wouldn't work:

```
mclasen	        TingPing: wrt to udev, the answer is: use a stable api. Really depends on what information you need - for storage, it could be udisks, for sound, pulseaudio, etc...
TingPing	mclasen, i guess my question was, is it acceptable to bundle udev or will that conflict with the host in some way
                because obviously we can't quite control the dependencies of some packages
alexlarsson	TingPing: you can bundle udev for the api
                TingPing: but you can't rely on it *working*
                TingPing: because a) it may not have access to every device, etc and b) it will not have access to the system udevd database
                and we can't grant it because that is not a stable on disk format
                (i asked upstream about it)
```

You can also read the related Flatpak issues I linked to in https://github.com/libratbag/piper/issues/5#issuecomment-301787796.

I suppose this is on hold for now, until a solution is found.

**Comment by whot** [comment]
closing as wontfix for now, thanks for all the research. Summary is until udev is sorted out for flatpaks, ratbagd and libratbag are not an option.

Piper is still a different story because it can be standalone and only talk to ratbagd (outside the sandbox) via the dbus interface, but we'll cross that bridge when we get to it.

**Comment by whot** [comment]
Just resurrecting this, though I expect it may get closed again. But some things have changed on the libratbag side:
- we use libudev to detect device nodes
- we use libudev to find hidraw nodes for devices
- we no longer use udev properties ourselves

To remove the libudev dependency, we could add a new path-based API to libratbag and use e.g. inotify in ratbagd replicate the udev-monitor. Searching for matching hidraw nodes  probably requires opening every hidraw node and comparing bits where possible. So not ideal, but at least more realistic than libudev in a flatpak.

As for device access: flatpak can mount all of `/dev/` into the sandbox with ``"finish-args": [ "--device=all" ],`` (filtering for input devices only is not possible). 

I got `evemu-record` to work in a flatpak this way but it obviously still needs to be run as root. This is the main takeaway here - a libratbag flatpak would be a **packaging** solution, not a sandboxing solution. Plus we'd have to make sure in piper that we drop privs when we start up if we start through a flatpak that also runs ratbagd.

**Comment by Hjdskes** [comment]
We can also consider libratbag to be a 'system' package. AFAIK, GNOME does the same for many packages. Then we can package Piper as is done in #235, and keep libratbag the way it is. On the short term, I think this is our best bet. Long term, it may still be -- I don't think we should have to mutilate libratbag just to get it working inside a flatpak.

**Comment by whot** [comment]
I'm going to close this. The only way I can envision this to work is to have a hid device portal for flatpak and then modify ratbagd to be able to work through that. This hasn't happened yet and I doubt anyone is going to magically find the time to implement this.

Due to the interaction with hardware, ratbagd is by definition a system daemon and thus basically out of scope for flatpak which has a desktop app focus.

So yeah, if anyone wants this they can figure it out but let's not pretend we'll work on this.
