### ISSUE TITLE
DPI resets every once in a while

### ISSUE THREAD

**Issue by QazCetelic** [libratbag/piper#508]
**Information**
- `ratbagd` version (`0.13`):
- Piper version: 0.4
- Distribution: KDE Neon
- Kernel version (ex. `uname -srmo`): `5.3.0-46-generic`
- Mouse: Logitech G600

**Describe the bug**
The DPI (or resolution as it's called in piper) is reset every once in a while, I set it to 500, 4000, 500, 4000 however it changes back to 800, 1200, 1600, 32000

**To Reproduce**
I was unable to use libratbag using the CLI (not because of an error but probably because I did something ). 

1. Set resolution
2. Wait
3. Resolution changes back

**Logs**
```
$ ratbagd --verbose=raw
```
Can't run command because libratbagd is already running and I don't know how to stop it.

**Additional context**
I hope this is helpful even if I don't have a clue what I'm doing.
Seems to be the same as [a closed issue](https://github.com/libratbag/piper/issues/330).

**Comment by FFY00** [comment]
Which device?

**Comment by QazCetelic** [comment]
Logitech G600

**Comment by QazCetelic** [comment]
It's still a problem in the current version (0.5)

**Comment by FFY00** [comment]
Sorry for the late reply, I don't have that device and I am not sure why that would happen, sorry.

**Comment by QazCetelic** [comment]
It still happens. It also seems like piper has no effect on the mouse, I changed to DPI back to how I wanted it in Piper, but it did not actually change the DPI.

**Comment by QazCetelic** [comment]
I'm unable to replicate this issue anymore.
