### ISSUE TITLE
Ubuntu 20.04 PPA version of Piper does not start with ModuleNotFoundError

### ISSUE THREAD

**Issue by KlfJoat** [libratbag/piper#515]
**Information**

- `ratbagd` version (`ratbagd --version`):  0.13
- Piper version: Since Piper doesn't run, this is what I've got...
```shell
$ apt show piper
Package: piper
Version: 0.4+git431-2964944~ubuntu20.04.1
```
- Distribution: Ubuntu 20.04
- Device: N/A (Logitech M705)
- Kernel version (ex. `uname -srmo`): `Linux 5.4.0-28-generic x86_64 GNU/Linux`

**Describe the bug**
Using the Ubuntu PPA, Piper will not start via gnome-shell or the command-line.

When I start it via the command line I receive the following error
```shell
$ piper                                          
Traceback (most recent call last):                          
  File "/usr/bin/piper", line 36, in <module>            
    from piper.application import Application       
ModuleNotFoundError: No module named 'piper' 
```

This is admittedly the same issue as #341. In fact, I did some of the same troubleshooting...

```shell
$ ll /usr/lib/python3/dist-packages/piper
lrwxrwxrwx 1 root root 38 Apr 29 17:58 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.7/site-packages/piper
$ ll /usr/lib/python3.7/site-packages/piper
ls: cannot access '/usr/lib/python3.7/site-packages/piper': No such file or directory
$ ll /usr/lib/python3.8/site-packages/piper
total 164K
-rw-r--r-- 1 root root 3.1K Apr 28 16:16 application.py
(etc)
```
**So the bug, IMO, seems to be that the Ubuntu 20.04 PPA does not install Piper correctly.**  It seems to use the wrong symlink location.

**To Reproduce**

1. Install Ubuntu 20.04 (upgrade from 19.10)
2. Run `apt install piper`
3. *Piper* runs just fine.  HOWEVER...
4. Experience libratbag/libratbag#970
5. To fix that problem, run
```shell
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
sudo apt-get update
sudo apt upgrade
```
6. Open gnome-terminal
7. Type `piper`
8. See error

**Logs**
There are no logs. `ratbagd` does not start.  I am unable to find command line help for Piper bc it will not start.  Starting with `piper --debug` or `piper --verbose` provides nothing extra.

**Additional context**
Obviously, I can fix this individual problem for myself.  
```shell
$ sudo ln -si /usr/lib/python3.8/site-packages/piper /usr/lib/python3/dist-packages/piper 
Executing sudo -- bash -x -v -c "ln" '-si' '/usr/lib/python3.8/site-packages/piper' '/usr/lib/python3/dist-packages/piper'
"ln" '-si' '/usr/lib/python3.8/site-packages/piper' '/usr/lib/python3/dist-packages/piper'
+ ln -si /usr/lib/python3.8/site-packages/piper /usr/lib/python3/dist-packages/piper
ln: replace '/usr/lib/python3/dist-packages/piper'? y
$ ll /usr/lib/python3/dist-packages/piper
lrwxrwxrwx 1 root root 38 May  1 14:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8/site-packages/piper/
```
But that's a workaround, not a fix.

**Comment by FFY00** [comment]
cc @muzena

**Comment by stephanlachnit** [comment]
If you are on 20.04 you can also use the version in the Ubuntu universe repo (it will be stuck on 0.4 though). If you do this, remove piper+libratbag, remove the PPA and install with apt.

**Comment by muzena** [comment]
@KlfJoat 
Uninstall piper, remove manually made symlink python3.8 and then try again install
sudo apt install piper

**Comment by KlfJoat** [comment]
@muzena 
Thanks, that fixes it for me!

FYI, the [postrm script](https://github.com/muzena/piper-packaging/blob/master/debian/piper.postrm) handled removal of the symlink, no matter where it points to.  So your middle step was unnecessary.
