### ISSUE TITLE
Not working on PopOs 18.04 LTS

### ISSUE THREAD

**Issue by afelro97** [libratbag/piper#516]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.13
- Piper version: 0.4
- Distribution: Pop!_OS 18.04 LTS x86_64
- Device: Logitech g305
- Kernel version (ex. `uname -srmo`): `5.3.0-7648-generic`

**Describe the bug**
I followed all the steps and it did not detect my device

**Additional context**
Im running piper on a PopOs dist 18.04 Lts 
I installed ratbag first, then piper, it didn't work, I restarted the pc and it still didn't work, I updated repositories and it still didn't work

**Comment by FFY00** [comment]
You need https://github.com/torvalds/linux/commit/5722f3386eb9847131573513190796533e8f4999, which was introduced in Linux 5.4.

**Comment by afelro97** [comment]
Hello, I already updated my kernel to version 5.4 (PopOs 20.04) but it still doesn't work

![image](https://user-images.githubusercontent.com/48090232/81189074-c1006780-8f7b-11ea-8f77-70cc59d6d92a.png)

**Comment by afelro97** [comment]
Update: I restarted the computer and it worked perfectly
![image](https://user-images.githubusercontent.com/48090232/81191668-e6db3b80-8f7e-11ea-867f-c0c31c16f516.png)
