### ISSUE TITLE
Logitech MX Anywhere 2 -- no picture of mouse.

### ISSUE THREAD

**Issue by D33M0N** [libratbag/piper#523]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.14
- Piper version: 0.4.r21.g00f3381-1
- Distribution: Manjaro
- Device: Logitech MX Anywhere 2
- Kernel version (ex. `uname -srmo`): `Linux 5.6.12-1-MANJARO x86_64 GNU/Linux`

**Describe the bug**
picture is missing. showing rat with "404" sign.

![piper-logitech-mx-anywhere2](https://user-images.githubusercontent.com/15782020/82616823-dbfaea80-9bbd-11ea-82cb-07fde8cacfa6.png)

**Comment by D33M0N** [comment]
already spotted the problem in:
/usr/share/piper/piper.gresource
is

[Logitech MX Anywhere 2]
DeviceMatch=usb:046d:404a;bluetooth:046d:b013;bluetooth:046d:b018
Svg=logitech-mx-anywhere2.svg

BUT in:
/usr/share/libratbag/logitech-MX-Anywhere2.device
is

[Device]
Name=Logitech MX Anywhere 2
DeviceMatch=usb:046d:404a;bluetooth:046d:b013;bluetooth:046d:b018;bluetooth:046d:b01f
Driver=hidpp20


and I have no clue how to correctly edit /usr/share/piper/piper.gresource to add the missing ";bluetooth:046d:b01f"

**Comment by FFY00** [comment]
You can add all the missing IDs. Pull requests are welcome.

**Comment by D33M0N** [comment]
done :-)
https://github.com/libratbag/piper/pull/524/commits/a4b8d4a4dfeda128d27e2387017a83a7a5063b32

**Comment by stephanlachnit** [comment]
Thanks!
