### ISSUE TITLE
Ratbag bindings should have proper enums

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#53]
Going to do this once all different PRs that have binding changes are in.

**Comment by whot** [comment]
I think this is done now?

**Comment by Hjdskes** [comment]
Haven't even started on this :) FYI, I mean to have e.g. `class RatbagButtonActionType(IntEnum)` instead of having `ACTION_TYPE_FOO` class variables.

The priority here obviously isn't high at all so I'll likely do this during some down time somewhere down the line.

**Comment by whot** [comment]
oh, I thought this referred to moving it to named items in the bindings. nevermind, I'll leave this open.

**Comment by whot** [comment]
done with 3c33bd850b198dc7124c5d1cd01b03b2b5f8778b
