### ISSUE TITLE
"Resolution Up" Doesn't work (like i expect it to)

### ISSUE THREAD

**Issue by QazCetelic** [libratbag/piper#537]
**Information**
Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.0
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-59-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa DRI Intel® UHD Graphics 630 

**Describe the bug**
I thought it would use the resolution above the currently selected resolution, but it doesn't do anything except that it makes the RGB brighten

**To Reproduce**.
1.  Assign "resolution up" to button
2. Nothing happens except that it makes the RGB brighten

**Device**
Logitech G600

**Comment by FFY00** [comment]
Device?

**Comment by QazCetelic** [comment]
Logitech G600

**Comment by QazCetelic** [comment]
Not reproduceable
