### ISSUE TITLE
Can't assign buttons

### ISSUE THREAD

**Issue by QazCetelic** [libratbag/piper#538]
**Information**
Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.0
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-59-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa DRI Intel® UHD Graphics 630 

**Describe the bug**
If I assign a button it will show up in Piper but it will still do the action the button was assigned to before.

**To Reproduce**
1. Assign button (In my case I assigned G18 with mouse button 5)
2. Press button (G18)
3. Does action button was assigned to before (In my case it )

**Additional context**
I'm using a Logitech G600 mouse

**Comment by FFY00** [comment]
Device?

**Comment by QazCetelic** [comment]
Logitech G600

**Comment by QazCetelic** [comment]
Issue not reproduceable
