### ISSUE TITLE
Can’t find service/doesn’t detect mouse - OpenSUSE

### ISSUE THREAD

**Issue by peterandrewd** [libratbag/piper#556]
Using OpenSUSE Tumbleweed. When I launch the piper app, it says uh oh and doesn’t detect any device and says please make sure ratbagd service is running and your user is in the required group
On other distros it detects my g703 mouse.
All the services and d-bus daemons are installed and symlinked too.
Any solutions?

**Comment by peterandrewd** [comment]
*EDIT* Fixed.
But FFS shouldn't of had to do that much modification to make it work

**Comment by andrerodr** [comment]
Can you elaborate on the fix?

**Comment by peterandrewd** [comment]
> Can you elaborate on the fix?

Nope because look above and see how many people replied or tried to give me a solution before I spent ALL night working out myself how to fix it....0 people :)
You get what you give in life.

**Comment by FFY00** [comment]
Sorry if my response time, which comes from my free time and is shared with a bunch of other projects, was not enough for your requirements.

**Comment by FFY00** [comment]
That said, you are probably much better off asking your provider (in this case, OpenSUSE) for support. They are the ones packaging libratbag for you and have the responsibility to make sure everything works fine when installed on the system.

**Comment by peterandrewd** [comment]
Firstly, it pisses me off when people say I only do this in my free time. Sure, I respect that, but if you commit to a project, you assume responsibility for all support requests, and to provide the support as much as possible as well as continued maintenance and development. Either commit fully or don’t commit to it at all.
Secondly, it was nothing to do with OpenSUSE, as I built it from source.

**Comment by FFY00** [comment]
> Firstly, it pisses me off when people say I only do this in my free time and use it as an excuse.

Well, it pissed me off when people think they are entitled to my free time.

> but if you commit to a project or multiple projects, you assume responsibility for all support requests, and to provide the support as much as possible as well as continued maintenance and development of said projects

I absolutely do not. All support that is presented is on a best effort basis and relies solely on the good will of the maintainers and other users that might want to contribute.

An excerpt from the license:
```
			    NO WARRANTY

  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN
OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS
TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE
PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,
REPAIR OR CORRECTION.
```

> Either commit fully or don’t commit to it at all.

I guess you would be better off with nobody not committing at all, and this project not existing, right?

And this all seems ridiculous since it was merely hours between you opening the request and getting it to work. Furthermore, it was a Sunday, even if this was a commercial product and you had a support contract with the developers, you would \*very\* likely not have gotten support that fast.

No hard feelings, but please re-evaluate your behavior and expectations regarding open source software. I understand you had a bad experience, but this is not how you should behave. If you keep acting like this, you will have a very bad experience getting support from other projects.

Cheers :heart:

**Comment by peterandrewd** [comment]
Well you’re commenting very quickly now, so I guess I rest my case. If you can comment quickly now, you can comment quickly other times.
Cheers x

**Comment by FFY00** [comment]
Yes. Because I am available right now?? I wasn't when you opened the issue.

Anyway, you would probably just be better off not using the project because I will not provide any support if you keep acting like this.

**Comment by peterandrewd** [comment]
Noted sir piper dev

**Comment by gimbas** [comment]
@peterandrewd You need a reality check, the world does not revolve around you and your issues.

That being said, since you managed to fix your issue so swiftly by yourself, maybe you should consider becoming a contributor and help fix the apparent lack of support :wink: that is, if you have free time of course.

**Comment by peterandrewd** [comment]
I MAKE free time unlike most others, because that’s how I envision my life to be, a fine but necessary balance of work and free time.
I might consider contributing especially detailing how I fixed the issue I was having, but I’d only do it on under condition lmao

**Comment by andrerodr** [comment]
I was expecting to see the dev team ignoring this guy let him speak alone, specially considering it's tone, but his own words say everything about him. https://github.com/foxlet/macOS-Simple-KVM/issues/247#issuecomment-644751468

**Comment by peterandrewd** [comment]
> I was expecting to see the dev team ignoring this guy let him speak alone, specially considering it's tone, but his own words say everything about him. [foxlet/macOS-Simple-KVM#247 (comment)](https://github.com/foxlet/macOS-Simple-KVM/issues/247#issuecomment-644751468)

Stalker. Absolute stalker. Creep. The more you people reply and continue to poke shit at me, the less I’m going to want to contribute or detail my solution and the more I’m going to want to continue pissing people off

**Comment by gimbas** [comment]
I'm pretty sure no one actually wants your contributions, I was mostly making fun of you by suggesting so.

Also:
> Stalker. Absolute stalker. Creep.
How so? These things are public you know...

**Comment by peterandrewd** [comment]
The very fact that you even felt the need to post my other conversations from another git is creepy and the fact you even looked me up to find my other conversations.
And good then if no one wants my contributions. 1 less thing I have to do 😂
But keep replying cos you’re giving me the fuel I need to continue 😅

**Comment by gimbas** [comment]
Different people, i didn't post your conversations.

I guess I'll keep replying, with enough fuel, you might just catch fire.

**Comment by peterandrewd** [comment]
Lmao I’ll catch fire and burn you

**Comment by FFY00** [comment]
> I was expecting to see the dev team ignoring this guy let him speak alone, specially considering it's tone, but his own words say everything about him. [foxlet/macOS-Simple-KVM#247 (comment)](https://github.com/foxlet/macOS-Simple-KVM/issues/247#issuecomment-644751468)

Well, if no one stands up and points out his behavior is wrong, he will just keep doing it. I gave it a try, not sure what else I can do :confused:
