### ISSUE TITLE
Piper can't acess ratbagd - permissions 

### ISSUE THREAD

**Issue by andrerodr** [libratbag/piper#559]
- `ratbagd` version 0.14
- Piper version: 0.5.1
- Distribution: Opensuse Tumbleweed
- Device: G703, MX518 Legendary (2018), MX Master 2S
- Kernel version Linux 5.8.0-1-default x86_64 GNU/Linux
(5.7.x, 5.6.x)

**Describe the bug**
Piper can't connect to ratbagd as regular user, only as root. Also valid for ratbagctl.

-Solved-
 Workaround
Add user account to games group "sudo usermod -a -G games 'YourUserName' 
and reboot, as logout and login is not enough.

 Please add some reference to this issue on the wiki/faq
also : 
https://github.com/libratbag/piper/issues/379#issuecomment-529874661
https://github.com/libratbag/libratbag/issues/802#issuecomment-525754861

**Comment by FFY00** [comment]
How did you install libratbag?

**Comment by andrerodr** [comment]
both are v. 0.14- from standard opensuse repoitory

asus:/home/andre # which ratbagd
/usr/sbin/ratbagd
asus:/home/andre # which ratbagctl
/usr/bin/ratbagctl
asus:/home/andre #

**Comment by FFY00** [comment]
Can you please report this issue to them? It seems like the package isn't properly setting up the DBus service. We can keep this open here in the meantime.

**Comment by FFY00** [comment]
I think @DimStar77 is the maintainer.

**Comment by FFY00** [comment]
Well, actually @theMarix. Sorry for the ping Dominique.

**Comment by andrerodr** [comment]
Ok I will report it,
the idea behind making a reference on faq or wiki is that in 6 months or 1 year it may brake again and users have the chance to maintain  some more hair.

**Comment by andrerodr** [comment]
Thank you

**Comment by FFY00** [comment]
No worries. I believe everyone has edit access to the wiki, feel free to ass that.

**Comment by staticssleever668** [comment]
Duplicate: #551

**Comment by swarnimcodes** [comment]
thanks! had the same issue on tumbleweed and adding the user to the games group worked.

**Comment by malikwirin** [comment]
Im still having this issue, adding my user to the groups input and games did not work
