### ISSUE TITLE
No picture for G102 LightSync

### ISSUE THREAD

**Issue by GamerSlav** [libratbag/piper#563]
Hi, I'm using G102 LightSync, but when I use Piper, I can't see svg of my mouse.

![изображение](https://user-images.githubusercontent.com/44983570/90800867-a7b6d780-e32e-11ea-879b-ff1688d3dd8c.png)

Is there a solution for this problem?

**Comment by FFY00** [comment]
What is the USB ID?

**Comment by GamerSlav** [comment]
> What is the USB ID?

046d:c092

**Comment by FFY00** [comment]
It is fixed by https://github.com/libratbag/piper/commit/bf2444ac0f0a2cd7cdfe2e391765b2342e164231. Can you try building from master?

**Comment by GamerSlav** [comment]
> It is fixed by [bf2444a](https://github.com/libratbag/piper/commit/bf2444ac0f0a2cd7cdfe2e391765b2342e164231). Can you try building from master?

Sorry, my english isn't good enough, what do you mean "building from master"?

**Comment by FFY00** [comment]
This will be fixed in the next version, if you want it right now you need to build and install the software from source.

**Comment by GamerSlav** [comment]
> This will be fixed in the next version, if you want it right now you need to build and install the software from source.

```
~/piper$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.45.1
Source dir: /home/sheptikhinva/piper
Build dir: /home/sheptikhinva/piper/builddir
Build type: native build
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)

meson.build:15:0: ERROR: Native dependency 'pygobject-3.0' not found
```
Can you help with this?

**Comment by GamerSlav** [comment]
> This will be fixed in the next version, if you want it right now you need to build and install the software from source.

Ok, thank you :)
