### ISSUE TITLE
Not really an issue, but can we change Profile Names? 

### ISSUE THREAD

**Issue by ThanosPlanetSmasher** [libratbag/piper#566]
Holy Moly is this software amazing!  The only thing I wonder is if there is a way I can change the profile names?  I dont expect this to hit the GUI anytime soon, but I was wondering if I could change a filename or something to change the profile names? Thanks so much!  This project should come standard with every Linux Distro.

**Comment by FFY00** [comment]
```
$ ratbagctl help
...
  profile N name set blah             Set the name of the profile
...
```

**Comment by FFY00** [comment]
Now, if that works on your device is another question :sweat_smile:

**Comment by ThanosPlanetSmasher** [comment]
You bet.  And I would put that into terminal with ratbagctl?

**Comment by FFY00** [comment]
Yes, in the terminal.
