### ISSUE TITLE
Can't find any device - Linux Ubuntu 19.10 - Razer DeathAdder Essential

### ISSUE THREAD

**Issue by agmonr** [libratbag/piper#568]
**Information**
- `ratbagd` 0.14 (`ratbagd --version`):
- Piper version: 0.5.1
- Distribution: ubuntu 19.10
- Device: Razer DeathAdder Essential
- Kernel version (ex. `uname -srmo`): `Linux 5.3.0-64-generic x86_64 GNU/Linux`

Tried also with ubuntu 20.04 and logitech b100 with the same results. 

**Describe the bug**
When I open the Piper, it shows the message "Can't find any device - Verify if the device is connected" 

**To Reproduce**
ratbagctl
No devices available.

**Logs**
sudo ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Blue Microphones Yeti Nano
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for b58e:0005
ratbag debug: New device: Razer Razer DeathAdder Essential
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:006e
ratbag debug: New device: Razer Razer DeathAdder Essential
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:006e
ratbag debug: New device: Razer Razer DeathAdder Essential
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:006e
ratbag debug: New device: Razer Razer Cynosa Chroma
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:022a
ratbag debug: New device: Razer Razer Cynosa Chroma
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:022a
ratbag debug: New device: Razer Razer Cynosa Chroma
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1532:022a
ratbag debug: New device: DELL07FA:00 06CB:7E92
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 06cb:7e92
DBus server ready

sudo systemctl status ratbagd
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-09-05 13:13:15 IDT; 2s ago
 Main PID: 3202 (ratbagd)
    Tasks: 1 (limit: 4915)
   Memory: 868.0K
   CGroup: /system.slice/ratbagd.service
           └─3202 /usr/bin/ratbagd

Sep 05 13:13:15 HaDavinchi systemd[1]: Starting Daemon to introspect and modify configurable mice...
Sep 05 13:13:15 HaDavinchi systemd[1]: Started Daemon to introspect and modify configurable mice.```

**Comment by FFY00** [comment]
Unfortunately we don't support razer devices yet :confused:, it is in my TODO but I am swamped right now.

**Comment by modMars** [comment]
> Unfortunately we don't support razer devices yet confused, it is in my TODO but I am swamped right now.

Did the razer support ever become a reality? Piper can't find my Razer Orochi v2.

**Comment by staticssleever668** [comment]
@modMars, no, it didn't.
By the way there is another open source device configuration utility made specifically for Razer devices: https://github.com/openrazer/openrazer.
