### ISSUE TITLE
Missing G915 image

### ISSUE THREAD

**Issue by TheLazyHatGuy** [libratbag/piper#572]
**Is your feature request related to a problem? Please describe.**
The image for the G915 keyboard is missing

**Describe the solution you'd like**
Add the missing image

**Describe alternatives you've considered**
``

**Additional context**
``

**Comment by opal06** [comment]
I have made a pull request (#578) to fix this issue. I reused the image from the G815 as it is the same device just wired. On my G915 it works fine, so I hope it can get merged quickly. In the meantime, you can always pick the commit and build yourself.

**Comment by MJWootton** [comment]
I can confirm that an appropriate image for the G915 appears in Piper on the version available through apt-get, but it's missing on the version from FlatHub.

**Comment by Techognito** [comment]
Can confirm the image is there in v0.7 from flathub
