### ISSUE TITLE
Add suport for Logitech G203 Lightsync

### ISSUE THREAD

**Issue by brunobmello25** [libratbag/piper#576]
Here is the output for lsusb:

- Bus 003 Device 005: ID 046d:c092 Logitech, Inc. G203 LIGHTSYNC Gaming Mouse

I believe it's svg can be the same as the conventional logitech g203

**Comment by FFY00** [comment]
It should, we just need to have the extra LED.

**Comment by brunobmello25** [comment]
> It should, we just need to have the extra LED.

There is no extra led between the logitegh g203 and the lightsync version, I think. The only difference is the led controls that are a bit better

**Comment by DrewBrunning** [comment]
Just to clarify, the Logitech G203 Lightsync does have three LEDs and should also have additional modes such as cycling the colors. However, it looks like libratbag only detects one LED currently:

https://github.com/libratbag/libratbag/issues/1059

It would be great if Piper could allow for independent control of all three LEDs as OpenRGB does; however, it seems like the libratbag driver will need to be fixed to get the correct number of LEDs first.

**Comment by staticssleever668** [comment]
This ID was added at some point

**Comment by wedesoft** [comment]
Any news on this or a workaround? I installed today's version from source and ratbagctl only reports 1 LED for Logitech G203 Lightsync.
