### ISSUE TITLE
Displays a 404 image when using a Logitech MX Master 3 via Bluetooth

### ISSUE THREAD

**Issue by lasersocks** [libratbag/piper#579]
Piper Version: 0.4 shows a picture of a rat holding a 404 sign while connected to my Logitech MX Master 3 via Bluetooth.

Under the welcome screen it shows that it's detected the MX Master 3 (again with the same 404 image as its icon)

**Comment by FFY00** [comment]
Hum, seems like the device ID needs to be added to the data file.

**Comment by fpuga** [comment]
AFAIK  this can be closed. I'm connecting by bluetooth and correct svg is shown.

**Comment by FFY00** [comment]
Feel free to reopen if it is missing your particular ID!

**Comment by chqzeng** [comment]
not sure whether it is appropriate to continue this issue. I have the same issue with my new MX Master (**not 3**).
I assume issue #389 has solved the name ID for my mouse. 

OS: __Ubuntu 20.04__. 
connection: _Bluetooth_.
production info when checked with Device: product: _0xb01e_,  version: _0x5_, bus: _0x5_, vendor: _0x46d_
installation method:
```
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
sudo apt-get update
sudo apt install piper
```
I am trying to setup using [Logiops](https://github.com/PixlOne/logiops) after see this issue, but seems better to setup the mouse with GUI.
thx

**Comment by FFY00** [comment]
It didn't, you need to add a new ID: `bluetooth:046d:b01e`. Could you open a pull request?

**Comment by chqzeng** [comment]
> It didn't, you need to add a new ID: `bluetooth:046d:b01e`. Could you open a pull request?

thank you! quite new to github, I added the pull request, not sure whether that is correct ...
For your suggestion, do I need to wait until next release of `ppa:libratbag-piper/piper-libratbag-git` to use advanced features on my mouse, or I can change it myself from my end?
I notice the previous #389 mentioned about file `data/svgs/svg-lookup.ini`, where is it in my system?
thx

**Comment by luisalvarado** [comment]
Is this why the 935g shows like this

![image](https://user-images.githubusercontent.com/29236/113342196-70100500-92eb-11eb-97ba-d007ed947bfe.png)

![image](https://user-images.githubusercontent.com/29236/113342214-769e7c80-92eb-11eb-8c99-9c0aacc84400.png)

**Comment by bbb651** [comment]
I'm also seeing the 404 image with the `Logitech G102 LIGHTSYNC Gaming Mouse`.

![Screenshot from 2021-06-23 00-32-28](https://user-images.githubusercontent.com/53972231/123002356-82658080-d3ba-11eb-9518-74117cf718b2.png)

I'm on Arch with the GNOME 40 desktop environment.

**Comment by eldelacajita** [comment]
Same here for the MX Anywhere 3. Using Piper 0.5.1 on Manjaro.

**Comment by aalvajn** [comment]
**Information**

- Piper version: piper-0.6-1.fc35.noarch

- Distribution: Fedora

- Device: Logitech MX Anywhere 3

 In:
/usr/share/libratbag/logitech-MX-Anywhere-3.device
is

[Device]
Name=Logitech MX Anywhere 3
DeviceMatch=bluetooth:046d:b025;usb:046d:4090
Driver=hidpp20

But in 
/usr/share/piper/piper.gresource

Doesn't exist MX Anywhere 3

![mx-devices](https://user-images.githubusercontent.com/31983315/150003113-61175d70-6d7c-44d5-8d86-193f63181cf0.png)

**Comment by fmontefalcone** [comment]
Hi! I'm still getting the 404 image on piper when configuring my MX MASTER 3. 
Can somebody please help?
Running ubuntu 20.04.03 LTS.
and using it via Bluetooth.
Thanks
![Screenshot from 2022-02-18 18-43-47](https://user-images.githubusercontent.com/71709058/154765301-98217042-9416-432b-9b04-e37c99b19c6a.png)

**Comment by Danmga** [comment]
I have the same issue Dec 15, 2022

**Comment by Danmga** [comment]
Still can;t solve mouse with 404 sign when trying to configure logitech mx master 3s on Pop Os desktop

**Comment by staticssleever668** [comment]
There may be a chance your distro ships an older version of Piper where this hasn't been implemented yet. This has been added in Piper 0.5.

Still, it's not like it impacts functionality in any way, it's just a visual issue.
