### ISSUE TITLE
Cannot build on Ubuntu 18.

### ISSUE THREAD

**Issue by JontomXire** [libratbag/piper#582]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Piper version: Latest
- Distribution: Ubuntu 18
- Device: Not relevant
- Kernel version (ex. `uname -srmo`): Linux 4.15.0-112-generic x86_64 GNU/Linux

**Describe the bug**
I cannot build for Ubuntu 18.

I started trying to use the Flatpak install, but although it was reported as successfully installed I could not find the program itself.

I tried building from source. After adding dependencies that were not listed I got the message:

```
   *********************** WARNING ****************************
    *                 (   )(                                   *
    *         (\-.     ) (  )    ratbagd found in $PATH is too *
    *         / _`> .---------.  old and  will  not  work with *
    * _)     / _)=  |'-------'|  this version of Piper. Please *
    *(      / _/    |O   O   o|  update libratbag/ratbagd.     *
    * `-.__(___)_   | o O . o |                                *
    ************************************************************
```

I uninstalled the distribution provided ratbagd and tried to build it from source. I got the message:

    meson.build:1:0: ERROR: Meson version is 0.45.1 but project requires >= 0.53.0.

I draw the line at trying to compile meson from source as this is a rabbit hole that will only get deeper and deeper until i end up installing 20 different pieces of software from source. And probably fail.

**To Reproduce**

Install Ubuntu 18.
Install all the build tools etc from distribtuon repos.
Follow the build instructions in the README.md.

**Logs**

None.

**Additional context**

If you can specify a checkout tag that is compatible with Ubuntu 18 and the distro install of ratbagd, please let me know.

**Comment by FFY00** [comment]
You need to install https://github.com/libratbag/libratbag first.

**Comment by JontomXire** [comment]
Read further down where I said...

I uninstalled the distribution provided ratbagd and tried to build it from source.

It got scrambled in with the compiler error from piper - I will fix that.

**Comment by FFY00** [comment]
Ah, sorry. Too much things hapenning in my head. That is because your meson version is too old, but I've just merged a patch that reverts the changes that introduced that, please `git pull` and try again :blush:

**Comment by JontomXire** [comment]
Thanks for that.

I then installed the following dependencies:

libevdev-dev
libjson-glib-dev
libunistring-dev
libsystemd-dev
check
valgrind

It now wants python 3.6. I have python 3 installed but it is version 3.5.

I would love to upgrade to Ubuntu 20, really, but when I upgraded from 16 to 18 it shafted my system (it now boots REALLY slowly). And so do not feel confident upgrading to 20. A fresh install would be problematic too. Over the years I have done so many customisations which I did not keep notes of and so cannot remember what they were or how I did them. So I really need to be able to build for Ubuntu 18.

Sorry to be such a pain.

**Comment by FFY00** [comment]
No worries, unfortunately there is nothing I can do there, IIRC we use Python 3.6 features. Python 3.5 is really old and is EOL now, it won't receive any support or upgrades, so really should update it as soon as you can. Python 3.9 is already out for comparison :confused:

**Comment by JontomXire** [comment]
I just had a look at whether I could install python 3.6 easily and...it is already installed.
```
Configuring org.freedesktop.ratbag1.conf using configuration
Dependency python-3.6 found: NO
Dependency python3 found: NO

meson.build:568:4: ERROR: Dependency "python3" not found

A full log can be found at /home/me/Development/libratbag/builddir/meson-logs/meson-log.txt
me@Shikamaru:~/Development/libratbag$ sudo dpkg -l | grep python3.6
ii  libpython3.6:amd64                                               3.6.9-1~18.04ubuntu1.1                           amd64        Shared Python runtime library (version 3.6)
ii  libpython3.6-minimal:amd64                                       3.6.9-1~18.04ubuntu1.1                           amd64        Minimal subset of the Python language (version 3.6)
ii  libpython3.6-stdlib:amd64                                        3.6.9-1~18.04ubuntu1.1                           amd64        Interactive high-level object-oriented language (standard library, version 3.6)
ii  python3.6                                                        3.6.9-1~18.04ubuntu1.1                           amd64        Interactive high-level object-oriented language (version 3.6)
ii  python3.6-minimal                                                3.6.9-1~18.04ubuntu1.1                           amd64        Minimal subset of the Python language (version 3.6)
```
Running "python --version" reports python 2.7! WTF? I removed it and after almost 1GB of freed disk space (why was it even on my system?) running "python --version" now reports...python 2.7.

Python is a bit like Japanese ivy it appears. I managed to fully remove it and now it appears I don't have python on my system at all, despite dpkg -l reporting both python 3.5 and 3.6 being present.

**Comment by JontomXire** [comment]
I was missing python3-dev. Now missing swig <sigh>. So many dependencies!

**Comment by JontomXire** [comment]
libratbag is now built. When I try to build Piper I get:

`Native dependency 'pygobject-3.0' not found`

According to a search of the internet this is obtainable by installing python-gi-dev. However installing that results in installing python 2.7 as a dependency! I have python3-gi installed, but there is no python3-gi-dev package at all.

**Comment by muzena** [comment]
@JontomXire 
https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git

**Comment by JontomXire** [comment]
Thankyou so much.
