### ISSUE TITLE
New app icon?

### ISSUE THREAD

**Issue by bertob** [libratbag/piper#590]
The current app icon doesn't really follow the HIG, would you be intersted in help with a new one?

Here's a quick experiment redrawing the current metaphor in the platform style:

![image](https://user-images.githubusercontent.com/1908896/97807334-77f64b00-1c60-11eb-8e17-80de337772a6.png)

**Comment by FFY00** [comment]
Yeah, definitely. I think that icon looks good.

@whot @stephanlachnit thoughts?

**Comment by stephanlachnit** [comment]
Love it

**Comment by whot** [comment]
heh, yes, very nice. and definitely better than my 10 minute icon ;)

**Comment by bertob** [comment]
Alright, I'll clean it up a bit and make a PR then :)
