### ISSUE TITLE
Piper does not open. Installed ratbag and piper from source.

### ISSUE THREAD

**Issue by vince5001** [libratbag/piper#599]
**Information**
- `ratbagd` version (`ratbagd --version`): 0.15
- Piper version: Version: 0.5.1+git454-aef0567~ubuntu21.04.1
- Distribution: Debian 10
- Device: Keyboard G915 TKL
- Kernel version (ex. `uname -srmo`): Linux 4.19.0-12-amd64 x86_64 GNU/Linux

**Describe the bug**
Installed ratbag and piper, issue is that Piper does not open at all.

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

1. Double click on Piper
2. Does nothing, does not open.

**Logs**
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: PixArt HP USB Optical Mouse
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 03f0:134a
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c545 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c545 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c545 is a Logitech receiver, not a device. Ignoring...
DBus server ready

```

**Additional context**

**Comment by FFY00** [comment]
What is your kernel version?

**Comment by vince5001** [comment]
> What is your kernel version?

Linux 4.19.0-12-amd64 x86_64 GNU/Linux

**Comment by stephanlachnit** [comment]
Can run piper from the terminal? What is its output?
Also `Version: 0.5.1+git454-aef0567~ubuntu21.04.1` look like it's from the Ubuntu PPA, correct?

**Comment by vince5001** [comment]
> Can run piper from the terminal? What is its output?
> Also `Version: 0.5.1+git454-aef0567~ubuntu21.04.1` look like it's from the Ubuntu PPA, correct?

Traceback (most recent call last):
  File "./piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'

**Comment by stephanlachnit** [comment]
Ok, this indicates that you run this from the source / build directory, that the exectubable doesn't find the Python module is to be expected. You need to run `piper.devel` instead.

**Comment by vince5001** [comment]
> Ok, this indicates that you run this from the source / build directory, that the exectubable doesn't find the Python module is to be expected. You need to run `piper.devel` instead.

Running from source tree, using local files
Traceback (most recent call last):
  File "./piper.devel", line 39, in <module>
    from piper.application import Application
  File "/home/anon/Desktop/piper/piper/application.py", line 4, in <module>
    from .window import Window
  File "/home/anon/Desktop/piper/piper/window.py", line 8, in <module>
    from .mouseperspective import MousePerspective
  File "/home/anon/Desktop/piper/piper/mouseperspective.py", line 5, in <module>
    from .buttonspage import ButtonsPage
  File "/home/anon/Desktop/piper/piper/buttonspage.py", line 6, in <module>
    from .mousemap import MouseMap
  File "/home/anon/Desktop/piper/piper/mousemap.py", line 12, in <module>
    gi.require_version("Rsvg", "2.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available

**Comment by stephanlachnit** [comment]
You have missing dependencies. Please run `sudo apt install python3-gi python3-gi-cairo python3-lxml python3-evdev gir1.2-rsvg-2.0`

**Comment by vince5001** [comment]
> You have missing dependencies. Please run `sudo apt install python3-gi python3-gi-cairo python3-lxml python3-evdev gir1.2-rsvg-2.0`

Ok, now piper can open and says Cannot find any device. What is the step from here ?

**Comment by stephanlachnit** [comment]
Probably missing USB ID. Can you run `lsusb`?

**Comment by vince5001** [comment]
> Probably missing USB ID. Can you run `lsusb`?

Bus 001 Device 003: ID 046d:c545 Logitech, Inc.

**Comment by stephanlachnit** [comment]
Requires libratbag/libratbag#1099 to be merged.
