### ISSUE TITLE
Logitech G915: Limitted Assigment of G-Keys 1 & 2

### ISSUE THREAD

**Issue by MJWootton** [libratbag/piper#605]
**System Info**
- Piper version: 0.5.1
- Distribution: Ubuntu 20.04
- Device: Logitech G915 (keyboard)
- Kernel version: 5.4.0-56-generic

**Description**
The Logitech G915 has five programmable "G-Keys". From the Piper interface, one can assign an arbitrary function to G3, G4, and G5 without issue, but G1 and G2 (labelled as button 0 and button 1 in Piper & ratbagctl) can only be assigned as right or left mouse clicks, even though the G915 is a keyboard. However, these keys are dealt with correctly in ratbagctl.

**Comment by Coecoenut** [comment]
> **System Info**
> 
>     * Piper version: 0.5.1
> 
>     * Distribution: Ubuntu 20.04
> 
>     * Device: Logitech G915 (keyboard)
> 
>     * Kernel version: 5.4.0-56-generic
> 
> 
> **Description**
> The Logitech G915 has five programmable "G-Keys". From the Piper interface, one can assign an arbitrary function to G3, G4, and G5 without issue, but G1 and G2 (labelled as button 0 and button 1 in Piper & ratbagctl) can only be assigned as right or left mouse clicks, even though the G915 is a keyboard. However, these keys are dealt with correctly in ratbagctl.

The same issue applies to the G1 and G2 keys of the Logitech G815 keyboard

**System Info**
    * Piper version: 0.5.1

**Comment by Coecoenut** [comment]
The same issue applies to the G1 and G2 keys of the Logitech G815 keyboard

**System Info**

* Piper version: 0.5.1
* Distribution: Debian 10
* Device: Logitech G815 (keyboard)
* Kernel version: 4.19.171-2

**Comment by Techognito** [comment]
Still an issue in Piper 0.7

**Comment by staticssleever668** [comment]
Fixed by #536.

**Comment by MJWootton** [comment]
Cheers!
