### ISSUE TITLE
Map secondary mousewheel on MX-Master3

### ISSUE THREAD

**Issue by jounathaen** [libratbag/piper#617]
I have a Logitech MX-Master3 Mouse which has a secondary mousewheel. This by default handles left/right scrolling but maybe I'd like to map it to e.g. zoom-in/zoom-out.

At least for the MX3 there is no such setting in piper. The buttons of this mouse are mappable however.

**Comment by FFY00** [comment]
I am not sure the device allows to do this.

**Comment by 8836290** [comment]
On Ubuntu 20.04 and 20.10 the Thumb wheel (the one the user access with thumbnail), on Chrome it scrolls up and down and on VLC increases and decreases volume, but inverted than it does with scroll wheel. So it seems the Thumb wheel can be interpeted differently on at least two different programms. If piper allows map on one direction to Ctrl+ for zoom in and Ctrl- (default shortcut keys for zoom in/out on browsers) it would do the job.If it is in general the maping could be the default ones on gnome Alt+Super+= and Alt+Super+-

According to this [Logitech MX Master 3 manual page4](https://www.manua.ls/logitech/mx-master-3/manual?p=4)  the user can

1.Adjust thumbwheel scrolling speed, and direction 
2.Enable app-specific settings for the thumbwheel

On [page 6](https://www.manua.ls/logitech/mx-master-3/manual?p=6) of the same manual it is clear that per applicaiton the Thumb wheel can return zoom fuctionality. So it can be done but it is an applicaiton specific feature thrugh Logitech options software.

**Comment by FFY00** [comment]
It can definitely be done in software, but I am pretty sure it can't via the hardware. This project just configures hardware, it does not do any kind of processing to input events in software. So you can remap the actions like you would with literally any other device in software.

**Comment by jounathaen** [comment]
Hmm, didn't know that piper does a hardware remapping. But then of course it is out of scope for this project.
I guess I'll close this then.
