### ISSUE TITLE
Adding a .svg file for the glorious model d mouse ?

### ISSUE THREAD

**Issue by le-grand-mannitout** [libratbag/piper#622]
Hello,
I get a 404 error screen when I open piper (mouse model : Glorious Model D) :

![Screenshot_2021-02-21_15-56-11](https://user-images.githubusercontent.com/61273515/108628862-57dfd700-745d-11eb-9011-516bf72db201.png)

Is it possible to add a .svg file for the glorious model d mouse (if this is the reason of the 404 screen)?

Thanks,

**Comment by FFY00** [comment]
Yes, it is but the maintainers don't really have time. Feel free to open a PR :confused:

**Comment by le-grand-mannitout** [comment]
I understand...
I am gonna try to do it. 
Thank you !

**Comment by neveratdennys** [comment]
I would really prefer to have button config support on the model D, algough even existing support is very nice to have. Somehow my model D's default "foward" "backward" side buttons are not working in the OS. Thank you!
