### ISSUE TITLE
Support for Logitech G Pro X Superlight

### ISSUE THREAD

**Issue by pschichtel** [libratbag/piper#623]
**Is your feature request related to a problem? Please describe.**
libratbag already supports the device device on master (https://github.com/libratbag/libratbag/commit/104543fdf19f6108b46d311d4a14f32731868261), but piper shows the 404 image.

**Describe the solution you'd like**
It would be nice to have a proper image for that mouse very similar to the image of the G Pro.

**Comment by FFY00** [comment]
I would, however the maintainers currently don't have time to do this :confused:
Feel free to open a PR.

**Comment by pschichtel** [comment]
Is there any guide on how the images are being made?
