### ISSUE TITLE
No picture of mouse - no key combinations possible

### ISSUE THREAD

**Issue by GAZ63** [libratbag/piper#625]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Piper version: 0.4
- Distribution: Linux Mint 20.1 Cinnamon
- Device: Logitech M720 Thriathlon
- Kernel version (ex. `uname -srmo`): `Linux 5.4.0-66-generic x86_64 GNU/Linux`

**Describe the bug**
Picture of mouse is missing. Showing rat with "404" sign. Also I can't assign key combinations.
![Piper M720](https://user-images.githubusercontent.com/80415936/110701845-fb690f80-81f1-11eb-89f1-03832ac60b54.png)

**Comment by HuangLiPang** [comment]
Got the same thing here. @GAZ63 How did you fix it?
