### ISSUE TITLE
G102 Lightsync doesnt show on piper

### ISSUE THREAD

**Issue by nakobejo** [libratbag/piper#628]
im using Logitech G102 Lightsync and doesnt appear on piper
![gambar](https://user-images.githubusercontent.com/49896401/112992165-2233b980-9192-11eb-9006-ef36034e22f0.png)

my distro is Fedora Linux 33 KDE, im using piper from Fedora repository
lsusb show
![gambar](https://user-images.githubusercontent.com/49896401/112992371-4f806780-9192-11eb-91de-376458f0e50f.png)

**Comment by FFY00** [comment]
Hi, can you tell me you kernel version? You can run `uname -a` and paste the output.

**Comment by nakobejo** [comment]
![gambar](https://user-images.githubusercontent.com/49896401/113556170-46761700-9626-11eb-856b-53c315115c23.png)
5.11
seems like this is because i running older version of libratbag
on my archlinux system it detected
