### ISSUE TITLE
Any way to set default mouse wheel settings MX Master 3 (2?)

### ISSUE THREAD

**Issue by DFF-fred** [libratbag/piper#633]
**Is your feature request related to a problem? Please describe.**
Every time I start the computer the mouse wheel does 3 lines x 3 lines, I love free wheeling! :-)
**Describe the solution you'd like**
Set default mouse wheeling behavior settings rather than click on the default button to set it up.

**Describe alternatives you've considered**
Overall I am a happy user. No problem is you say "cannot do" :-)

Thank you.

**Comment by harshitgoel96** [comment]
Hi, this is bit off topic, but I can not use piper with my MX Master 3, I installed piper from apt install command.
can you please confirm if you are able to use Piper with Mx Master 3

**Comment by DFF-fred** [comment]
Sure, this is a screenshot of Piper downloaded from Fedora's packages using dnf:
![Screenshot from 2021-07-21 09-30-54](https://user-images.githubusercontent.com/5652441/126421428-685b8be4-b086-4a89-b17d-ba318a38df42.png)

**Comment by FFY00** [comment]
We do not support this, have a look at https://github.com/pwr-Solaar/Solaar instead.

**Comment by DFF-fred** [comment]
Indeed! Thank you very much. I thought my MX 3 wheel was actually damage and it was 'recently' switching between rachet and free wheeling, but it was set to 10 (values go between 0 to 50). My MX 2 broke 2 times under warranty (the pointer doesn't move, but buttons work) and I was getting a bit disappointed by Logitech quality on those. 
Turns out it was a setting issue on the MX 3. For the MX 2 I need to dismantle it, it seems to be a common problem, just been lazy.

Well thank you.
