### ISSUE TITLE
ratbag not found or not exectuable

### ISSUE THREAD

**Issue by Siamaster** [libratbag/piper#634]
I ran the build command commands on ubuntu 18.04:

 meson builddir --prefix=/usr/
 
The Meson build system
Version: 0.45.1
Source dir: /home/siamaster/Development/piper
Build dir: /home/siamaster/Development/piper/builddir
Build type: native build
Project name: piper
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program ratbagd found: NO

meson.build:20:4: ERROR: Program(s) ['ratbagd'] not found or not executable

A full log can be found at /home/siamaster/Development/piper/builddir/meson-logs/meson-log.txt

full log does not have much more information.

**Comment by stephanlachnit** [comment]
Run `sudo apt install ratbagd` and try it again. You are missing run-time dependencies.
