### ISSUE TITLE
Trust GXT 144 Gaming Mouse does not show

### ISSUE THREAD

**Issue by smith558** [libratbag/piper#635]
**Information**
- `ratbagd` version: 0.14
- Piper version: 0.5.1
- Distribution: Ubuntu 20.10
- Device: Lenovo Yoga-510 laptop
- Kernel version: `Linux 5.8.0-48-generic x86_64 GNU/Linux`
- Device: `Bus 001 Device 003: ID 145f:026d Trust GXT 144 Gaming Mouse` (https://www.trust.com/en/product/22991-gxt-144-rexx-ergonomic-vertical-gaming-mouse)

**Describe the bug**
Trust GXT 144 Gaming Mouse not detected.

**Comment by smith558** [comment]
Un-supported driver.

**Comment by eadmaster** [comment]
I am interested in this as well, can this be moved over (libratbag)[https://github.com/libratbag/libratbag/issues] to investigate the protocol?
