### ISSUE TITLE
I'm not sure if this is bug but i download that program only for 2 left button clicks but when i change my right button to left my left buton become right my mouse is logitech g102

### ISSUE THREAD

**Issue by bobi4b** [libratbag/piper#639]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Piper version: 
- Distribution: 
- Device: 
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`

**Describe the bug**

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**

**Comment by staticssleever668** [comment]
This doesn't follow the template, but I'll answer anyway.
Not a bug, Piper intentionally shows a different dialog for changing the first two buttons.
If you really need, this can be accomplished with ratbagctl.
