### ISSUE TITLE
Mapped autorepeat with optional delay

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [libratbag/piper#642]
**Describe the solution you'd like**
Please add auto-repeat feature. 
For example i want to use additional mouse button as a left mouse click in auto-repeat mode until it release it. 
I.e. 
normal left mouse click is just left mouse click 
Pressing additional button is left mouse click auto-repeat with optional delay until release.

**Comment by staticssleever668** [comment]
Closing in favor of #748
