### ISSUE TITLE
Piper and ratbagctl not detecting Logitech G102 Lightsync

### ISSUE THREAD

**Issue by kelptaken** [libratbag/piper#651]
**Information**
- `ratbagd` version: 0.13
- Piper version: 0.4
- Distribution: KDE neon 5.22.2
- Device: Logitech G102 Lightsync
- Kernel version (ex. `uname -srmo`): `Linux 5.8.0-59-generic x86_64`

**Describe the bug**
Piper shows that no devices are connected. `ratbagctl list` shows `No devices available.` `ratbagctl -vvv list` shows the same error.

**To Reproduce**
1. Open Piper
2. See the error message 'No devices are connected'
or
2. Execute 'ratbagctl list'
3. See the error message 'No devices available.

**Logs**
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c092
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c092
ratbag debug: New device: ELAN1200:00 04F3:309F
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04f3:309f
DBus server ready

```

**Comment by Netherquark** [comment]
update both piper and ratbag to version 0.5.1 and 0.15 respectively. that might help.

**Comment by FFY00** [comment]
You need at least libratbag 0.15.

https://github.com/libratbag/libratbag/commit/02226d04280964f69fe5b58bc88232ec697abc70

**Comment by GioBego** [comment]
Many versions later and g102 is still not detected for me. (Manjaro KDE, Piper 0.7, libratbag 0.17, kernel 6.3.5)

**Comment by sbrl** [comment]
Got this problem with the closely related lightsync G203 on:

```bash
$ ratbagctl --version
0.17
$ ratbagd --version
0.17
// piper version:
0.7
$ ratbagctl list
No devices available.
```

![Piper_2024-10-25_23:10:17_001_a51ef94](https://github.com/user-attachments/assets/1d33076a-17c3-4f32-8484-b8726b38c488)


....which is after 0.15.

**Comment by 0xOmarAdel** [comment]
> Got this problem with the closely related lightsync G203 on:
> 
> $ ratbagctl --version
> 0.17
> $ ratbagd --version
> 0.17
> // piper version:
> 0.7
> $ ratbagctl list
> No devices available.
> ![Piper_2024-10-25_23:10:17_001_a51ef94](https://github.com/user-attachments/assets/1d33076a-17c3-4f32-8484-b8726b38c488)
> 
> ....which is after 0.15.


I have the same versions and my device is Logitech g102 and it's not detected either
