### ISSUE TITLE
Logitech G305, Device not found

### ISSUE THREAD

**Issue by MattRGX** [libratbag/piper#654]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Piper version: 0.4
- Distribution: Debian 10 Buster
- Device: Logitech G305
- Kernel version (ex. `uname -srmo`): `Linux 4.19.0-17-amd64 x86_64 GNU/Linux`
- 
**Describe the bug**
I've managed to install Ratbagd and piper from backports. My G305 is plugged through an USB hub. But when i launch piper, i get "impossible to find any device. Make sure that your device is supported and plugged"

**To Reproduce**
Install Ratbagd and piper and try to connect a G305.

**Comment by PotatoAlienOf13** [comment]
Same issue here. I remember piper being able to find this mouse earlier.

**Comment by Rodscaloppe** [comment]
I also had this problem and now mine does not open.

**Comment by FFY00** [comment]
You need at least Linux 5.4 IIRC.

**Comment by muzikbike** [comment]
It recognised my G305 yesterday and still remembers what I had each key mapped to, but it appears to have suddenly forgotten about its existence today even though it still works fine with the wired G402 I also have plugged in.

**Comment by staticssleever668** [comment]
>  but it appears to have suddenly forgotten about its existence today
Judging by "You need at least Linux 5.4 IIRC" message above, this is a different issue. If it triggers for you again, feel free to open a new issue!

**Comment by KraXen72** [comment]
for me, closing piper, `sudo systemctl restart ratbagd`, launching piper solved the issue.
