### ISSUE TITLE
To scroll one screen per mouse wheel notch 

### ISSUE THREAD

**Issue by robkam** [libratbag/piper#659]
**Feature request**
It's frustrating to have to scroll long documents or web pages only a few lines at a time when scrolling a screen at a time would be more ergonomic. 

**Solution**
On the Piper buttons tab add an option for the scroll wheel to scroll instead by one screen per mouse wheel notch. Also there needs to be a way to easily toggle this off and on as some programs won't work with it, (e.g. to zoom in/out)

In Windows control panel there is this option for this. 
![contol_panel](https://user-images.githubusercontent.com/4047844/126375738-ac535aeb-16e9-481b-9af6-47b80e998ec1.png)

**Comment by FFY00** [comment]
That is out of scope for this project. This project is focused on configuring the hardware itself, and that functionallity is implemented in software. Please ask your desktop environment / window manager.
