### ISSUE TITLE
G102 usb:046d:c092 404

### ISSUE THREAD

**Issue by Netherquark** [libratbag/piper#663]
**Information**
- `ratbagd` version (`ratbagd --version`): 0.15
- Piper version: 0.5.1
- Distribution: Ubuntu 21.04
- Device: Logitech G102 Lightsync (G203)
- Kernel version (ex. `uname -srmo`): `Linux 5.11.0-25-generic x86_64 GNU/Linux`

**Describe the bug**
For some reason, on my desktop my G102 shows up as usb:046d:c084, and it shows up as usb:046d:c092 on my laptop. Everything works perfectly on my desktop, and everything is also functional on my laptop, but the graphical rendition of the mouse is replaced with a rat holding a 404 sign. I think this is a pretty easy fix? But im relatively unfamiliar with the code of this project so i won't be able to PR.

**Screenshots**
![image](https://user-images.githubusercontent.com/65618735/126860688-2c7e4fd2-5227-48e6-8239-685f0bc21dc2.png)

**Comment by FFY00** [comment]
Right, the ID was added in https://github.com/libratbag/piper/commit/bf2444ac0f0a2cd7cdfe2e391765b2342e164231 but we haven't had a release since.

@stephanlachnit do you want to do a release, or shall I?

**Comment by stephanlachnit** [comment]
I don't have much time atm so if you could do it I would appreciate it :)

**Comment by Netherquark** [comment]
![image](https://user-images.githubusercontent.com/65618735/128295149-941953bc-8c50-437f-9cab-c990dfe99da6.png)

works properly now. thanks. closing issue.
