### ISSUE TITLE
Exception ModuleNotFoundError: No module named 'piper', caused by typo in symlink in latest versions 

### ISSUE THREAD

**Issue by ocumo** [libratbag/piper#664]
**Information**
- `ratbagd` version (`ratbagd --version`): 0.16
- Piper **versions**:  `0.5.1+git467-4dd9e4f-202107271832~ubuntu20.04.1`
  and **also** previous version:  `0.5.1+git466-6131de0-202107242216~ubuntu20.04.1`
  and **at least one more before it**.
- Distribution: Ubuntu 20.04
- Kernel version (ex. `uname -srmo`): Linux 5.8.0-63-generic x86_64 GNU/Linux

EDIT: _Updated because new version released 28.07.2021 ALSO has the bug_

**Describe the bug**
Piper crashes as soon as it is run, with the Exception **ModuleNotFoundError: No module named 'piper'**. This happens after the latest updates and possible earlier versions too (see versions above), and the cause is very obvious:
The deb package creates a symlink that doesn't exist, simply because it has a TYPO in it:

  ```
  ls -l /usr/lib/python3/dist-packages/piper
  lrwxrwxrwx 1 root root 39 Jul 25 12:36 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8./site-packages/piper
  ```

**Note the extra dot in the middle of the path: `/python3.8./`**

Without that dot, all is OK.

EDIT: _It is possible that the typo has been already present in previous updates, see #661_.

**To Reproduce**
To reproduce, just install (or upgrade to) any of these versions of piper:
`0.5.1+git467-4dd9e4f-202107271832~ubuntu20.04.1` or the previous one `0.5.1+git466-6131de0-202107242216~ubuntu20.04.1` and then run `piper` from the console.
If you issue the command
`ls -l /usr/lib/python3/dist-packages/piper`
you get a broken link, with the typo, even if you previously had it correct:
`lrwxrwxrwx 1 root root 39 Jul 28 17:39 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8./site-packages/piper`

**WORKAROUND**: This is **not** a permanent fix, because it won't survive a system/package upgrade. The fix needs to be done in the piper installer.
IF your python version is 3.8, then the correct path should exist: Just re-do the symlink:

`$ sudo ln -nsf /usr/lib/python3.8/site-packages/piper /usr/lib/python3/dist-packages/piper`

Hopefully this typo is only for those who have python 3.8, which is my case
`$ python3 -V
Python 3.8.10`

**Comment by ocumo** [comment]
The latest version, released today, `0.5.1+git467-4dd9e4f-202107271832~ubuntu20.04.1` **ALSO has the bug**.

I had made a temporary fix, per above, all was OK.  After my update today, **_the installer (again) created a broken link_**:
```
$ ll /usr/lib/python3/dist-packages/piper
lrwxrwxrwx 1 root root 39 Jul 28 17:39 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8./site-packages/piper
```
and of course, piper **crashes** immediately after entering `piper` on the console, with the same reported error.

Once again, **after manually fixing the broken link, per above instructions, piper is working again**.

**Comment by devonallie** [comment]
On flatpak (0.6) I get no such issue, sorry.

**Comment by skauertz** [comment]
I confirm I am having the same issue also with Python 3.6.

- Piper version 0.5.1+git467-4dd9e4f-202107271833~ubuntu18.04.1
- Ubuntu Studio 18.04
- Python 3.6

Incorrect link:
`lrwxrwxrwx 1 root root 39 Jul 28 07:40 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.6./site-packages/piper
`

while `/usr/lib/python3.6/site-packages/piper` does well exist.

Thanks @ocumo for pointing this out, I would not have figured out why Piper isn't working anymore.

**Comment by ocumo** [comment]
Ok, today's release `focal 0.5.1+git467-4dd9e4f-202108021932~ubuntu20.04.1` has been installed via `apt upgrade` and it did not destroy the existing symlink (which I was manually fixed after being broken by the previous upgrade):

`lrwxrwxrwx 1 root root 38 Aug  3 17:06 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8/site-packages/piper/`

And piper runs without the aforementioned crash.

I cannot tell if this is the definitive fix but at least the installer this time did not destroy the existing link: either it didn't touch it, and because it was OK then it works, or it did re-write it and it did it well.  Thus I don't know whether it would work fine in these cases:

- a) piper is already installed and it has a bad link
- b) piper is not installed: first time installation.
- c) Other versions of Python and/or distribution.

Sadly, there are still other issues (Unable to modify MX Vertical configuration through Piper #666) , which prevent me from getting it to work properly: that bug is still present. That's another thread...

@skauertz, you are welcome, glad I could help. Perhaps you could report when you get an update for ubuntu 18.04 ?  Thanks a lot

**Comment by skauertz** [comment]
I just installed that same update on 18.04 with Python 3.6, and it did fix the broken link under `/usr/lib/python3/dist-packages/piper` and piper is working as usual again. I did not fix the link manually before, the installer corrected it itself.

**Comment by ocumo** [comment]
Yet a newer version: 0.5.1+git468-3389ae8-202108181303~ubuntu20.04.1, upgraded without the originally reported issue.
