### ISSUE TITLE
Support for Mars Gaming MM4

### ISSUE THREAD

**Issue by Qjammer** [libratbag/piper#676]
**Describe the solution you'd like**
Add support for Mars Gaming MM4.

**Describe alternatives you've considered**
Based on the changes on [Qjammer/libratbag@marsgaming-mm4](https://github.com/Qjammer/libratbag/tree/marsgaming-mm4), I have added the svgs to support this mouse in [Qjammer/piper@marsgaming-mm4](https://github.com/Qjammer/piper/tree/marsgaming-mm4)

**Additional context**
I will be opening a PR soon with support for this mouse.
This is how the button config page looks like at the moment.
![image](https://user-images.githubusercontent.com/11245037/133982501-88f62c2a-c36b-4329-8ffa-7080192f868a.png)

Related: https://github.com/libratbag/libratbag/issues/1199

**Comment by Qjammer** [comment]
Question: There is a button on the underside of the mouse. It is used for changing the current profile. The manufacturer's config tool does not let you change it. Should we allow it? Additionally, how would you represent such a button? I added a striped circle and button path, but I'm open to suggestions.

**Comment by FFY00** [comment]
I think so. For the SVG, I think it is probably fine as-is, as the people with the device should be able to figure it out.
