### ISSUE TITLE
Save button is not obvious

### ISSUE THREAD

**Issue by whot** [libratbag/piper#69]
Comment from @hadess when I showed him piper at GUADEC: the save button to actually write to the mouse is not obvious enough, needs to be differently placed.

**Comment by Hjdskes** [comment]
Would replacing the image with simply "Save" work? I'm not sure where else we can place it to make it more obvious.

Also, in case you didn't notice, the button has a tooltip to explain its purpose.

**Comment by whot** [comment]
There are a couple of comments here: first, the icon is "save to disk", that was confusion number one. Second, it's not in-your-face obvious that you have to press it to write to the device. So replacing it with a Save or "Write to device" or so is likely better. The last thing: maybe we should highlight/flash/something the button whenever the profile is dirty?

**Comment by bentiss** [comment]
I still believe we should not explicitely ask the user to actually send the configuration to the mouse. I wish we could just monitor the events and automatically send the commit when there is no widget interactions for 1 second for instance

**Comment by Hjdskes** [comment]
> automatically send the commit when there is no widget interactions for 1 second for instance

Two immediate problems come to mind with this approach:

1. timeouts are not discoverable
2. what happens if the user wants to abort the changes they made?

> There are a couple of comments here: first, the icon is "save to disk", that was confusion number one. Second, it's not in-your-face obvious that you have to press it to write to the device. So replacing it with a Save or "Write to device" or so is likely better. The last thing: maybe we should highlight/flash/something the button whenever the profile is dirty?

Gotcha, I can replace the image with a label. Highlighting the button sounds interesting too, I'll add it to the list.

**Comment by whot** [comment]
If you can't do that in the widgets, you could do this in the dbus bindings. Set a dirty flag on the device whenever you change a property, you can than query it.  That's the quick and dirty approach :)

> what happens if the user wants to abort the changes they made?
That's what the cancel buttons are for, once you click "OK" on a button, there's no abort anymore. If we remove the Save button altogether, then the expectation of being able to abort at any time goes away.

**Comment by bentiss** [comment]
Also, automated commit is basically what happens under the other operating system with the proprietary applications.

The only situation where it could be an issue is if you remap buttons and forget to have a primary click somewhere. This can be detected and we can then either automatically switch the other primary physical button (think left/right button type) to primary logical button action. We could also show a popup warning the user.

**Comment by Hjdskes** [comment]
> That's what the cancel buttons are for, once you click "OK" on a button, there's no abort anymore. If we remove the Save button altogether, then the expectation of being able to abort at any time goes away.

> Also, automated commit is basically what happens under the other operating system with the proprietary applications.

Oke, that sounds good. Just tell me whether you want me to rework the save button or to go with a timeout based approach (if so, how long should it be?)

**Comment by whot** [comment]
anytime switching between the GtkStack is time to commit, otherwise I'd say after 3 seconds?

**Comment by bentiss** [comment]
> anytime switching between the GtkStack is time to commit, otherwise I'd say after 3 seconds?

Porbably also right after validating in a popup (LED, button action) would be a good time given that the user has already the choice to validate or cancel

**Comment by Hjdskes** [comment]
Alright, I'll work on that when I get time to :)

**Comment by hadess** [comment]
There are a couple of things that could be done to make it more obvious:
- Disable the button when nothing has been changed
- Make the button blue like the default button in dialogues ('suggested-action' style IIRC) when something has been changed
- Use a label rather than an icon if there isn't one that matches exactly. 'Apply' seems like a good label to use.
- Ask the user whether to apply all the settings to the mouse before exiting (same pattern as when you exit gedit with an unsaved file)
- Add a preference to automatically save to the mouse when exiting (default to yes?)
- Show activity through a spinner and in-app notifications. See the HIG and core GNOME applications for examples.

**Comment by Hjdskes** [comment]
Thanks, I'll likely go with some of those now and improve the rest when I have time left, or after GSoC.

**Comment by hadess** [comment]
I still think the icon needs to be changed to a textual representation. An icon is only useful if the symbol is already known. Having to decipher an icon, however playful it is, is not something you want users doing while using your software. Gedit doesn't use this downward arrow metaphor anymore, just a button that says "Save".
