### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by BloodyIron** [libratbag/piper#701]
I can't seem to find a website for piper, so when I look at the tags (not actually releases for some reason), I can't see what was actually done in each release. In similar vein to any other open source project, can we please get fully fleshed-out release notes for releases going forward? I'm also unsure where to find any sort of feature roadmap (like macros).

That would be greatly appreciated :)

**Comment by staticssleever668** [comment]
We do announcements with release notes on the [freedesktop.org input-tools mailing list](http://lists.freedesktop.org/archives/input-tools/)
https://github.com/libratbag/libratbag#mailing-list

> I'm also unsure where to find any sort of feature roadmap (like macros).

There isn't one, really, I think most contributors just work on whatever they think is most important at the time.

**Comment by BloodyIron** [comment]
Reading through email lists for release notes is not release notes. There's no realistic way to tell which of those threads on the linked page has actual info (or not) about what made it into a release.

I'm specifically asking for something that's actually intended for humans to ingest efficiently.

**Comment by yjfguhd** [comment]
I had to do an Issues search to find this thread to find where the release notes are. Just copy the notes from that mailing list email into a changelog file in the repo.
