### ISSUE TITLE
meson.build cannot see pygobject-3.0 dependency

### ISSUE THREAD

**Issue by incredibun** [libratbag/piper#704]
I was missing the "pygobject-3.0" but then found it - unfortunately I am not sure what to do at this point.

So how do I get the meson.build to see pygobject-3.0, so I can ultimately get Piper to work correctly? 
(At present I am seeing a 404 message)

I am running Linux Mint 20.2 Cinnamon (5.0.7)

This is as far as I got:

Project name: piper

Project version: 0.6

Host machine cpu family: x86_64

Host machine cpu: x86_64

Program ratbagd found: YES (/usr/bin/ratbagd)

Found pkg-config: /usr/bin/pkg-config (1.6.3)

Found CMake: /usr/bin/cmake (3.16.3)

Run-time dependency pygobject-3.0 found: NO (tried pkgconfig and cmake)

meson.build:56:4: ERROR: Dependency "pygobject-3.0" not found, tried pkgconfig and cmake

A full log can be found at /home/jo/piper/builddir/meson-logs/meson-log.txt

computer:~/piper$ cd

computer:~$ sudo apt-file search pygobject-3.0

python-gi-dev: /usr/include/pygobject-3.0/pygobject.h

python-gi-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/pygobject-3.0.p
!
![2021-12-25_12-45](https://user-images.githubusercontent.com/67307252/147390633-35c82b2a-e061-405f-ba8d-2e9226382cfa.jpg)
c

**Comment by whot** [comment]
[this post](https://askubuntu.com/questions/1301038/how-to-install-pygobject-3-0-in-ubuntu-for-compiling-a-project-with-meson) says it's `python-gi-dev` that you need, that should install `pygobject-3.0.pc` which meson looks for.
