### ISSUE TITLE
Integration of Discord Shortcuts

### ISSUE THREAD

**Issue by TomBayne** [libratbag/piper#705]
DIscord supports control via external software using the [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide). This should be utilized to allow Mute/Deafen/PTT to be bound to macro keys on peripherals.

This would replicate functionality of Logitech G-Hub, which allows macro keys, DPI switching keys, etc to be bound to 'Discord Mute Self' or 'Discord Deafen Self'. This functionality in Logitech G-Hub is essentially seamless and just requires the user to accept an initial confirmation screen within Discord when this functionality is enabled for the first time.

**Comment by staticssleever668** [comment]
Currently libratbag is only a configuration tool, so this is out of scope of the project. This would
