### ISSUE TITLE
Having troubles

### ISSUE THREAD

**Issue by shag00** [libratbag/piper#706]
I have installed piper (ver 0.6) from the Ubuntu respository for Kubuntu 21.10 and added and installed the ratbag ppa (https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git) 

I have 2 devices that should appear (supported by ratbag),  the logitech G603 mouse and G513 keyboard. When I open Piper I have a graphic of a keyboard but no labels and can't see a way to change to a graphic of a mouse. I am able to change the light show on the keyboard.

On the top line of the window I appear to be missing the Profile button that appears on your screenshots.

**Comment by staticssleever668** [comment]
If there is no button to go to the device list, then it means that your mouse is not recognized, even though it should be. If you still have this problem, please, open a new issue filling up the given template.

Profile changing feature seems to be unavailable for your keyboard. If official software supports it, you can make a separate issue for it. :)
