### ISSUE TITLE
Logitech MX Vertical mouse buttons mismatched

### ISSUE THREAD

**Issue by Doomsdayrs** [libratbag/piper#710]
**Information**
- Piper version: doomsdayrs:patch-1
- Device: Logitech MX Vertical

**Describe the bug**
Back and auxiliary button mismatched.

![image](https://user-images.githubusercontent.com/38189170/148883840-b2483b60-a142-4998-b781-8cb5ec8fc3e2.png)

You can see that the buttons are traced incorrectly.

**Comment by whot** [comment]
Can you send a PR to fix this please, file should be `svgs/logitech-mx-vertical.svg`

**Comment by Doomsdayrs** [comment]
> Can you send a PR to fix this please, file should be `svgs/logitech-mx-vertical.svg`

I do not know how to edit an SVG to do so.

Is there a specific ID or tag I have to find and replace?

**Comment by whot** [comment]
inkscape should be able to do all that, the important bits are in the object IDs, see the [README](https://github.com/libratbag/piper/blob/master/data/svgs/README.md). If they're swapped, you should only need to change the names for the leader lines
