### ISSUE TITLE
Support for Logitech G935

### ISSUE THREAD

**Issue by DavidCooper** [libratbag/piper#717]
Can you add support for the Logitech G935 headset? I would be happy to do the development if I had a little direction about supporting headsets, since I don't see any supported thus far.

**Comment by Doomsdayrs** [comment]
What could be supported?

**Comment by DavidCooper** [comment]
It has buttons and LEDs that would be great to manage

**Comment by staticssleever668** [comment]
Implemented in https://github.com/libratbag/libratbag/pull/984
