### ISSUE TITLE
Add option to disable mouse buttons

### ISSUE THREAD

**Issue by Ustin** [libratbag/piper#718]
My mouse have additional "forward/back" buttons I sometimes press accidentaly. 

I do not need these buttons and I would like to disable them completely. 

Windows software provided by manufacturer is able to do it, but piper misses this option. 

I can remap them to one of less intrusive function like sideways scrolling, but I can't set it "do nothing when I press this button". 

So, my request is to add "nothing" option to mouse button function selection.

**Comment by staticssleever668** [comment]
Duplicate of #247, fixed by #849.
