### ISSUE TITLE
changing a resolution should not change the active one

### ISSUE THREAD

**Issue by bentiss** [libratbag/piper#72]
When testing a device that has resolution 2 active, changing any other resolution in the Resolution panel and committing to the device changes the active resolution back to the first one (0).

I do not have this behavior with ratbagctl so I guess piper must be overwriting the active resolution...

**Comment by Hjdskes** [comment]
I cannot reproduce this here. In any case, no code related to resolutions (`resolutionspage.py`, `resolutionrow.py`) calls `RatbagdResolution::set_active` at any time. 

Are you sure you weren't doing something else?

**Comment by Hjdskes** [comment]
Also this seems to conflict with https://github.com/libratbag/piper/issues/81

**Comment by whot** [comment]
I'd prefer the #81 behaviour, it provides immediate feedback to what the user just set. @bentiss any comments?

**Comment by Hjdskes** [comment]
Closed because #132 is merged.
