### ISSUE TITLE
macros are not recognized by xev

### ISSUE THREAD

**Issue by ghost** [libratbag/piper#722]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Piper version: 0.6
- Distribution: Void Linux
- Device: Logitech G Pro
- Kernel version (ex. `uname -srmo`): `Linux 5.15.14_1 x86_64 GNU/Linux`

**Describe the bug**
Macros are not recognized by the system as keys. I have F7, F8 and F9 set to the two side buttons and the scroll wheel click. This works _sometimes_ but most of the time xev does not produce the function codes. Instead, xev outputs something like this (F7):

```
FocusOut event, serial 34, synthetic NO, window 0x2200001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 34, synthetic NO, window 0x2200001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 34, synthetic NO, window 0x2200001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  ```

When removing the macros, the keys are recognized as by xev as F7, F8 and F9. When remapping the buttons with Piper to other function keys, such as F4, F5 and F6, those will stop being recognized as well.

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

Steps to reproduce the behavior:
1. Replicate the setup
2. Run xev

**Comment by staticssleever668** [comment]
I don't think this is a problem with libratbag, instead it's likely a problem with the mouse itself.
To confirm this set the macro in official mouse software and try if it works in Linux then.
(I can see that reporting user is already a @ghost, so you if whoever reads this now has the same problem, please, check my theory).
