### ISSUE TITLE
Glorious Wireless D Not Showing

### ISSUE THREAD

**Issue by NBZion** [libratbag/piper#727]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Piper version: 0.6
- Distribution:  Archlinux
- Device: Glorious D Wireless
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`

**Describe the bug**
I tried the wired and wireless plugi, none of them showed up in piper and yet i checked the supported devices and i saw that it was supported.
**To Reproduce**
N/A
**Logs**
N/A

**Additional context**
Already Shown Above

**Comment by NBZion** [comment]
Sorry Kernel Version is Linux 5.16.4-arch1-1 x86_64 GNU/Linux
 though im about to convert to xanmod

**Comment by jiriks74** [comment]
@luke512 
How is it with Model D? Will there be support for button remaping or is this state (dpi, polling rate, rgb) the final one?

**Comment by staticssleever668** [comment]
Device support depends on libratbag: https://github.com/libratbag/libratbag/issues/1299
