### ISSUE TITLE
G815 G1 and G2 keys locked to change handedness

### ISSUE THREAD

**Issue by SeanMcnabb** [libratbag/piper#735]
When trying to change the key mappings for the G1 and G2 keys on the G815 keyboard, it will only allow a change between the device's handedness. The G3-G5 keys are okay though.

![Screenshot from 2022-03-13 13-23-10](https://user-images.githubusercontent.com/25807635/158073771-c4759821-3ee3-4479-85f9-4d0d87367fb5.png)

**Comment by sethseth6** [comment]
This is happening to me too.

**Comment by ImNuro** [comment]
I have the same issue with my g815.
Cant send a pic rn, sry

**Comment by starsforeveryone** [comment]
I can confirm this bug still exists in the latest Fedora 37 version (Piper 0.7). Very sad, since this is an otherwise awesome keyboard!

If we could just fix this bug, then the combination of OpenRGB + Piper will make the keyboard fully Linux compatible! 😎

**Comment by sTiKyt** [comment]
Still have this issue on G815 keyboard

**Comment by staticssleever668** [comment]
Hi! It's been fixed but it's not in a release yet. I've been meaning to make one for a while but I lack time.
In the meantime, you can do it with ratbagctl - the command line interface of libratbag.

**Comment by gregfr** [comment]
Hello, I just bought a G815 and have the same problem, how can I use ratbagctl to map to something else?
Thanks in advance
Regards
