### ISSUE TITLE
displaying the scale for changing the resolution can be masked

### ISSUE THREAD

**Issue by bentiss** [libratbag/piper#74]
Clicking on resolution 4, at the end of the list often pops up the resolution scale to interact outside of the current view.

The user needs to scroll down to access it, which is counter intuitive.

We need to make sure the scale is always visible after a click by moving all the rest up (with an animation if possible, or @jimmac is going to complain).

**Comment by Hjdskes** [comment]
I cannot reproduce this, maybe this got fixed since it was reported. @bentiss If you can still reproduce this, please reopen this issue.
