### ISSUE TITLE
Dependency "pygobject-3.0" not found in Ubuntu 22.04

### ISSUE THREAD

**Issue by XinranZhao** [libratbag/piper#741]
When building in Ubuntu 22.04 with meson, got the message:
> $ meson builddir --prefix=/home/sam/local/lib/piper/build
> The Meson build system
> Version: 0.56.2
> Source dir: /home/sam/local/lib/piper/source
> Build dir: /home/sam/local/lib/piper/source/builddir
> Build type: native build
> Project name: piper
> Project version: 0.6
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Program ratbagd found: YES (/usr/local/bin/ratbagd)
> Found pkg-config: /usr/bin/pkg-config (0.29.2)
> Found CMake: /snap/bin/cmake (3.23.1)
> Run-time dependency pygobject-3.0 found: NO (tried pkgconfig and cmake)
> 
> meson.build:56:4: ERROR: Dependency "pygobject-3.0" not found, tried pkgconfig and cmake

I found many threads online suggesting "sudo apt install pygobject3-devel" or "sudo apt install python-gi-dev", I tried but from all of them I got

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package xxxxxx

what is the package name for pygobject-3.0 in Ubuntu 22.04? 

I also tried "pip install PyGObject", it tells me it already exists:

> Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (3.42.0)
> Requirement already satisfied: pycairo>=1.16.0 in /usr/lib/python3/dist-packages (from PyGObject) (1.20.1)

Many thanks! Really appreciate your help..

**Comment by eli-schwartz** [comment]
https://packages.ubuntu.com/jammy/python-gi-dev

This package should exist, it's listed in Ubuntu 22.04's web listing. Its filelist says it installs the pkg-config dependency file you need.

**Comment by avi951** [comment]
While compiling Blueman 2.3.5,
I got an error like :
 ```
checking for pygobject-3.0 >= 3.27.2... no
configure: error: Package requirements (pygobject-3.0 >= 3.27.2) were not met:

Package 'pygobject-3.0', required by 'virtual:world', not found
```

It resolves by installing **python-gi-dev**
