### ISSUE TITLE
Drop all indices from the GUI

### ISSUE THREAD

**Issue by Hjdskes** [libratbag/piper#75]
E.g. "LED X: <mode>", or the number of the resolution in the list, etc. None of this is interesting to the user, except for profiles perhaps because we need the index to differentiate those.

**Comment by bentiss** [comment]
> except for profiles

well, on some devices, you can even set a name on the profile. Ratbagd currently doesn't export it, but this is something that we should eventually allow.
For non writable names, we can just have hardcoded "profile N"

**Comment by whot** [comment]
https://github.com/libratbag/libratbag/issues/266

**Comment by Hjdskes** [comment]
Closed through #91.
