### ISSUE TITLE
 problem detecting g733 headphones

### ISSUE THREAD

**Issue by tridoxx** [libratbag/piper#750]
**Information**

- `ratbagd version: 0.16
- Piper version: 0.6-2
- Distribution: pop_os
- Device: logitech g733 
- Kernel version: Linux 5.17.5-76051705-generic x86_64 GNU/Linux
**Describe the bug**

**To Reproduce**
Hi, I'm trying to use piper to configure my logitech g733 headset, but piper jumps directly and only shows the mouse, as I read in the instructions, if it doesn't detect another logitech device, it jumps directly to the one it finds, so I don't know if Suddenly I'm missing something or what could it be, since the headsets work fine, and I found a library where the light can be managed by command line, so it should be working, on the computer but maybe the piper doesn't recognize it, I am connecting using the receiving device, and I have also tried it by cable, and in the list of devices if the supported piper devices are listed, it is listed, I am attentive, thank you very much

**Logs**
Please start the daemon with verbosity and reproduce the issue.

$ ratbagd --verbose=raw
ratbagd error: Bus name is taken, another instance of ratbagd is already running.

**Comment by warboy2408** [comment]
im having the same problem however  im seeing:
ratbag debug: No data file found for 046d:0ab5

**Comment by tridoxx** [comment]
> im having the same problem however im seeing: ratbag debug: No data file found for 046d:0ab5

i found the solutión, you need to add, the file with the name of the headset in the files, and it work, but when i restart the config dissapeer

**Comment by staticssleever668** [comment]
Implemented in https://github.com/libratbag/libratbag/pull/1197
