### ISSUE TITLE
Disable button?

### ISSUE THREAD

**Issue by SrBrahma** [libratbag/piper#751]
**Is your feature request related to a problem? Please describe.**
I don't use 3 buttons of my mouse, and sometimes I accidentally press them and what they do annoys me (like going back).

**Describe the solution you'd like**
Have a "None" option, so the button becomes useless.

**Describe alternatives you've considered**
For now I set them all as middle click, but not the best solution. Surprises me that this software doesn't have this option.

**Comment by 1Spinne** [comment]
+1

**Comment by madmadman** [comment]
I want this too. Been having issues

**Comment by staticssleever668** [comment]
Duplicate of #498.
