### ISSUE TITLE
'Ratbagd' object has no attribute '_devices'

### ISSUE THREAD

**Issue by twwn** [libratbag/piper#757]
Latest git versions of both piper and ratbag, piper won't start:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/piper/ratbagd.py", line 268, in _on_properties_changed
    object_paths = [d._object_path for d in self._devices]
AttributeError: 'Ratbagd' object has no attribute '_devices'. Did you mean: 'devices'?
```

**Comment by kimhongsu** [comment]
I have the same problem.
```
❯ piper
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 268, in _on_properties_changed
    object_paths = [d._object_path for d in self._devices]
AttributeError: 'Ratbagd' object has no attribute '_devices'
```
I have installed piper from PPA(ppa:libratbag-piper/piper-libratbag-git)
```
Get:7 http://ppa.launchpad.net/libratbag-piper/piper-libratbag-git/ubuntu focal/main amd64 lur-command amd64 0.16-1+git1844-07b4031~ubuntu20.04.1 [8,756 B]
Get:8 http://ppa.launchpad.net/libratbag-piper/piper-libratbag-git/ubuntu focal/main amd64 libratbag-tools all 0.16-1+git1844-07b4031~ubuntu20.04.1 [4,292 B]
Get:9 http://ppa.launchpad.net/libratbag-piper/piper-libratbag-git/ubuntu focal/main amd64 piper all 0.7+git490-7f9834c~ubuntu20.04.1 [183 kB]
```

**Comment by terminatorul** [comment]
Same here, I installed piper and libratbag from OpenSUSE Tumbleweed repository

**Comment by terminatorul** [comment]
timothy@localhost:~> zypper info libratbag-tools ratbagd piper
Loading repository data...
Reading installed packages...


Information for package libratbag-tools:
----------------------------------------
Repository     : Main Repository (OSS)
Name           : libratbag-tools
Version        : 0.16-2.5
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 99.9 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libratbag-0.16-2.5.src
Upstream URL   : https://github.com/libratbag/libratbag
Summary        : Utilities for configuring gaming mice
Description    : 
    libratbag is a configuration library for gaming mice. It provides a
    generic way to access the various features exposed by these mice and
    abstracts away hardware-specific and kernel-specific quirks.

    This subpackage contains the ratbag utilities allowing to inspect and configure
    mice.


Information for package ratbagd:
--------------------------------
Repository     : Main Repository (OSS)
Name           : ratbagd
Version        : 0.16-2.5
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 233.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libratbag-0.16-2.5.src
Upstream URL   : https://github.com/libratbag/libratbag
Summary        : Service granting access to the configuration options of gaming mice
Description    : 
    libratbag is a configuration library for gaming mice. It provides a
    generic way to access the various features exposed by these mice and
    abstracts away hardware-specific and kernel-specific quirks.

    This subpackage contains the daemon managing access to the hardware.


Information for package piper:
------------------------------
Repository     : Main Repository (OSS)
Name           : piper
Version        : 0.7-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 1.7 MiB
Installed      : Yes
Status         : up-to-date
Source package : piper-0.7-1.1.src
Upstream URL   : https://github.com/libratbag/piper
Summary        : Configuration UI for gaming mice
Description    : 
    Piper is a GTK+ application to configure gaming mice. It is a graphical frontent
    to the ratbagd DBUS daemon which provides the actual configuration support for the
    devices.

**Comment by staticssleever668** [comment]
Duplicate #551
