### ISSUE TITLE
Repeat press req? 100ms, 250ms, 50ms etc.

### ISSUE THREAD

**Issue by Ferosuchiki** [libratbag/piper#765]
I'd like to see a function where I can add the macro mode for lets say, my Q. When I then press my dedicated mouse key it pressed the key "Q" at a set interval. 50ms, 100ms, 250ms or whatever you want it for :) I have severe artrisis and used that function on a program called AutoHotKey but I've done the change from Windows to Linux (Ubuntu) as its more stable for my usage. I use it for gaming and I've confirmed from the game developer that its legal :)

**Comment by staticssleever668** [comment]
libratbag and Piper are just tools to configure mice. If the mouse doesn't support such actions, we can't do them either. I think your only way out is finding some kind of AHK alternative.

Closing because I don't know of any mice supporting this.

**Comment by staticssleever668** [comment]
Hm, actually, sounds like this may be possible on Logitech mice: #748. Well, this is a duplicate issue then.
