### ISSUE TITLE
Logitech G915 - First two macro buttons registering as mouse clicks?

### ISSUE THREAD

**Issue by redness2** [libratbag/piper#766]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Piper version: 0.6
- Distribution: PopOS
- Device: G915 Keyboard
- Kernel version (ex. `uname -srmo`): 5.18.10-76051810-generic x86_64

**Describe the bug**
The first two macro buttons (G1 and G2) are registering as mouse clicks. I can't set a key that isn't left or right click mouse button.
![Screenshot from 2022-07-24 07-20-31](https://user-images.githubusercontent.com/40418303/180625995-4b6fa1a6-823a-4ece-82c4-7e3ed5983f43.png)

Menu that shows up when clicking to configure the G1 or G2 key.
![image](https://user-images.githubusercontent.com/40418303/180628092-203ecdcd-8340-417e-865f-ff1867b64c97.png)

I don't know if this is working as intended but I feel like it isn't as I can't do much with these two keys.

**Comment by DevDorrejo** [comment]
Same issue with openSUSE Tumbleweed

**Comment by jason-pollock** [comment]
Same here on Ubuntu

- version (ratbagd --version): 0.16
- Piper version: 0.7
- Distribution: Kubuntu 22.04
- Device: G915 Keyboard
- Kernel version (ex. uname -srmo): Linux 5.15.0-47-generic x86_64 GNU/Linux

**Comment by schoenid** [comment]
The same as  https://github.com/libratbag/piper/issues/735
Seems to be on every keyboard (g810, g910, g915 ... more?)

**Comment by staticssleever668** [comment]
#735
