### ISSUE TITLE
Steelseries Rival 5 support?

### ISSUE THREAD

**Issue by Sikeen** [libratbag/piper#767]
Is there a possibility for Rival 5 support in the future?

I use a Rival 5 mouse myself and would really like to be able to change the buttons and RGBled´s

**Comment by staticssleever668** [comment]
libratbag/libratbag#1252 :)

**Comment by Sikeen** [comment]
> [libratbag/libratbag#1252](https://github.com/libratbag/libratbag/issues/1252) :)

oh hell yeah

thanks:]
