### ISSUE TITLE
Unmet dependencies when installing piper on Ubuntu 22.04

### ISSUE THREAD

**Issue by joangog** [libratbag/piper#768]
**Information**
- `ratbagd` version: Cannot get installed
- Piper version: Cannot get installed
- Python version: 3.10.4
- Distribution: Ubuntu 22.04
- Device: Lenovo Legion 7s
- Kernel version: Linux 5.15.0-25-generic x86_64 GNU/Linux

**Issue Description**
When installing piper on a fresh installation of Ubuntu 22.04 with the command "sudo apt install piper" I get the following error message:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  python3-evdev : Depends: python3 (< 3.9) but 3.10.4-0ubuntu2 is to be installed
>  python3-lxml : Depends: python3 (< 3.9) but 3.10.4-0ubuntu2 is to be installed
>                 Recommends: python3-bs4 but it is not going to be installed
>                 Recommends: python3-html5lib but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

It seems that the problem may be my version of python but I'm not sure if downgrading is a sensible thing to do as it might break my system. I also tried installing it from the Ubuntu Software app but the same issue persists. Does anyone have a solution?

**Comment by whot** [comment]
fwiw, anything `apt install` is a ubuntu-specific issue that we cannot address upstream. We just say we need "python-evdev" but the rest is up to the distribution (or `pip` if you install with pip). Please file an issue in launchpad for this, thanks.
