### ISSUE TITLE
Profile cycle buttons must apply across all profiles

### ISSUE THREAD

**Issue by whot** [libratbag/piper#78]
If we assign a button to profile cycle up or some other profile switching, that mapping must be assigned across all profiles. Otherwise clicking the same button will eventually land you in a profile with no way out.

**Comment by Hjdskes** [comment]
Isn't this something that we should do in ratbagd/libratbag?

**Comment by whot** [comment]
See my comment in #82, this isn't something that a configuration proxy like ratbagd should enforce so we need this in the GUI

**Comment by Hjdskes** [comment]
[This comment](https://github.com/libratbag/piper/issues/82#issuecomment-321788303) also applies here.
