### ISSUE TITLE
heavily needed addition of mouse scroll speed

### ISSUE THREAD

**Issue by petebryan04** [libratbag/piper#780]
my  first ever issues coming to ubuntu was that unlike windows there was no mouse scroll speed. i couldnt set my scroll pixels to higher numbers. no matter how much googling and searching, it cannot be found. i feel like the implementation of this on piper would give it a nice edge, since there arent any other applications that work with gaming mice that have this feature.

**Comment by staticssleever668** [comment]
I haven't heard of any mice having such a configuration option.
Some configuration utilities, like those from sinowealth (used on older Glorious mice, for example), just expose the Windows option in their GUI.
I think this is a limitation of X11, and we can't do anything about it. You can work around this by using IMWheel, but, in my experience, it's not great. In the end I gave up on this.
You may have better experience on Wayland.
