### ISSUE TITLE
Logitech G915 TKL is not recognized by piper (connected using: lightspeed)

### ISSUE THREAD

**Issue by PalmTamino** [libratbag/piper#783]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Piper version: 0.7
- Distribution: Fedora
- Device: 
- Kernel version (ex. `uname -srmo`): `5.19.6-200.fc36.x86_64`

**Describe the bug**
My keyboard "Logitech G915 TKL" is not shown in piper, it is connected with Lightspeed.

**Additional info**
My Mouse G502 Lightspeed is shown for example though.

**Comment by Techognito** [comment]
Same with full size g915

**Comment by staticssleever668** [comment]
Tracked on libratbag's side: https://github.com/libratbag/libratbag/issues/1178.
In short, this device will only be configurable in wired mode until support for receiver is implemented in the Linux kernel.
