### ISSUE TITLE
Logitech Powerplay is not shown in Piper

### ISSUE THREAD

**Issue by PalmTamino** [libratbag/piper#784]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Piper version: 0.7
- Distribution: Fedora
- Device: 
- Kernel version (ex. `uname -srmo`): `5.19.6-200.fc36.x86_64`

**Describe the bug**
My keyboard "Logitech Powerplay" is not shown in piper, it is connected via USB.

**Additional info**
My Mouse G502 Lightspeed is shown for example though.

**Comment by staticssleever668** [comment]
Duplicate #719.
