### ISSUE TITLE
Logitech G935 Headset is shown in piper, but can't be controlled

### ISSUE THREAD

**Issue by PalmTamino** [libratbag/piper#785]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Piper version: 0.7
- Distribution: Fedora
- Device: 
- Kernel version (ex. `uname -srmo`): `5.19.6-200.fc36.x86_64`

**Describe the bug**
It shows in piper, though the thumbnail is a rat, and everything else too, just not being able to control anything: 

![grafik](https://user-images.githubusercontent.com/36358673/188332343-8cce5681-c686-4672-9602-224909356102.png)

![grafik](https://user-images.githubusercontent.com/36358673/188332427-b7a59345-4631-461c-8bcb-461143e59f91.png)

**Additional info**
My Mouse G502 Lightspeed is shown for example though.

**Comment by staticssleever668** [comment]
Sorry for this being unanswered for so long.
I think in addition to butotns, LEDs are also supposed to be configurable (https://github.com/libratbag/libratbag/issues/977#issuecomment-628799293).
What does ratbagd say in verbose mode? (`sudo systemctl stop ratbagd.service && sudo ratbagd --verbose`)
