### ISSUE TITLE
flake8 should be marked as required : false

### ISSUE THREAD

**Issue by Apteryks** [libratbag/piper#787]
This directive:

https://github.com/libratbag/piper/blob/dcec480417c601fcf9c684b2af4552e889eed8dd/meson.build#L122

causes the build to fail if flake8 is missing, instead of skipping the flake8 test, as intended.

**Comment by Apteryks** [comment]
> It is actually meant to be like so, see #549 ([d5b27d4](https://github.com/libratbag/piper/commit/d5b27d4b51999330f2568bc75cc10f6d092bf2cc)). Maybe it would be better to explicitly make it `require : true` to avoid confusion...

Then the condition checking if flake8 is found at https://github.com/libratbag/piper/blob/master/meson.build#L122 is no longer required.

**Comment by staticssleever668** [comment]
Yeah, you are right, I noticed that only after replying to you... However, it's not like it matters in any way (other than that it may cause confusion like here). Still, you can drop a PR if you want.
