### ISSUE TITLE
Is it possible to run piper on WSL?

### ISSUE THREAD

**Issue by igonro** [libratbag/piper#808]
I was able to run `ratbagd` and `piper` on WSL, but it says "Cannot find any devices". Maybe it is impossible to detect the mouse hardware through WSL? I just wanted to know if there is a workaround to use this on Windows, because I hate the Logitech software. Thanks!

**Comment by igonro** [comment]
I just read #391 and I wanted to ask another question. Would it be possible to configure the mouse using `piper` on a Linux VM? If so, then the configuration would be also available on Windows since it's saved on the mouse memory.

**Comment by PieQuest** [comment]
+1
This would be awesome. I just tried to do the same thing and was able to get the Piper GUI working on WSL 2. I can't seem to get the actual bin for libratbag / libratbagd running. Seems to hit a wall since WSL doesn't support systemctl. I don't know if this would ever work, since I doubt WSL and the host can share the bus for the mouse.

**Comment by staticssleever668** [comment]
> I just read #391 and I wanted to ask another question. Would it be possible to configure the mouse using `piper` on a Linux VM? If so, then the configuration would be also available on Windows since it's saved on the mouse memory.

Yes, it would.

**Comment by staticssleever668** [comment]
To the original question: basically, it should be a matter of allowing WSL to get raw access to the devices, making our D-Bus daemon ratbagd use it and expose itself on the bus, allowing Piper to connect to it.

I don't think there is anything WSL-specific we need to do, it just comes down to whether WSL supports these steps or not.
For such reason I'll close this issue.
However, feel free to describe the steps here if you were able to do it, it may make sense to put it on our wiki. :)
