### ISSUE TITLE
Piper translated over to my Windows setup.

### ISSUE THREAD

**Issue by umuligt** [libratbag/piper#809]
***LINUX TO WINDOWS***

Im just gonna jump right into this, and delete the template, because i have none of the information.

Basically i recently installed windows instead of linux, and i had Piper on my Linux setup
I had my mouse keys bound to some numbers, and when i changed... my binds were still there, but i don't want them anymore.

What do i do?

**Comment by staticssleever668** [comment]
Piper is a device configuration utility, it doesn't it's some kind of scripting utility for creating keyboard shortcuts like AutoHotkey, for example.
So, your solution is installing official configuration utility for your mouse and reset mouse settings.
