### ISSUE TITLE
[General Question] How to use custom SVG?

### ISSUE THREAD

**Issue by jaamivstheworld** [libratbag/piper#815]
Basically what the title says. I have my own SVG I would like to use. How would I go about configuring piper to use it?

**Comment by staticssleever668** [comment]
Hello! You will need to be able to build Piper from source first.
Then it gets easy, you put the SVG under `data/svgs/` in the source code, add corresponding entry to `data/svgs/svg-loopup.ini` and recompile. 
To test if your SVG is correct, you can run tests: `meson test -Cbuilddir`.

**Comment by jaamivstheworld** [comment]
Worked like a charm! Thank you so much.
