### ISSUE TITLE
Steam Deck Piper is missing the libratbag that is not easy to install

### ISSUE THREAD

**Issue by MadogPL** [libratbag/piper#825]
Hallo

Steam Deck allows to install Piper, but Piper requires libratbag to operate, and it's not available in flatpak "Discover" program.
Steam warns that even if I unlock all the functionalities of the deck (sudo, pacman, whatever that means), It might get overwritten in next system update. 

Make instruction how to install those things safely on Steam Deck or make the libratbag avaliable with flatpak to install.

**Comment by staticssleever668** [comment]
Answered in https://github.com/libratbag/libratbag/issues/1401.
