### ISSUE TITLE
Logitech G502-HERO (wired) says it cannot find device, i got all the newset versions 

### ISSUE THREAD

**Issue by JcnesFucksWomen** [libratbag/piper#826]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Piper version: 
- Distribution: 
- Device: 
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`

**Describe the bug**

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**

**Comment by staticssleever668** [comment]
Hello, please, fill out the template.
