### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by stickybeard** [libratbag/piper#827]
I was looking for a quick "on-the-fly" solution for figuring out what profile I last used and for changing profiles without having to open piper or a terminal each time.  I suspect native implementation of something like this would be near impossible, so I guess that makes this an FYI for anyone in a similar situation.

I came across a (KDE Plasma) widget called [Scriptinator](https://github.com/tubbadu/Scriptinator).  I cobbled together a few crude bash scripts to notify the active profile and increment or decrement the profile.  Now I have an icon on my task manager that I can mouse over to notifies me of the active profile, I can mouse wheel up or down to increment/decrement the active profile, and if I click the widget, it opens Piper.

**Comment by staticssleever668** [comment]
Hello, did you know that Piper is just a front-end for libratbag, which also has a command-line interface?

`ratbagctl <device name> profile active get`
`ratbagctl <device name> profile active set 0`
(both are zero-based)

To find the device name you can use `ratbagctl list`. As the device name you can use either the auto-generated name, or the name shown on the right.
