### ISSUE TITLE
build dependencies link is dead

### ISSUE THREAD

**Issue by SamuelBorn** [libratbag/piper#831]
**Describe the bug**
The link to the build dependencies on the installation wiki [build dependencies](https://github.com/libratbag/piper/blob/master/.circleci/config.yml#L4) is missing.

I am speaking of this link https://github.com/libratbag/piper/blob/master/.circleci/config.yml#L4

![image](https://user-images.githubusercontent.com/58636569/213887571-4111fec7-26cd-4425-93ae-b2a28c6cc93c.png)

**Comment by staticssleever668** [comment]
Commit where this file was dropped: 348f29587c7748da908fd321c97d74c05616026b
File as of the commit: https://github.com/libratbag/piper/blob/f8bcd1fe7183b17c4c93418b9a958a1a02381141/.circleci/config.yml

**Comment by staticssleever668** [comment]
I have removed the link.
https://github.com/libratbag/piper/wiki/Installation/_compare/b8c1930cc92d9efa29814339a4abf6067f954768...edd748d2239615ec0eeedc3ef23c530d999b9021
