### ISSUE TITLE
Do you plan on updating the flatpak package?

### ISSUE THREAD

**Issue by KierPrev** [libratbag/piper#858]
There had been many new supported devices and patches recently.

The last one is 6 months old. And I can not recommend it to my friends, not everyone compiles from source.

Even the Arch package is that old!

**Comment by staticssleever668** [comment]
Hi, see the second section of https://github.com/libratbag/piper/issues/832#issuecomment-1407412783. We are getting there.

**Comment by KierPrev** [comment]
Ohh right. Thanks for your work :)
