### ISSUE TITLE
Logitech G502 X DPI doesn't change

### ISSUE THREAD

**Issue by amanda-santini** [libratbag/piper#865]
**Information**

Correct. I'm on 5.10 (Debian Stable)
- `ratbagd` version (`ratbagd --version`): 0.15-1+b1
- Piper version: 0.5.1-1
- Distribution: Debian Stable
- Device: Logitech G502 X
- Kernel version (ex. `uname -srmo`): `Linux 5.10.0-21-amd64 x86_64 GNU/Linux`

**Describe the bug**
Hi there. I'm a 3D artist with severe tendonitis on my fingers, and I bought 4 Logitech mice to test their comfort levels.
I liked two of them, the G403 and the G502X. The G403 works well in Piper, but the G502X does not. Initially Piper wouldn't even recognize it, but I took a look at issue #388 and I was (kind of?) able to make it recognize the mouse, using the following configuration at `/usr/share/libratbag/logitech-g502-X.device`:
`[Device]
Name=Logitech G502 X
DeviceMatch=usb:046d:c099
Driver=hidpp20
`

The "DeviceMatch" line I got it from lsusb.

My main problem with Piper and the G502X (the mouse I liked the most) is that Piper can't seem to change the mouse DPI. I tested multiple values, not of them work, it's like only the default DPI values work.

**To Reproduce**

1. Connect mouse;
2. Open Piper;
3. Try to change the DPI values to something outrageous like 100 or 20,000;
4. Cycle through the DPIs via mouse buttons;
5. Doesn't work.

**Logs**
Please start the daemon with verbosity and reproduce the issue.
---------------------------------------------------

OK, so I was in the middle of starting the log process, and I think I got it working. 

Here's what I found:
1. When first installed/opened, Piper said my G502X was with a "Profile 1" activated;
2. I thought of creating a new profile to see if it works;
3. After clicking "New Profile", instead of it creating "Profile 2" it created "Profile 0";
4. "Profile 1" doesn't exist anymore;
5. This "Profile 0" now works fine, I can change the DPI in Piper and it correctly loads that DPI when I change it with the mouse button.

I wonder if this is a case of updating Piper (or whatever is under the hood) to automatically do the profile steps the first time the user runs it.
Also, it would be nice to add the G502X profile like I did.
Also also, it would be great to actually have a proper image of the mouse to load. Right now I have no idea which button is which.

If any of these have been fixed on newer versions of the program, please disregard this issue.

Kind regards

![image](https://user-images.githubusercontent.com/3147833/228379638-a7b4c8c8-6c19-4bc3-8854-143cfcbaa989.png)

**Comment by staticssleever668** [comment]
I'm not sure about the profile thing, but the rest is implemented in the last versions of libratbag and Piper
https://github.com/libratbag/libratbag/pull/1355
#794
