### ISSUE TITLE
Change profiles names

### ISSUE THREAD

**Issue by zShxck720** [libratbag/piper#867]
So now the Profiles names are Profile 0, Profile 1 etc.
I would like the possibility to rename Profile 0 to the name of the program I need that specific profile. 

i.e.:
Lets say I use Profile 2 for playing Tomb Raider I would like to rename Profile 2 into Tomb Raider. So I don't end up with 20 profiles which I don't know which I use for which program/game.

Thanks and keep up the good work!

**Comment by staticssleever668** [comment]
Duplicate: #85.
Already supported on libratbag side (and so profile names can be set with libratbag), we just need to add this to Piper's UI.

I've tried taking a crack at it, but I was a bit less familiar with GTK and wasn't successful at the time. My mice don't support profile name so I myself am not too interested in this feature, but I'd gladly accept a PR for this. :)

**Comment by zShxck720** [comment]
Thank you! And Happy Easter
