### ISSUE TITLE
integration with openrazer for razer mice

### ISSUE THREAD

**Issue by Agreeable-f** [libratbag/piper#873]
**Is your feature request related to a problem? Please describe.**
I have a couple of razer mice (basilisk v3, viper 8k) that aren't supported under libratbag, but do have support from openrazer. currently piper can't detect the mice.

**Describe the solution you'd like**
i'd like to be able to use and configure my mice through piper as the tools for razer mice like razergenie don't have the ability to edit the buttons or profiles.

**Describe alternatives you've considered**
razergenie but as mentioned before it doesn't allow control of macros and button definitions

**Additional context**

**Comment by staticssleever668** [comment]
Since this depends completely on libratbag, let's close this in favor of libratbag-side issue: https://github.com/libratbag/libratbag/issues/103
