### ISSUE TITLE
Volume controls 

### ISSUE THREAD

**Issue by bossman7309** [libratbag/piper#875]
**Is your feature request related to a problem? Please describe.**
I have a logitic g502 hero and would like to change buttons G5 and G4 to control volume on my system. 

**Describe the solution you'd like**
adding support for volume controls(example: G5 is volume up and G4 is volume down)

**Comment by staticssleever668** [comment]
Duplicate: #683.
For now you can do this with ratbagctl, see this comment: https://github.com/libratbag/piper/issues/683#issuecomment-1456856759.
