### ISSUE TITLE
AW610M Mouse Support

### ISSUE THREAD

**Issue by CodingWithAnxiety** [libratbag/piper#877]
The AW610M lacks any Piper support, and due to it's lack of popularity, general support for settings in Linux.

It would be wonderful is some support for this mouse could be added.

**Comment by staticssleever668** [comment]
Device support depends on libratbag. Already reported in https://github.com/libratbag/libratbag/issues/1308.

**Comment by CodingWithAnxiety** [comment]
Thanks a bunch for referencing me in the issue. Sorry if I'm a tad misled.
