### ISSUE TITLE
new mouse support

### ISSUE THREAD

**Issue by aliilaali1** [libratbag/piper#883]
I like the application very much, but I think the only problem is that the supported devices are few. There are asus and logitech mice only. For example, it would be great if razer mice came.

**Comment by staticssleever668** [comment]
I don't think it's fair to say that we support Logitech and ASUS, we do support plenty of other devices. As this is an open source project driven by pure enthusiasm, you are always welcome to contribute. For example, when I first heard of libratbag, it didn't support mice I have had, but over time I got interested and added support for them.
For Razer mouse support there is this (stale) issue: https://github.com/libratbag/libratbag/issues/103.
