### ISSUE TITLE
Swapping Ctrl and Caps Lock with GNOME Tweaks breaks macros that use CTRL

### ISSUE THREAD

**Issue by bcpardo** [libratbag/piper#888]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Piper version: 0.7
- Distribution: Pop!_OS 22.04 LTS
- Device: Logitech G604
- Kernel version (ex. `uname -srmo`): `Linux 6.2.6-76060206-generic x86_64 GNU/Linux`

**Describe the bug**
Swapping Ctrl and Caps Lock with GNOME Tweaks breaks macros that use CTRL. The macros instead act like the swap never happened and inputs Caps Lock instead of expected CTRL.

Setting in GNOME Tweaks:
![image](https://github.com/libratbag/piper/assets/13476448/e454edf2-25a7-4cc9-af9c-cd7fde196463)

Piper GUI Settings:
![image](https://github.com/libratbag/piper/assets/13476448/6db4972a-cc7c-4ba9-ad31-480200e757ed)

**To Reproduce**
1. Enable the "Swap Ctrl and Caps Lock" option in Tweaks.
2. Create a custom keystroke macro in Piper on a mouse button, such as CTRL+C using the remapped Caps Lock button.
3. Macro will say "CAPSLOCK" instead of "CTRL".

**Comment by staticssleever668** [comment]
Piper just grabs whatever GTK sends, so, if anything, I think this should be be considered a GNOME Tweaks bug.

https://github.com/libratbag/piper/blob/1e426df58e10622095b1721e6ac88165e708a25a/piper/buttondialog.py#L300
https://github.com/libratbag/piper/blob/1e426df58e10622095b1721e6ac88165e708a25a/piper/buttondialog.py#L310
