### ISSUE TITLE
Macro creation with mixed events

### ISSUE THREAD

**Issue by cleberabreu87** [libratbag/piper#893]
Hello everybody!

Actually I would like a clarification. I'm wanting to buy a Logitech mouse, the G502 Hero and I have a question about macros.

I know that in G Hub it is possible to cascade key press events with mouse events. For example, I need to create a Macro in which the "F1" key is pressed, after 10 milliseconds the "F5" key is pressed and after 15 milliseconds the "Click" event is given on the left mouse button.

Is it possible to create a Macro this way?

**Comment by staticssleever668** [comment]
Hi! The macro editor in Piper is not too advanced, but in theory you can do that libratbag, e.g. `ratbagctl Glorious button 5 action set macro KEY_F1 t10 KEY_F5 t15 BTN_LEFT` works with Glorious Model D, however, that may not work with our Logitech driver on G502 specifically, so you can only know for sure by trying it out yourself, sorry.

**Comment by cleberabreu87** [comment]
> Hi! The macro editor in Piper is not too advanced, but in theory you can do that libratbag command line interface, e.g. `ratbagctl Glorious button 5 action set macro KEY_F1 t10 KEY_F5 t15 BTN_LEFT` works with Glorious Model D, however, that may not work with our Logitech driver on G502 specifically, so you can only know for sure by trying it out yourself, sorry.

And for key concatenation, for example "CTRL+ALT+1", is it possible to send more than one keystroke at the same time?

**Comment by staticssleever668** [comment]
libratbag is capable of that, but the driver for G502 may not. Anyway, this works on Glorious mice: `ratbagctl Glorious button 5 action set macro +KEY_LEFTCTRL +KEY_LEFTALT KEY_1 -KEY_LEFTALT -KEY_LEFTCTRL`.
