### ISSUE TITLE
Can't find any devices (Logitech G102)

### ISSUE THREAD

**Issue by YaketyYak** [libratbag/piper#897]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Piper version: 0.7
- Distribution: Manjaro Linux (KDE)
- Device: Logitech G102
- Kernel version (ex. `uname -srmo`): Linux 6.1.53-1-MANJARO x86_64`

**Describe the bug**
Piper didn't see my device. I run it, and text say "can't find any devices"

I installed Piper from Pamac, made actions from https://github.com/libratbag/libratbag/blob/master/README.md

$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Gaming KB Gaming KB
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04f3:152e
ratbag debug: New device: Gaming KB Gaming KB
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04f3:152e
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c09d
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c09d
DBus server ready

**Comment by staticssleever668** [comment]
Duplicate: #1493.
See that issues for solution for now.

**Comment by YaketyYak** [comment]
> Duplicate: #1493. See that issues for solution for now.

thanks for the answer. I forgot to say, I made actions from #1493 later, after reporting, but now I have another problem:
![Screenshot_20230921_111904](https://github.com/libratbag/piper/assets/51900899/08b61a51-a1af-4565-853e-4e83c71cae47)

Should I create new bug report?

**Comment by Mercyful-Rambler** [comment]
Ok, so I basically installed latest git version with meson and ninja, with
[https://github.com/libratbag/piper/wiki/Installation](this) and [https://github.com/libratbag/libratbag/wiki/Building-from-source](url) guides, it was hard for me, and required new knowledge to understand and do everything, but in the end of the end it worked. It's time, guys, to update the software! :)
