### ISSUE TITLE
Can't bind RIGHTSHIFT to mouse button

### ISSUE THREAD

**Issue by DarkblooM-SR** [libratbag/piper#900]
I have a G502 and as the title says I want to bind a button to the RIGHTSHIFT key but all I get is this message:

![screenshot](https://i.imgur.com/J33XzWQ.png)

Enlightenment would be appreciated.

Note: If I'm missing any log or console output, please tell me how to get it.

**Comment by staticssleever668** [comment]
Hi! This is a known issue, you can find a few workarounds in #352.
Anyway, this is a libratbag issue: https://github.com/libratbag/libratbag/issues/1205.

**Comment by DarkblooM-SR** [comment]
Thank you very much
