### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by sugoides** [libratbag/piper#902]
any way for this to be built in Windows? or any installation for the said OS?

**Comment by staticssleever668** [comment]
Hello! No, we only support Linux at the moment, and there are no plans to change that.

Technical side: two things that are in the way:
1) D-Bus - not sure if it's supported in Windows at all.
2) Linux-specific key-codes. To support other Unix-like OS I think it could be a matter of ifdef'ing Linux key-code list includes and replacing them with other OS-specific. (I want to try porting libratbag on FreeBSD but no promises).
