### ISSUE TITLE
Piper wont find my Roccat kain 120 aimo

### ISSUE THREAD

**Issue by MexicanDuke** [libratbag/piper#903]
So basicly i downloade piper and opened it, this is the result :

![image](https://github.com/libratbag/piper/assets/147701106/b194bfb0-419c-47c4-ab15-27e571e6b721)

**Comment by staticssleever668** [comment]
Not supported, also device related issues go to libratbag https://github.com/libratbag/libratbag/issues/1363

**Comment by MexicanDuke** [comment]
> Not supported, also device related issues go to libratbag [libratbag/libratbag#1363](https://github.com/libratbag/libratbag/issues/1363)

So what am i supossed to do, its my first time using github man

**Comment by MexicanDuke** [comment]
@staticssleever668

**Comment by staticssleever668** [comment]
I didn't mean to be rude if that's how it looked :)
Different devices require different drivers and libratbag is community-built, so somebody has to volunteer and write a driver for this mouse, so you're probably out of luck with libratbag for now.
