### ISSUE TITLE
ModuleNotFoundError: No module named 'gi' when using pyenv and not setting pyenv local to system

### ISSUE THREAD

**Issue by tetoNidan** [libratbag/piper#909]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Piper version: extra/piper 0.7-2 [installed]
- Distribution: Arch - Garuda
- Device: Laptop
- Kernel version (ex. `uname -srmo`): Linux 6.6.1-zen1-1-zen x86_64 GNU/Linux

**Describe the bug**

This is not so much a bug as I believe their is no solution that could be made on by the development team. Maybe this would fall better under feature request but I thought people might be able to find this information here when searching for open/closed bug reports.

If you are using `pyenv` for python version management and if you have changed your `pyenv local` version to use anything but `system` in your `$USER`'s home directory, `piper` will fail to launch from `piper.desktop` and running `piper` in the terminal. The error thrown will likely be a `ModuleNotFoundError:` followed by the name of your missing python module. In my case it was:

```
Traceback (most recent call last):
  File "/usr/bin/piper", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

This can easily be interpreted as an issue that `piper` had not properly pulled the required python dependencies which is not the case. 

If you are using `pyenv` you can check to see what version of python you are using:

1. `cd $USER`
2. `pyenv versions`

```
  system
* 3.11.3 (set by /home/$USER/.python-version)
  3.12.0
```

You can set your changed python version that you are using by:

1. `cd $USER`
2. `python local system`
3. verify changes with `pyenv versions` to see the asterisk has moved to the `sysetm`

If you by chance have changed your `pyenv global` version you should probably change it back as well. :

1. `pyenv global system` 
 
I'm not sure how `pyenv` handles the installation of linux packages when the `global` python version is not set to `system`. I tend to always leave my global set to system to avoid any unnecessary headaches.  

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

1. Have `pyenv local` set to any other python version than `system`
2. Open Piper using the piper.desktop or for error output open a terminal and type `piper` hit enter. Note opening from the piper.desktop will not show any error and you will likely need to find the log file.

**Logs**

I did not log any usage as this is a not so obvious operator error problem that I thought I could save some people the trouble  of fixing by the above explanation. If the piper team would like some logs anyway I'd be more than happy to provide them.

**Additional context**
Again you program works fine for me! I just thought that this guide might be helpful in diagnosing/helping others with the same issue in the future. This issue can be closed upon review if the piper dev team has no questions or need for further information.

**Comment by staticssleever668** [comment]
I don't know anything about pyenv, so I'll assume it's just a convenient way to create virtual environments for Python.

We don't have a requirements.txt with dependencies listed, but I think you only need `pygobject evdev lxml`.
For development it would also make sense to install `pygobject-stubs` (even though they are for GTK4 and not GTK3).

For example this seems to work for me:
```
python3 -m venv .venv
. ./.venv/bin/activate
pip3 install pygobject evdev lxml
meson setup build
meson compile -C build
./build/piper.devel
```

**Comment by staticssleever668** [comment]
Or does this mean that pyenv changes global python executable or module path, and when you use it, you can't even start Piper from desktop entry? If so, I'm pretty sure that would apply to any GUI application in Python, not just Piper.

**Comment by tetoNidan** [comment]
[staticssleever668](https://github.com/staticssleever668), `pyenv is just an easy python version manager. It makes it easy to have multiple python versions installed. This slight issue was the only drawback to using it in the last 9 months of using it. I usually change the `pyenv local version` back to system when I'm done testing something but hadn't done so and couldn't figure out what was going on when I installed piper this morning. I figured it out from running piper in the terminal which led my to see what version of python I had installed and what version pyenv was using. This led me to completely change my already started bug report.

>Or does this mean that pyenv changes global python executable or module path, and when you use it, you can't even start Piper from desktop entry? If so, I'm pretty sure that would apply to any GUI application in Python, not just Piper.

I'm assuming so. You can set your python version locally for a directory or globally and it will use that version. I had set my $USER's home directory to use python 3.11.3. I believe arch is using 3.11.5. I assume that any pure python application not bundled by something like preinstaller would face the same issues. i don't think I have any installed so I don't think I can test.

Like I said it's operator error in my case ant thought it'd be helpful to make note if it for others and in case someone tries to post a bug about it here without realizing that pyenv has changed the way your executable's python version. Hopefully they might see this and see if `pyenv` was the issue.

**Comment by tetoNidan** [comment]
I just thought of something that might work on your end but I'm not positive? Aren't users in groups able to execute programs that are defined for that group? Creating a piper group and adding the user to that group might work around someone setting their `pyenv local` version for their $USER's home directory..

I don't know if this would work as I never have any other users besides myself and therefore no need to create my own groups. This operator error would likely still persist in the event that someone changed their `pyenv global` version. That is it it works at all. I dont know how `pyenv` would execute the python whether it would be from the `system` version or the `local`. 

But like I said earlier I don't think this is pipers fault and I don't think you should have to fix operator error like this. I just want to be helpful to you and others by making small contributions when and where I can.

**Comment by staticssleever668** [comment]
> Aren't users in groups able to execute programs that are defined for that group? Creating a piper group and adding the user to that group might work around someone setting their pyenv local version for their $USER's home directory..

I haven't ever heard of something like this, for user's PATH to be determined from user groups.
In libratbag's case groups can be used to restrict access to D-Bus API for configuring mice, it's configured in [this](https://github.com/libratbag/libratbag/blob/6db5cc374352367937bf00098ba365e50d645ee5/dbus/org.freedesktop.ratbag1.conf.in#L14) file, which is created according to the `dbus-group` build option. On Arch access is not restricted to any group, but for example on OpenSUSE you need to be in the 'games' group.

Python packages are installed per Python environments and versions, when you install 'piper' package from your package manager, it's installed for your system environment and system's Python version, so, if you activate a virtual environment and try to run 'piper' command you will get `ModuleNotFoundError: No module named 'piper'`.
And it's exactly the same deal with pyenv.

---

Anyway, since we don't have anything to do about this on our side, let's close this.
Thank you for the info! :)
