### ISSUE TITLE
More RGB for model o

### ISSUE THREAD

**Issue by jdcdanguk** [libratbag/piper#910]
crap thing about piper no offence, is that the model o doesn't have as much RGB features on piper. Can you please add more

BTW: I think Piper is amazing I just think there is one crap thing about it

**Comment by staticssleever668** [comment]
Hi! There's a bunch of issues for more lighting options, e.g. #833.
You can have better luck with OpenRGB, an app made specifically made for configuring lighting modes, it support Model O.
