### ISSUE TITLE
Update Flatpak version, so most home users can access the new added mice configurations

### ISSUE THREAD

**Issue by KierPrev** [libratbag/piper#920]
The last flatpak update was over a year ago, and since that time, there were a LOT of new mice added.

Thanks.

**Comment by staticssleever668** [comment]
Hello! I'll try to make a new release soon, I've already made release notes even, just want to review last PR for a new driver on libratbag side and merge a little blocker I've fixed but didn't merge yet. :)
Also see #832.

**Comment by KierPrev** [comment]
Ups, sorry.  Yeah, this is even a duplicate of my own post #858  I forgot 💀
