### ISSUE TITLE
Got error "Ooops. ratbagd has disappeared" after 5 minutes after launching piper

### ISSUE THREAD

**Issue by koreanfan** [libratbag/piper#925]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Piper version: 0.7-1
- Distribution: debian stable branch
- Device: Logitech G102 Prodigy Gaming Mouse
- Kernel version (ex. `uname -srmo`): `Linux 6.1.0-16-amd64 x86_64 GNU/Linux`

**Describe the bug**
Got error "Ooops. ratbagd has disappeared" after 5 minutes after launching piper
**To Reproduce**
Launch piper. Wait 5 minutes. Got error "Ooops. ratbagd has disappeared"
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

1. Launch piper
2. Wait 5 minutes
3. Got error "Ooops. ratbagd has disappeared"

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```
Initializing libratbag
ratbag debug: New device: Logitech G102 Prodigy Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc084
ratbag debug: Logitech G102 Prodigy Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc084
ratbag debug: Logitech G102 Prodigy Gaming Mouse is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   11 ff 00 18 04 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 00 08 00 01 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: hidpp write:  10 ff 01 08 00 00 00
ratbag raw: hidpp read:   11 ff 01 08 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 01 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 02 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 03 00 02 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 03 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 04 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 01 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 05 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 02 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 06 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 06 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 07 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 08 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 09 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e b0 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0a 00 00
ratbag raw: hidpp read:   11 ff 01 18 22 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0b 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 b1 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0c 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 c2 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0d 00 00
ratbag raw: hidpp read:   11 ff 01 18 80 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0e 00 00
ratbag raw: hidpp read:   11 ff 01 18 80 70 00 04 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0f 00 00
ratbag raw: hidpp read:   11 ff 01 18 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 10 00 00
ratbag raw: hidpp read:   11 ff 01 18 81 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: 'Logitech G102 Prodigy Gaming Mouse' is using protocol v4.2
ratbag raw: 'Logitech G102 Prodigy Gaming Mouse' has 17 features
ratbag raw: Init feature HIDPP_PAGE_ROOT (0x0000) 
ratbag raw: hidpp write:  10 ff 00 08 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0000 is at 0x00
ratbag raw: Init feature HIDPP_PAGE_FEATURE_SET (0x0001) 
ratbag raw: hidpp write:  10 ff 00 08 00 01 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: Init feature HIDPP_PAGE_DEVICE_INFO (0x0003) 
ratbag raw: hidpp write:  10 ff 00 08 00 03 00
ratbag raw: hidpp read:   11 ff 00 08 02 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0003 is at 0x02
ratbag raw: unknown feature 0x0003
ratbag raw: Init feature HIDPP_PAGE_DEVICE_NAME (0x0005) 
ratbag raw: hidpp write:  10 ff 00 08 00 05 00
ratbag raw: hidpp read:   11 ff 00 08 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0005 is at 0x03
ratbag raw: unknown feature 0x0005
ratbag raw: Init feature 0x1801 (0x1801) 
ratbag raw: hidpp write:  10 ff 00 08 18 01 00
ratbag raw: hidpp read:   11 ff 00 08 04 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1801 is at 0x04
ratbag raw: Init feature 0x1802 (0x1802) 
ratbag raw: hidpp write:  10 ff 00 08 18 02 00
ratbag raw: hidpp read:   11 ff 00 08 05 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1802 is at 0x05
ratbag raw: Init feature 0x1806 (0x1806) 
ratbag raw: hidpp write:  10 ff 00 08 18 06 00
ratbag raw: hidpp read:   11 ff 00 08 06 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1806 is at 0x06
ratbag raw: Init feature 0x1e00 (0x1e00) 
ratbag raw: hidpp write:  10 ff 00 08 1e 00 00
ratbag raw: hidpp read:   11 ff 00 08 07 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1e00 is at 0x07
ratbag raw: Init feature 0x1e20 (0x1e20) 
ratbag raw: hidpp write:  10 ff 00 08 1e 20 00
ratbag raw: hidpp read:   11 ff 00 08 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1e20 is at 0x08
ratbag raw: unknown feature 0x1e20
ratbag raw: Init feature 0x1eb0 (0x1eb0) 
ratbag raw: hidpp write:  10 ff 00 08 1e b0 00
ratbag raw: hidpp read:   11 ff 00 08 09 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1eb0 is at 0x09
ratbag raw: Init feature HIDPP_PAGE_ADJUSTABLE_DPI (0x2201) 
ratbag raw: hidpp write:  10 ff 00 08 22 01 00
ratbag raw: hidpp read:   11 ff 00 08 0a 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x2201 is at 0x0a
ratbag debug: device has adjustable dpi
ratbag raw: hidpp write:  10 ff 0a 08 00 00 00
ratbag raw: hidpp read:   11 ff 0a 08 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0a 18 00 00 00
ratbag raw: hidpp read:   11 ff 0a 18 00 00 c8 e0 32 1f 40 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0a 28 00 00 00
ratbag raw: hidpp read:   11 ff 0a 28 00 01 5e 03 20 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: sensor 0: current dpi: 350 (default: 800) min: 200 max: 8000 steps: 50
ratbag debug: device is at 350 dpi (variable between 200 and 8000).
ratbag raw: Init feature 0x18b1 (0x18b1) 
ratbag raw: hidpp write:  10 ff 00 08 18 b1 00
ratbag raw: hidpp read:   11 ff 00 08 0b 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x18b1 is at 0x0b
ratbag raw: Init feature 0xc2 (0x00c2) 
ratbag raw: hidpp write:  10 ff 00 08 00 c2 00
ratbag raw: hidpp read:   11 ff 00 08 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x00c2 is at 0x0c
ratbag raw: unknown feature 0x00c2
ratbag raw: Init feature HIDPP_PAGE_ADJUSTABLE_REPORT_RATE (0x8060) 
ratbag raw: hidpp write:  10 ff 00 08 80 60 00
ratbag raw: hidpp read:   11 ff 00 08 0d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8060 is at 0x0d
ratbag debug: device has adjustable report rate
ratbag raw: hidpp write:  10 ff 0d 08 00 00 00
ratbag raw: hidpp read:   11 ff 0d 08 8b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0d 18 00 00 00
ratbag raw: hidpp read:   11 ff 0d 18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: report rate is 1000
ratbag debug: device has 4 report rates
ratbag raw: Init feature HIDPP_PAGE_COLOR_LED_EFFECTS (0x8070) 
ratbag raw: hidpp write:  10 ff 00 08 80 70 00
ratbag raw: hidpp read:   11 ff 00 08 0e 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8070 is at 0x0e
ratbag debug: device has color effects
ratbag raw: Init feature HIDPP_PAGE_ONBOARD_PROFILES (0x8100) 
ratbag raw: hidpp write:  10 ff 00 08 81 00 00
ratbag raw: hidpp read:   11 ff 00 08 0f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8100 is at 0x0f
ratbag debug: device has onboard profiles
ratbag raw: Init feature HIDPP_PAGE_MOUSE_BUTTON_SPY (0x8110) 
ratbag raw: hidpp write:  10 ff 00 08 81 10 00
ratbag raw: hidpp read:   11 ff 00 08 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8110 is at 0x10
ratbag debug: device has configurable mouse button spy
ratbag raw: hidpp write:  10 ff 0e 08 00 00 00
ratbag raw: hidpp read:   11 ff 0e 08 01 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0e 18 00 00 00
ratbag raw: hidpp read:   11 ff 0e 18 00 00 02 04 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: led_info 0: location: 2 type Side LED num_effects: 4 persistency_caps: 0x00
ratbag debug: initializing onboard profiles
ratbag raw: hidpp write:  10 ff 0f 08 00 00 00
ratbag raw: hidpp read:   11 ff 0f 08 01 02 01 01 01 06 07 01 00 0a 01 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0f 28 00 00 00
ratbag raw: hidpp read:   11 ff 0f 28 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0f 48 00 00 00
ratbag raw: hidpp read:   11 ff 0f 48 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: current active profile is index: 1 unknown_0: 0
ratbag debug: Reading sector 0x0000
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 01 01 00 ff ff 00 00 ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 00 00 f0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff b9 0d
ratbag debug: Parsing profile 0
ratbag debug: Reading sector 0x0001
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 01 01 00 5e 01 5e 01 5e 01 5e 01 5e 01 ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 80 01 00 01 80 01 00 02 90 ff ff 00 90 ff ff 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 90 ff ff 00 90 ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 00 00 00 00 00 00 00 00 00 00 03 00 00 00 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 1f 40 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 0f 58 00 01 00 f0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 0f 58 00 03 00 00 00 00 00 1f 40 00 00 00 ff ff 12 be
ratbag raw: hidpp write:  10 ff 0e 08 00 00 00
ratbag raw: hidpp read:   11 ff 0e 08 01 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0e 28 00 00 00
ratbag raw: hidpp read:   11 ff 0e 28 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0e 28 00 01 00
ratbag raw: hidpp read:   11 ff 0e 28 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0e 28 00 02 00
ratbag raw: hidpp read:   11 ff 0e 28 00 02 00 03 c0 05 03 e8 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 0e 28 00 03 00
ratbag raw: hidpp read:   11 ff 0e 28 00 03 00 0a c1 05 00 3c 00 00 00 00 00 00 00 00
ratbag debug: driver match found: Logitech HID++2.0
hidraw0: "Logitech G102 Prodigy Gaming Mouse", 1 profiles
ratbag debug: New device: Logitech G102 Prodigy Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc084
ratbag debug: Logitech G102 Prodigy Gaming Mouse is device '/dev/hidraw0'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: SEMICO USB Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1a2c:4b6a
ratbag debug: New device: SEMICO USB Keyboard
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1a2c:4b6a
DBus server ready
Exiting after idle

**Additional context**
![piper_bug](https://github.com/libratbag/piper/assets/60460757/4c8af28d-b216-46d3-afcc-25add12b3ca3)

**Comment by staticssleever668** [comment]
See the bottom of 'logs' - 'Exiting after idle', so that's expected.:)

**Comment by koreanfan** [comment]
my mouse start moves faster after some random period, piper show 350 dpi, but mouse moves faster like it was 750 dpi, mouse settings still the same(data from xinput list props and mouse settings from DE). Test 5 different mouse and got always the same result-mouse start moves faster after some random period
