### ISSUE TITLE
Unable to Detect Logitech MX Master 3 and Other Devices with Piper

### ISSUE THREAD

**Issue by gabrielpcardozo** [libratbag/piper#929]
I have encountered an issue while attempting to install Piper on my laptop. Despite successfully installing Piper using the command sudo apt-get install piper, the application is unable to detect my Logitech MX Master 3 mouse and other devices.

Installed Piper using the command sudo apt-get install piper.
Verified that the Piper service is running.
Restarted the computer after installation.

Operating System: Ubuntu 20
User Privileges: I am not the root user and do not have full access to my computer.

Is there a specific group membership or permission that needs to be granted to Piper for it to detect devices properly? As a non-root user with limited access, I would like guidance on how to resolve this issue and ensure Piper recognizes my Logitech MX Master 3 and other devices.

**Comment by staticssleever668** [comment]
Hi! To debug this, we would need the output of ratbagd in verbose mode, which would require root rights.
`sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw` - this commands stops the automatically-started instance of ratbagd and launches it manually (ctrl+c in the same terminal window can stop it).

**Comment by polimi-door-group** [comment]
Sorry to hijack the discussion but I have the same issue with a 3s on manjaro. Here's my output to that command:

`sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw`

```
Initializing libratbag
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
DBus server ready
```

**Comment by mrondr** [comment]
Sorry to hijack the discussion but I have the same issue with a 3s on Manjaro. Here's my output to that command:

```
Initializing libratbag
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
DBus server ready
```

**Comment by staticssleever668** [comment]
Not sure about Ubuntu, but for OpenSUSE the user has to be in the "games" group. Anyway, can't do anything without logs, sorry.
