### ISSUE TITLE
Packaging PIPER as Snap app

### ISSUE THREAD

**Issue by gocarlos** [libratbag/piper#93]
I’ve read the comments on the issue #5.
As far as I know, snap packaging system can already overcome those issues. 

As the next ubuntu release will ship with gnome and snap apps can be installed in the majority of the distros, I’d suggest to try the snap apps... 

Here is an example of a meson app for reference: https://github.com/snapcore/snapcraft/tree/0a62dc065b033e84925198e25fcba775a833e0ba/integration_tests/snaps/meson-hello 

And here the interfaces of the snap apps: 
https://snapcraft.io/docs/reference/interfaces

**Comment by whot** [comment]
fwiw, this is likely something we'll need help with, not sure any of the core devels here run ubuntu

**Comment by Hjdskes** [comment]
Yep, no Ubuntu here either. @gocarlos if you run Ubuntu, feel free to have a go and present your results!

**Comment by gocarlos** [comment]
i've started with libratbag, https://github.com/gocarlos/libratbag 

I could already build a snap package out of this locally, but was not able to build the snap package within the snapcraft.io 
https://build.snapcraft.io/user/gocarlos/libratbag/65014

I've asked the authors of snapcraft, if this could be a bug in their software.

**Comment by Hjdskes** [comment]
The log shows

> ```
> Meson encountered an error in file meson.build, line 33, column 0:
> Unknown function "add_project_arguments".
> ```

See https://github.com/libratbag/libratbag/issues/276 :)

**Comment by the-mentor** [comment]
+1

**Comment by Hjdskes** [comment]
Dont do that please, use the emoticons if you must.

**Comment by whot** [comment]
@gocarlos are you still working on this?

**Comment by whot** [comment]
Closing after 16m of inactivity.
