### ISSUE TITLE
Don't work with my mouse G203 in Fedora 39

### ISSUE THREAD

**Issue by Arthur-Negrao-Smith** [libratbag/piper#934]
**Information**
- `ratbagd` version: 0.17
- Piper version: 0.7
- Distribution: Fedora 39
- Device: Ryzen 5 5600G, 16GB Ram, A520m Asus TUF gaming plus ii
- Kernel version  `Linux 6.5.6-300.fc39.x86_64 x86_64 GNU/Linux`

don't recognize my mouse logitech G203

1. Go to FlatHub and install piper
2. Click to Open Piper
![Captura de tela de 2024-01-25 19-22-03](https://github.com/libratbag/piper/assets/122286293/33b6dd04-0d5b-4615-8045-d1d96e1ffd67)

3. See error

**Comment by staticssleever668** [comment]
Please, post the output of `sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw`.

**Comment by nakadzima9** [comment]
I have same problem in my distro openSUSE-Tumbleweed. `sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw`

Output this command:

`Initializing libratbag
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c09d
ratbag debug: New device: Logitech G102 LIGHTSYNC Gaming Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c09d
ratbag debug: New device: SYN1B8B:00 06CB:CE24
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 06cb:ce24
DBus server ready
`

piper version - **0.7**
ratbagd version - **0.17**
