### ISSUE TITLE
Does not work in debian 12 for logitech mx master 3s for mac 

### ISSUE THREAD

**Issue by mukulsharma9118** [libratbag/piper#935]
**Information**

- `ratbagd` 0.7
- Piper version:  0.7
- Distribution: Debian 12 x86-64
- Device: Hp Chromebox
- Kernel version - Linux 6.1.0-17-amd64 x86_64 GNU/Linux

**Describe the bug**
Does not work in debian 12 for logitech mx master 3s for mac 

**To Reproduce**
Open piper, Can't find device

Open piper
![Screenshot from 2024-01-26 10-50-52](https://github.com/libratbag/piper/assets/21037912/96ebf8e4-365e-4596-ab02-0051361153cc)

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Logitech MX Master 3S For Mac
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:b034
ratbag debug: New device: MX MCHNCL M
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:b36d
DBus server ready
```

**Comment by staticssleever668** [comment]
Hi!

Try putting this file into /usr/share/libratbag, where other .device files are: https://raw.githubusercontent.com/libratbag/libratbag/master/data/devices/logitech-MX-Master-3S.device
