### ISSUE TITLE
Logitech G602 - Piper/libratbag Problem

### ISSUE THREAD

**Issue by mglinux** [libratbag/piper#98]
Installed Piper from Aur, all fine.

Started ratbagd and got this:
ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; enabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Tue 2017-08-08 18:20:17 CEST; 1min 56s ago
  Process: 18686 ExecStart=/usr/bin/ratbagd (code=dumped, signal=SEGV)
 Main PID: 18686 (code=dumped, signal=SEGV)

ratbagd.service: Unit entered failed state.
ratbagd.service: Failed with result 'core-dump'.
ratbagd.service: Service hold-off time over, scheduling restart.
Stopped Daemon to introspect and modify configurable mice.
ratbagd.service: Start request repeated too quickly.
Failed to start Daemon to introspect and modify configurable mice.
ratbagd.service: Unit entered failed state.
ratbagd.service: Failed with result 'core-dump'.

After I restarted my computer and got no error. Ratbagd is running. sudo ratbagd and I can see some mouse related infos like battery percent and a few other things:

ratbag debug: Logitech USB Receiver is device '/dev/hidraw3'.
ratbag debug: Logitech USB Receiver is device '/dev/hidraw4'.
ratbag debug: report ID 01
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 80
ratbag debug: 'Logitech USB Receiver' is using protocol v2.0
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has adjustable dpi
ratbag error:     HID++ error from the device (1): ERR_INVALID_ADDRESS (02)
ratbag error: Error while requesting resolution: Protocol error (-71)
ratbag debug: device has adjustable report rate
ratbag debug: device has color effects
ratbag error:     HID++ error from the device (1): ERR_INVALID_ADDRESS (02)
Speicherzugriffsfehler (Speicherabzug geschrieben)

The wireless G602 should be working. ID 046d:c537 Logitech, Inc, it´s in the hwdb.

Don´t know what´s wrong here. 

Running Manjaro and installed from AUR

**Comment by Hjdskes** [comment]
The Piper AUR package uses the completely outdated release that shouldn't be used anymore. Use the libratbag-git AUR package and pull piper directly from master.
